# -*- coding: utf-8 -*-
"""scdm_cases phase-B case generator (CPython 3).
usage: python -B gen_cases.py specs\\B01_primitives.py [more specs...]
Each spec defines BATCH (str) and CASES = [(case_key, overrides_dict, build_body_str), ...].
case_key must be an inventory variant key (or overrides must give 'feature'); category/priority/params/commands
come from _inventory\\feature_inventory.json unless overridden. Writes <category>\\<case_key>.py and _batches\\<BATCH>.txt.
Only writes inside scdm_cases."""
import json, os, pprint, sys, textwrap, runpy

ROOT = r"D:\training\caedecoder\scdm_cases"
INV = os.path.join(ROOT, "_inventory", "feature_inventory.json")

HEAD = '''# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\\gen_cases.py from _gen\\specs\\{spec}.
# Batch: loaded by _framework\\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
'''
FOOT = '''
if "SCDM_BATCH" not in globals():
    execfile(r"D:\\training\\caedecoder\\scdm_cases\\_framework\\scdm_fw.py")
    run_standalone(CASE, build, r"{path}")
'''


def main(specs):
    with open(INV, encoding="utf-8") as f:
        inv = json.load(f)
    feats = {x["id"]: x for x in inv["features"]}
    variants = {}
    for x in inv["features"]:
        for v in x.get("variants", []):
            variants[v["case_key"]] = (x, v)
    total = 0
    for sp in specs:
        ns = runpy.run_path(sp)
        batch, cases = ns["BATCH"], ns["CASES"]
        lines, seen = [], set()
        for key, ov, body in cases:
            if key in seen:
                raise SystemExit("duplicate case key " + key)
            seen.add(key)
            if key in variants:
                feat, var = variants[key]
            else:
                feat = feats.get(ov["feature"]) or {"id": ov["feature"], "category": ov.get("category"),
                                                    "name_en": "Combo", "priority": ov.get("priority")}
                var = {"params": {}, "expect": ov.get("inventory_expect")}
            cat = ov.get("category", feat["category"])
            params = dict(var.get("params") or {})
            params.update(ov.get("params", {}))
            expect = dict(ov["expect"]) if "expect" in ov else {}
            case = {"case_id": key, "category": cat, "feature": feat["id"], "priority": ov.get("priority", feat.get("priority")),
                    "title": ov.get("title", "%s: %s" % (feat["name_en"], key.split("_", 3)[-1])),
                    "params": params, "expect": expect,
                    "inventory_expect": var.get("expect"),
                    "commands": ov.get("commands", feat.get("v19_api", [])),
                    "out_dir": os.path.join(ROOT, cat)}
            if ov.get("notes"):
                case["notes"] = ov["notes"]
            path = os.path.join(ROOT, cat, key + ".py")
            src = HEAD.format(spec=os.path.basename(sp)) + "CASE = " + pprint.pformat(case, width=110) + "\n\n\ndef build(ctx):\n" + \
                textwrap.indent(textwrap.dedent(body).strip("\n"), "    ") + "\n" + FOOT.format(path=path)
            compile(src.replace("execfile(", "exec_file("), path, "exec")
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\r\n") as f:
                f.write(src)
            lines.append(path)
        os.makedirs(os.path.join(ROOT, "_batches"), exist_ok=True)
        lp = os.path.join(ROOT, "_batches", batch + ".txt")
        with open(lp, "w", encoding="utf-8", newline="\r\n") as f:
            f.write("\n".join(lines) + "\n")
        print("%-20s %3d cases -> %s" % (batch, len(lines), lp))
        total += len(lines)
    print("total", total)


if __name__ == "__main__":
    main(sys.argv[1:])
