# scdm_cases generic batch runner: SpaceClaim 2019 R3 (V195) headless /RunScript over a list of case scripts.
# Writes only inside D:\training\caedecoder\scdm_cases. Never kills a SpaceClaim it did not start.
param(
  [Parameter(Mandatory=$true)][string]$BatchName,
  [Parameter(Mandatory=$true)][string]$CaseList,
  [string]$ResultDir = '',
  [string]$OutDir = '',
  [ValidateSet('headless', 'gui')][string]$Mode = 'headless',
  [string]$Manifest = 'D:\training\caedecoder\scdm_cases\manifest.json',
  [string]$Phase = '',
  [int]$TimeoutSec = 2400,
  [int]$StallSec = 600,
  [int]$ExitGraceSec = 90,
  [int]$BusyWaitMin = 15,
  [int]$QuietSec = 60,
  [int]$LicenseRetries = 2,
  [switch]$GuiRetryFailed
)
$ErrorActionPreference = 'Continue'
$Root = 'D:\training\caedecoder\scdm_cases'
$Fw   = "$Root\_framework"
$Exe  = 'C:\Program Files\ANSYS Inc\v195\SCDM\SpaceClaim.exe'
$Py   = 'C:\ProgramData\anaconda3\python.exe'
$Utf8 = New-Object System.Text.UTF8Encoding($false)
if (-not $ResultDir) { $ResultDir = Split-Path $CaseList -Parent }
foreach ($p in @($CaseList, $ResultDir, $Manifest)) {
  if (-not ([IO.Path]::GetFullPath($p)).StartsWith($Root, [StringComparison]::OrdinalIgnoreCase)) { "ABORT: path outside scdm_cases: $p"; exit 4 }
}
New-Item -ItemType Directory -Force -Path $ResultDir | Out-Null

function Wait-NotBusy {
  # SpaceClaim must be absent for two checks QuietSec apart (the demo licence server needs time to settle
  # after another SpaceClaim exits; launching too early gives CONNECT_ERROR / "License check Failed", exit 19).
  $deadline = (Get-Date).AddMinutes($BusyWaitMin)
  while ($true) {
    $b = @(Get-Process SpaceClaim -ErrorAction SilentlyContinue)
    if (-not $b.Count) {
      Start-Sleep -Seconds $QuietSec
      $b = @(Get-Process SpaceClaim -ErrorAction SilentlyContinue)
      if (-not $b.Count) { return $true }
    }
    if ((Get-Date) -gt $deadline) { return $false }
    Write-Host ("  SpaceClaim busy (PIDs " + ($b.Id -join ',') + "), waiting 60 s ...")
    Start-Sleep -Seconds 60
  }
}

function Invoke-SC([string]$list, [string]$mode) {
  $driver = "$ResultDir\${BatchName}_${mode}_driver.py"
  $result = "$ResultDir\${BatchName}_${mode}_result.json"
  $od = if ($OutDir) { "r`"$OutDir`"" } else { 'None' }
  $src = @"
# -*- coding: utf-8 -*-
# auto-generated by _framework\run_batch.ps1 ($(Get-Date -Format s))
import System, traceback
try:
    execfile(r"$Fw\scdm_fw.py")
    run_list_file(r"$BatchName", r"$list", r"$result", "$mode", $od)
except Exception:
    _m = traceback.format_exc().replace("\\", "/").replace('"', "'").replace("\r", " ").replace("\n", " | ")
    System.IO.File.WriteAllText(r"$result", '{"stage": "done", "fatal": "' + _m + '", "cases": []}')
"@
  [IO.File]::WriteAllText($driver, $src, $Utf8)
  Remove-Item $result -ErrorAction SilentlyContinue
  $attempt = 0
  while ($true) {
    if (-not (Wait-NotBusy)) { Write-Host "ABORT: SpaceClaim still running after $BusyWaitMin min"; return $null }
    $hl = if ($mode -eq 'headless') { ' /Headless=True' } else { '' }
    $argline = "/RunScript=`"$driver`" /ExitAfterScript=True /Splash=False /Welcome=False$hl"
    Write-Host "== RUN [$BatchName/$mode] `"$Exe`" $argline"
    $start = Get-Date; $sw = [Diagnostics.Stopwatch]::StartNew()
    $p = Start-Process -FilePath $Exe -ArgumentList $argline -PassThru
    $doneAt = $null; $killed = $null; $lastW = $null; $lastChange = 0
    while (-not $p.HasExited) {
      $t = $sw.Elapsed.TotalSeconds
      if ($t -gt $TimeoutSec) { $killed = "timeout ${TimeoutSec}s"; break }
      if (Test-Path $result) {
        $w = (Get-Item $result).LastWriteTimeUtc
        if ($w -ne $lastW) { $lastW = $w; $lastChange = $t }
        if (-not $doneAt) { $c = Get-Content $result -Raw -ErrorAction SilentlyContinue; if ($c -match '"stage": "done"') { $doneAt = $t } }
      }
      if ($doneAt -and ($t - $doneAt) -gt $ExitGraceSec) { $killed = "no exit ${ExitGraceSec}s after sentinel"; break }
      if ($lastW -and -not $doneAt -and ($t - $lastChange) -gt $StallSec) { $killed = "stall: result unchanged ${StallSec}s"; break }
      Start-Sleep -Seconds 2
    }
    if ($killed) { try { $p.Kill() } catch {} }
    Start-Sleep -Seconds 3
    Get-Process SpaceClaim -ErrorAction SilentlyContinue | Where-Object { $_.StartTime -ge $start } |
      ForEach-Object { Write-Host "  killing leftover SpaceClaim PID $($_.Id) (started by this runner)"; try { $_.Kill() } catch {} }
    $exit = $null; try { $exit = $p.ExitCode } catch {}
    Write-Host ("  wall_s={0:N1} exit={1} killed={2} sentinel_done_at_s={3}" -f $sw.Elapsed.TotalSeconds, $exit, $killed, $doneAt)
    $lic = $false
    if (-not (Test-Path $result) -and $p) {
      $lf = Join-Path $env:APPDATA ("SpaceClaim\Log Files\SpaceClaim_{0}_{1}_{2}_{3}.log" -f $start.Year, $start.Month, $start.Day, $p.Id)
      if ((Test-Path $lf) -and ((Get-Content $lf -Raw) -match 'License check Failed')) { $lic = $true }
      if ($exit -eq 19) { $lic = $true }
    }
    if ($lic -and $attempt -lt $LicenseRetries) { $attempt++; Write-Host "  licence failure (exit=$exit), retry $attempt/$LicenseRetries after quiet wait"; continue }
    break
  }
  $log = [ordered]@{ batch = $BatchName; mode = $mode; licence_retries = $attempt; cmd = "`"$Exe`" $argline"; started = $start.ToString('yyyy-MM-ddTHH:mm:sszzz'); wall_s = [math]::Round($sw.Elapsed.TotalSeconds, 1); exit = $exit; killed = $killed; sentinel_done_at_s = $doneAt; result = $result }
  [IO.File]::WriteAllText("$ResultDir\${BatchName}_${mode}_run.json", ($log | ConvertTo-Json), $Utf8)
  if (-not (Test-Path $result)) { Write-Host "  NO RESULT FILE"; return $null }
  return $result
}

function Invoke-Post([string]$result) {
  $env:PYTHONDONTWRITEBYTECODE = '1'
  & $Py -B "$Fw\fw_post.py" --result $result --manifest $Manifest --root $Root --failed-list "$ResultDir\${BatchName}_failed.txt" --phase $Phase 2>&1 | ForEach-Object { "$_" }
}

$r = Invoke-SC $CaseList $Mode
if ($r) { Invoke-Post $r }
$fl = "$ResultDir\${BatchName}_failed.txt"
if ($r -and $GuiRetryFailed -and $Mode -eq 'headless' -and (Test-Path $fl)) {
  Write-Host "== GUI retry of headless failures: $((Get-Content $fl | Where-Object { $_ }).Count) case(s)"
  Copy-Item $fl "$ResultDir\${BatchName}_failed_headless.txt" -Force
  $r2 = Invoke-SC "$ResultDir\${BatchName}_failed_headless.txt" 'gui'
  if ($r2) { Invoke-Post $r2 }
}
