# -*- coding: utf-8 -*-
# auto-generated by _framework\run_batch.ps1 (2026-09-26T08:09:22)
import System, traceback
try:
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_list_file(r"probe", r"D:\training\caedecoder\scdm_cases\_probe\probe_list.txt", r"D:\training\caedecoder\scdm_cases\_probe\probe_headless_result.json", "headless", None)
except Exception:
    _m = traceback.format_exc().replace("\\", "/").replace('"', "'").replace("\r", " ").replace("\n", " | ")
    System.IO.File.WriteAllText(r"D:\training\caedecoder\scdm_cases\_probe\probe_headless_result.json", '{"stage": "done", "fatal": "' + _m + '", "cases": []}')