# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_layers_002_hidden_locked',
 'category': '11_doc_attrs',
 'commands': ['Layers.Create/AssignLayer/SetColor/SetVisibility/SetLock/Rename'],
 'expect': {'bodies': 2},
 'feature': 'doc_layers',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'locked': True, 'visible': False},
 'priority': 'P0',
 'title': 'Layers (create, assign, color, visibility, lock): 002_hidden_locked'}


def build(ctx):
    a = block((0, 0, 0), (40, 30, 20), "Visible_Block")
    b = block((60, 0, 0), (100, 30, 20), "Hidden_Locked_Block")
    Layers.Create("L_hidden")
    Layers.AssignLayer(sel(b), "L_hidden")
    ctx.attempt("visibility", lambda: Layers.SetVisibility(List[str](["L_hidden"]), False))
    ctx.attempt("lock", lambda: Layers.SetLock("L_hidden", True))
    lay = [x for x in DocumentHelper.GetActiveDocument().Layers if unicode(x.Name) == "L_hidden"]
    ctx.data["layer_state"] = _safe(lambda: {"visible": unicode(_safe(lambda: lay[0].IsVisible(None))), "locked": unicode(_safe(lambda: lay[0].IsLocked))})
    if not (ctx.ok("visibility") and ctx.ok("lock")):
        raise Exception("layer visibility/lock failed")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_layers_002_hidden_locked.py")
