# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_rename_001_body_Block_A',
 'category': '11_doc_attrs',
 'commands': ['RenameObject.Execute(sel, name)', 'HasNameExtensions.SetName'],
 'expect': {'bodies': 1},
 'feature': 'doc_rename',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'name': 'Block_A'},
 'priority': 'P0',
 'title': 'Rename body/component (captions): 001_body_Block_A'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Temp_Name")
    RenameObject.Execute(sel(b), "Block_A")
    intent("body_name", unicode(all_bodies()[0].Name), u"Block_A")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_rename_001_body_Block_A.py")
