# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_drawing_001_A3_3views',
 'category': '11_doc_attrs',
 'commands': ['(raw API) DrawingSheet.Create', 'DrawingView.CreateGeneralView/CreateProjectedView'],
 'expect': {'drawing_sheets': 1},
 'feature': 'doc_drawing_sheet',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'format': 'A3', 'views': ['front', 'top', 'right']},
 'priority': 'P2',
 'title': 'Drawing sheet with general/projected views: 001_A3_3views'}


def build(ctx):
    block((0, 0, 0), (40, 30, 20), "Drawing_Block")
    doc = DocumentHelper.GetActiveDocument()
    ds = raw("sheet", lambda: DrawingSheet.Create(doc, 0.42, 0.297))
    _safe(lambda: raw("name", lambda: setattr(ds, "Name", "Sheet_A3")))
    v = raw("gv", lambda: DrawingView.CreateGeneralView(ds, master(GetRootPart()), Matrix.Identity, PointUV.Create(0.12, 0.18)))
    raw("pv_top", lambda: DrawingView.CreateProjectedView(v, PointUV.Create(0.12, 0.08)))
    raw("pv_right", lambda: DrawingView.CreateProjectedView(v, PointUV.Create(0.28, 0.18)))
    intent("views", _safe(lambda: ds.Views.Count), 3)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_drawing_001_A3_3views.py")
