# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_rename_002_unicode_name',
 'category': '11_doc_attrs',
 'commands': ['RenameObject.Execute(sel, name)', 'HasNameExtensions.SetName'],
 'expect': {'bodies': 1},
 'feature': 'doc_rename',
 'inventory_expect': None,
 'notes': 'deliberate non-ASCII body name (encoding test); English-name normalisation disabled for this case',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'name': '主体_测试'},
 'priority': 'P0',
 'title': 'Rename body/component (captions): 002_unicode_name'}


def build(ctx):
    ctx.data["keep_unicode_names"] = True
    b = block((0, 0, 0), (40, 30, 20), "Temp_Name")
    nm = u"\u4e3b\u4f53_\u6d4b\u8bd5"
    RenameObject.Execute(sel(b), nm)
    intent("body_name", unicode(all_bodies()[0].Name), nm)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_rename_002_unicode_name.py")
