# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_suppress_001',
 'category': '11_doc_attrs',
 'commands': ['ViewHelper.SetObjectVisibility', 'ViewHelper.SetSuppressForPhysics', 'ViewHelper.LockBodies'],
 'expect': {'bodies': 2},
 'feature': 'doc_visibility',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {},
 'priority': 'P2',
 'title': 'Visibility / suppress for physics / lock: 001'}


def build(ctx):
    a = block((0, 0, 0), (40, 30, 20), "Active_Block")
    b = block((60, 0, 0), (100, 30, 20), "Suppressed_Block")
    ViewHelper.SetSuppressForPhysics(sel(b), True)
    ctx.data["suppressed"] = _safe(lambda: unicode(master(b).IsSuppressed))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_suppress_001.py")
