# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_units_002_meter',
 'category': '11_doc_attrs',
 'commands': ['(raw API) Units / Document units setter (to locate); UnitsHelper.GetDocumentUnits is '
              'read-only'],
 'expect': {'bodies': 1},
 'feature': 'doc_units',
 'inventory_expect': None,
 'notes': 'fix: MetricUnits replaced via ctor MetricUnits(Meters, Kilograms, Degrees)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'units': 'M'},
 'priority': 'P1',
 'title': 'Document units (mm / m / inch): 002_meter'}


def build(ctx):
    block((0, 0, 0), (40, 30, 20), "Meter_Block")
    doc = DocumentHelper.GetActiveDocument()
    u = doc.Units
    MU, MM_, AU = rawt("MetricUnits"), rawt("MetricMassUnit"), rawt("AngleUnit")
    ctx.data["before"] = unicode(u.Length)
    raw("mu", lambda: setattr(u, "MetricUnits", MU(MetricLengthUnit.Meters, enum_pick(MM_, "Kilograms", "Kilogram"), AU.Degrees)))
    raw("units", lambda: setattr(u, "ActiveUnitsSystem", UnitsSystemType.Metric))
    ctx.data["after"] = [unicode(doc.Units.ActiveUnitsSystem), unicode(doc.Units.Length), unicode(_safe(lambda: doc.Units.MetricUnits.Length))]
    intent("metric_length_meters", unicode(_safe(lambda: doc.Units.MetricUnits.Length)), u"Meters")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_units_002_meter.py")
