# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_ns_002_edges_and_body',
 'category': '11_doc_attrs',
 'commands': ['NamedSelection.Create(primary, secondary)', 'NamedSelection.Rename/Replace/Delete'],
 'expect': {'bodies': 1},
 'feature': 'doc_named_selection',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'members': '4 edges + body'},
 'priority': 'P0',
 'title': 'Named selections (groups): 002_edges_and_body'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "NS_Block")
    tops = edges_at_z(b, 20)
    r = NamedSelection.Create(sel(list(tops) + [b]), Selection.Empty())
    NamedSelection.Rename(unicode(r.CreatedNamedSelection.Name), "Top_Edges_And_Body")
    ctx.data["member_count"] = _safe(lambda: len(list(r.CreatedNamedSelection.Items)))
    intent("top_edges", len(tops), 4)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_ns_002_edges_and_body.py")
