# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_datum_002_axis_and_point',
 'category': '11_doc_attrs',
 'commands': ['DatumPlaneCreator.Create',
              'DatumLineCreator.Create',
              'DatumPointCreator.Create',
              'DatumOriginCreator.Create'],
 'expect': {'bodies': 1},
 'feature': 'doc_datum',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {},
 'priority': 'P1',
 'title': 'Datum plane / axis / point / origin (coordinate system): 002_axis_and_point'}


def build(ctx):
    block((0, 0, 0), (40, 30, 20), "Datum_Block")
    first_ok(ctx, "datum_line", [lambda: DatumLineCreator.Create(P(0, 0, 0), D(0, 0, 1)),
                                 lambda: DatumLineCreator.Create(P(0, 0, 0), P(0, 0, 50))])
    first_ok(ctx, "datum_point", [lambda: DatumPointCreator.Create(P(10, 10, 10))])
    root = GetRootPart()
    ctx.data["datum_lines"] = _safe(lambda: root.DatumLines.Count)
    ctx.data["datum_points"] = _safe(lambda: root.DatumPoints.Count)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_datum_002_axis_and_point.py")
