# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_color_002_face_green',
 'category': '11_doc_attrs',
 'commands': ['ColorHelper.SetColor(sel, SetColorOptions, Color)', 'ColorHelper.SetFillStyle'],
 'expect': {'bodies': 1},
 'feature': 'doc_colors',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'rgb': [0, 200, 0], 'target': 'face +Z'},
 'priority': 'P0',
 'title': 'Body / face color, fill style: 002_face_green'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Green_Top_Block")
    ColorHelper.SetColor(sel(top_face(b)), SetColorOptions(), Color.FromArgb(255, 0, 200, 0))
    ctx.data["top_color"] = _safe(lambda: unicode(master(top_face(b)).GetColor(None)))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_color_002_face_green.py")
