# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_note_001_text_on_face',
 'category': '11_doc_attrs',
 'commands': ['(raw API) Note.Create'],
 'expect': {'bodies': 1},
 'feature': 'doc_notes',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'text': 'HELLO'},
 'priority': 'P2',
 'title': '3D notes / annotations: 001_text_on_face'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Note_Block")
    lp = enum_pick(LocationPoint, "Center", "MiddleCenter")
    top = top_face(b)
    mf = master(top)
    uv = _safe(lambda: mf.Shape.ProjectPoint(P(20, 15, 20)).Param) or PointUV.Create(0, 0)
    ctx.data["uv"] = unicode(uv)
    root = GetRootPart()
    dp_holder = []
    def on_datum():
        dp = raw("datum", lambda: DatumPlane.Create(master(root), "Note_Plane_On_Top", Plane.Create(Frame.Create(P(0, 0, 20), D(1, 0, 0), D(0, 1, 0)))))
        return raw("n", lambda: Note.Create(dp, PointUV.Create(MM(20), MM(15)), lp, MM(4), "HELLO"))
    n = first_ok(ctx, "note", [lambda: raw("n", lambda: Note.Create(mf, uv, lp, MM(4), "HELLO")),
                               lambda: raw("n", lambda: Note.Create(mf, PointUV.Create(MM(20), MM(15)), lp, MM(4), "HELLO")),
                               lambda: raw("n", lambda: Note.Create(top, uv, lp, MM(4), "HELLO")),
                               on_datum])
    ctx.data["note_parent"] = _safe(lambda: unicode(n.Parent.GetType().Name))
    ctx.data["note_text"] = _safe(lambda: unicode(n.Text))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_note_001_text_on_face.py")
