# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_material_001_steel',
 'category': '11_doc_attrs',
 'commands': ['(raw API) DocumentMaterial.Create / LibraryMaterial -> DesignBody.Material'],
 'expect': {'bodies': 1},
 'feature': 'doc_material',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'material': 'Steel'},
 'priority': 'P2',
 'title': 'Material assignment: 001_steel'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Steel_Block")
    doc = DocumentHelper.GetActiveDocument()
    m = raw("material", lambda: DocumentMaterial.Create(doc, "Steel", 7850.0))
    raw("assign", lambda: setattr(master(b), "Material", m))
    intent("body_material", _safe(lambda: unicode(master(b).Material.Name)), u"Steel")
    ctx.data["mass_props"] = _safe(lambda: [unicode(master(b).MassProperties.Mass), unicode(master(b).MassProperties.Volume)])
    ctx.data["material_density"] = _safe(lambda: unicode(m.MaterialProperties))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_material_001_steel.py")
