# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_layers_001_two_layers_assign',
 'category': '11_doc_attrs',
 'commands': ['Layers.Create/AssignLayer/SetColor/SetVisibility/SetLock/Rename'],
 'expect': {'bodies': 2},
 'feature': 'doc_layers',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'layers': ['L_red', 'L_blue']},
 'priority': 'P0',
 'title': 'Layers (create, assign, color, visibility, lock): 001_two_layers_assign'}


def build(ctx):
    a = block((0, 0, 0), (40, 30, 20), "Red_Block")
    b = block((60, 0, 0), (100, 30, 20), "Blue_Block")
    Layers.Create("L_red")
    Layers.Create("L_blue")
    Layers.AssignLayer(sel(a), "L_red")
    Layers.AssignLayer(sel(b), "L_blue")
    Layers.SetColor(List[str](["L_red"]), Color.FromArgb(255, 255, 0, 0), True)
    Layers.SetColor(List[str](["L_blue"]), Color.FromArgb(255, 0, 0, 255), True)
    L = doc_stats()["layers"]
    intent("has_L_red_L_blue", any("L_red" in unicode(x) for x in L) and any("L_blue" in unicode(x) for x in L), True)
    ctx.data["body_layers"] = [unicode(_safe(lambda: master(x).Layer.Name)) for x in all_bodies()]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_layers_001_two_layers_assign.py")
