# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_datum_003_origin_rotated',
 'category': '11_doc_attrs',
 'commands': ['DatumPlaneCreator.Create',
              'DatumLineCreator.Create',
              'DatumPointCreator.Create',
              'DatumOriginCreator.Create'],
 'expect': {'bodies': 1},
 'feature': 'doc_datum',
 'inventory_expect': None,
 'notes': 'doc_stats reports coordinate_systems=2 for one DatumOriginCreator origin (walk counts it twice); '
          'checked as range 1..2',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'rot_deg': 30},
 'priority': 'P1',
 'title': 'Datum plane / axis / point / origin (coordinate system): 003_origin_rotated'}


def build(ctx):
    import math
    block((0, 0, 0), (40, 30, 20), "Datum_Block")
    a = math.radians(30)
    DatumOriginCreator.Create(P(0, 0, 0), D(math.cos(a), math.sin(a), 0), D(-math.sin(a), math.cos(a), 0))
    intent_range("coordinate_systems", doc_stats()["coordinate_systems"], 1, 2)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_datum_003_origin_rotated.py")
