# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_view_002_two_views',
 'category': '11_doc_attrs',
 'commands': ['ViewHelper.CreateNamedView', 'ViewHelper.SetProjection', 'ViewHelper.SetSectionPlane'],
 'expect': {'bodies': 1},
 'feature': 'doc_named_view',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'names': ['Front', 'Top']},
 'priority': 'P1',
 'title': 'Named views / section plane: 002_two_views'}


def build(ctx):
    block((0, 0, 0), (40, 30, 20), "View_Block")
    ViewHelper.SetProjection(ViewHelper.ViewProjection.Front, True, False)
    ViewHelper.CreateNamedView("Front")
    ViewHelper.SetProjection(ViewHelper.ViewProjection.Top, True, False)
    ViewHelper.CreateNamedView("Top")
    intent("activate_Front", bool(ViewHelper.ActivateNamedView("Front", True, False)), True)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_view_002_two_views.py")
