# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_color_001_body_red',
 'category': '11_doc_attrs',
 'commands': ['ColorHelper.SetColor(sel, SetColorOptions, Color)', 'ColorHelper.SetFillStyle'],
 'expect': {'bodies': 1},
 'feature': 'doc_colors',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'rgb': [255, 0, 0], 'target': 'body'},
 'priority': 'P0',
 'title': 'Body / face color, fill style: 001_body_red'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Red_Body")
    o = SetColorOptions()
    setp(ctx, o, [("FaceColorTarget", _safe(lambda: FaceColorTarget.Body))], "color_opts")
    ColorHelper.SetColor(sel(b), o, Color.FromArgb(255, 255, 0, 0))
    ctx.data["body_color"] = _safe(lambda: unicode(master(b).GetColor(None)))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_color_001_body_red.py")
