# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_datum_001_plane_offset_z10',
 'category': '11_doc_attrs',
 'commands': ['DatumPlaneCreator.Create',
              'DatumLineCreator.Create',
              'DatumPointCreator.Create',
              'DatumOriginCreator.Create'],
 'expect': {'datum_planes': 1},
 'feature': 'doc_datum',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'normal': [0, 0, 1], 'origin': [0, 0, 10]},
 'priority': 'P1',
 'title': 'Datum plane / axis / point / origin (coordinate system): 001_plane_offset_z10'}


def build(ctx):
    block((0, 0, 0), (40, 30, 20), "Datum_Block")
    DatumPlaneCreator.Create(P(0, 0, 10), D(0, 0, 1))
    dp = list(GetRootPart().DatumPlanes)[-1]
    _safe(lambda: set_name(dp, "Plane_Z10"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_datum_001_plane_offset_z10.py")
