# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_ns_003_renamed',
 'category': '11_doc_attrs',
 'commands': ['NamedSelection.Create(primary, secondary)', 'NamedSelection.Rename/Replace/Delete'],
 'expect': {'bodies': 1},
 'feature': 'doc_named_selection',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'rename': ['Group1', 'Inlet']},
 'priority': 'P0',
 'title': 'Named selections (groups): 003_renamed'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "NS_Block")
    r = NamedSelection.Create(sel(face_extreme(b, (1, 0, 0), -1)), Selection.Empty())
    old = unicode(r.CreatedNamedSelection.Name)
    ctx.data["default_name"] = old
    NamedSelection.Rename(old, "Group1")
    NamedSelection.Rename("Group1", "Inlet")
    intent("ns_names", [unicode(x) for x in doc_stats()["named_selections"]], [u"Inlet"])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_ns_003_renamed.py")
