# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_coordsys_001_translated_rotated',
 'category': '11_doc_attrs',
 'commands': ['(raw API) CoordinateSystem.Create', 'DatumOriginCreator.Create'],
 'expect': {'bodies': 1},
 'feature': 'doc_coordsys',
 'inventory_expect': None,
 'notes': 'raw CoordinateSystem.Create; doc_stats reports coordinate_systems=2 (range-checked)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'origin': [10, 0, 0], 'rot_deg': 30},
 'priority': 'P2',
 'title': 'Coordinate system: 001_translated_rotated'}


def build(ctx):
    import math
    block((0, 0, 0), (40, 30, 20), "CS_Block")
    a = math.radians(30)
    fr = Frame.Create(P(10, 0, 0), D(math.cos(a), math.sin(a), 0), D(-math.sin(a), math.cos(a), 0))
    CS = rawt("CoordinateSystem")
    root = GetRootPart()
    first_ok(ctx, "coordsys", [lambda: raw("cs", lambda: CS.Create(master(root), "CS_1", fr)),
                               lambda: raw("cs", lambda: CS.Create(root, "CS_1", fr)),
                               lambda: DatumOriginCreator.Create(P(10, 0, 0), fr.DirX, fr.DirY)])
    intent_range("coordinate_systems", doc_stats()["coordinate_systems"], 1, 2)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_coordsys_001_translated_rotated.py")
