# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B09_doc_attrs.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_units_001_inch',
 'category': '11_doc_attrs',
 'commands': ['(raw API) Units / Document units setter (to locate); UnitsHelper.GetDocumentUnits is '
              'read-only'],
 'expect': {'bodies': 1},
 'feature': 'doc_units',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\11_doc_attrs',
 'params': {'units': 'IN'},
 'priority': 'P1',
 'title': 'Document units (mm / m / inch): 001_inch'}


def build(ctx):
    block((0, 0, 0), (25.4, 50.8, 76.2), "Inch_Block")
    doc = DocumentHelper.GetActiveDocument()
    u = doc.Units
    IU, IM, AU = rawt("ImperialUnits"), rawt("ImperialMassUnit"), rawt("AngleUnit")
    first_ok(ctx, "imperial_units", [lambda: raw("iu", lambda: setattr(u, "ImperialUnits", IU(ImperialLengthUnit.Inches, enum_pick(IM, "Pounds", "PoundMass", "Pound"), AU.Degrees))),
                                     lambda: None])
    raw("units", lambda: setattr(u, "ActiveUnitsSystem", UnitsSystemType.Imperial))
    ctx.data["units_after"] = [unicode(doc.Units.ActiveUnitsSystem), unicode(doc.Units.Length)]
    intent("units_system", unicode(doc.Units.ActiveUnitsSystem), u"Imperial")
    intent("length_is_inch", "inch" in unicode(_safe(lambda: doc.Units.ImperialUnits.Length)).lower(), True)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\11_doc_attrs\11_doc_units_001_inch.py")
