# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B04_edge.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '04_edge_round_001_block_1edge_r3',
 'category': '04_edge',
 'commands': ['ConstantRound.Execute(sel edges, radius, ConstantRoundOptions)'],
 'expect': {'bodies': 1, 'faces': 7, 'volume_mm3': 23922.750307},
 'feature': 'edge_round',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\04_edge',
 'params': {'base': 'block 40x30x20', 'edges': 1, 'r_mm': 3},
 'priority': 'P0',
 'title': 'Constant radius round (fillet): 001_block_1edge_r3'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Round_Block_1Edge")
    e = edge_nearest(b, (20, 30, 20), "Line")
    ctx.data["edge_mid_mm"] = edge_mid(e)
    ConstantRound.Execute(sel(e), MM(3), ConstantRoundOptions())

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\04_edge\04_edge_round_001_block_1edge_r3.py")
