# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B04_edge.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '04_edge_chamfer_003_cyl_top_d1',
 'category': '04_edge',
 'commands': ['Chamfer.Execute(sel, distance)', 'Chamfer.Execute(sel, d1, d2)'],
 'expect': {'bodies': 1, 'faces': 4},
 'feature': 'edge_chamfer',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\04_edge',
 'params': {'base': 'cyl r10 h20', 'd_mm': 1},
 'priority': 'P0',
 'title': 'Chamfer (equal/unequal): 003_cyl_top_d1'}


def build(ctx):
    b = cylinder((0, 0, 0), (0, 0, 20), 10, "Chamfer_Cyl_Top")
    Chamfer.Execute(sel(edges_at_z(b, 20)), MM(1))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\04_edge\04_edge_chamfer_003_cyl_top_d1.py")
