# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B04_edge.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '04_edge_splitround_001',
 'category': '04_edge',
 'commands': ['SplitRound.Execute', 'NamedSelection.RestoreRounds', 'RoundInfo.Create'],
 'expect': {'bodies': 1},
 'feature': 'edge_split_round',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\04_edge',
 'params': {'base': 'block+round r3'},
 'priority': 'P2',
 'title': 'Round utilities (split round, restore rounds): 001'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "SplitRound_Block")
    e = edge_nearest(b, (20, 30, 20), "Line")
    ConstantRound.Execute(sel(e), MM(3), ConstantRoundOptions())
    b = body_named("SplitRound_Block")
    rf = faces(b, "Cylinder")[0]
    res = [x for x in rf.Edges]
    long_edges = [x for x in res if gtype(x) == "Line"]
    ctx.data["round_face_edges"] = [[gtype(x), edge_mid(x)] for x in res]
    ctx.data["long_edges"] = len(long_edges)
    e0 = long_edges[0]
    m = edge_mid(e0)
    first_ok(ctx, "splitround", [
        lambda: SplitRound.Execute(sel(e0), P(*m), MM(2)),
        lambda: SplitRound.Execute(sel(e0), P(*m), 0.0)])
    ctx.data["faces_after"] = shape_of(body_named("SplitRound_Block")).Faces.Count

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\04_edge\04_edge_splitround_001.py")
