# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B04_edge.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '04_edge_chamfer_001_block_1edge_d2',
 'category': '04_edge',
 'commands': ['Chamfer.Execute(sel, distance)', 'Chamfer.Execute(sel, d1, d2)'],
 'expect': {'bodies': 1, 'faces': 7, 'volume_mm3': 23920.0},
 'feature': 'edge_chamfer',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\04_edge',
 'params': {'d_mm': 2},
 'priority': 'P0',
 'title': 'Chamfer (equal/unequal): 001_block_1edge_d2'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Chamfer_Block_1Edge")
    e = edge_nearest(b, (20, 30, 20), "Line")
    Chamfer.Execute(sel(e), MM(2))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\04_edge\04_edge_chamfer_001_block_1edge_d2.py")
