# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B04_edge.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '04_edge_round_003_cyl_top_r2',
 'category': '04_edge',
 'commands': ['ConstantRound.Execute(sel edges, radius, ConstantRoundOptions)'],
 'expect': {'bodies': 1, 'faces': 4},
 'feature': 'edge_round',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\04_edge',
 'params': {'base': 'cyl r10 h20', 'edges': 'top circle', 'r_mm': 2},
 'priority': 'P0',
 'title': 'Constant radius round (fillet): 003_cyl_top_r2'}


def build(ctx):
    b = cylinder((0, 0, 0), (0, 0, 20), 10, "Round_Cyl_Top")
    es = edges_at_z(b, 20)
    ctx.data["top_edges"] = len(es)
    ConstantRound.Execute(sel(es), MM(2), ConstantRoundOptions())

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\04_edge\04_edge_round_003_cyl_top_r2.py")
