# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B04_edge.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '04_edge_fullround_001_rib_3faces',
 'category': '04_edge',
 'commands': ['FullRound.Execute(selFaces)'],
 'expect': {'bodies': 1},
 'feature': 'edge_full_round',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\04_edge',
 'params': {'base': 'block 40x5x10', 'faces': 'side-top-side'},
 'priority': 'P2',
 'title': 'Full round: 001_rib_3faces'}


def build(ctx):
    b = block((0, 0, 0), (40, 5, 10), "Rib")
    fs = [face_extreme(b, (0, 1, 0), -1), top_face(b), face_extreme(b, (0, 1, 0), 1)]
    first_ok(ctx, "fullround", [
        lambda: FullRound.Execute(sel(fs)),
        lambda: FullRound.Execute(sel(fs[1], fs[0], fs[2]))])
    ctx.data["cylinder_faces"] = len(faces(body_named("Rib"), "Cylinder"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\04_edge\04_edge_fullround_001_rib_3faces.py")
