# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B04_edge.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '04_edge_round_004_vertex_blend_3edges_r4',
 'category': '04_edge',
 'commands': ['ConstantRound.Execute(sel edges, radius, ConstantRoundOptions)'],
 'expect': {'bodies': 1},
 'feature': 'edge_round',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\04_edge',
 'params': {'edges': '3 edges meeting at vertex', 'r_mm': 4},
 'priority': 'P0',
 'title': 'Constant radius round (fillet): 004_vertex_blend_3edges_r4'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Round_Vertex_Blend")
    es = [edge_nearest(b, p, "Line") for p in [(20, 30, 20), (40, 15, 20), (40, 30, 10)]]
    ctx.data["edge_mids_mm"] = [edge_mid(e) for e in es]
    ConstantRound.Execute(sel(es), MM(4), ConstantRoundOptions())

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\04_edge\04_edge_round_004_vertex_blend_3edges_r4.py")
