# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B10_beam_sheetmetal.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '08_sheetmetal_convert_001_block_t2',
 'category': '08_sheetmetal',
 'commands': ['NONE in SpaceClaim.Api.V19.Scripting; raw API SheetMetalAspect/Bend are read-only (no '
              'Create)'],
 'expect': {'bodies': 1, 'volume_mm3': 10000.0},
 'feature': 'sm_all',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\08_sheetmetal',
 'params': {'base': 'block 100x50x2', 'thickness_mm': 2},
 'priority': 'P1',
 'title': 'Sheet metal (convert, flange, bend, unfold, junction, relief): 001_block_t2'}


def build(ctx):
    block((0, 0, 0), (100, 50, 2), "Sheet_Plate_T2")
    root = GetRootPart()
    raw("sheetmetal", lambda: master(root).ConvertToSheetMetal())
    intent("part_type", unicode(_safe(lambda: master(root).Type)), u"SheetMetal")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\08_sheetmetal\08_sheetmetal_convert_001_block_t2.py")
