# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B10_beam_sheetmetal.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '08_sheetmetal_unfold_001',
 'category': '08_sheetmetal',
 'commands': ['NONE in SpaceClaim.Api.V19.Scripting; raw API SheetMetalAspect/Bend are read-only (no '
              'Create)'],
 'expect': {},
 'feature': 'sm_all',
 'inventory_expect': None,
 'notes': 'L-bracket with bend (as flange_001), then SheetMetalAspect.Unfold(base bottom face)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\08_sheetmetal',
 'params': {},
 'priority': 'P1',
 'title': 'Sheet metal (convert, flange, bend, unfold, junction, relief): 001'}


def build(ctx):
    a = block((0, 0, 0), (100, 50, 2), "Bracket")
    w = block((98, 0, 2), (100, 50, 22), "Wall")
    Combine.Merge(sel(a, w))
    b = largest()
    root = GetRootPart()
    raw("sheetmetal", lambda: master(root).ConvertToSheetMetal())
    b = largest()
    asp = master(root).SheetMetal
    LE = List[rawt("DesignEdge")]
    ctx.attempt("bends", lambda: raw("bend", lambda: asp.CreateMissingBends(LE([master(edge_nearest(b, (98, 25, 2)))]), MM(1))))
    anchor = bottom_face(largest())
    f = first_ok(ctx, "unfold", [lambda: raw("unfold", lambda: asp.Unfold(master(anchor)))])
    ctx.data["unfold_result"] = _safe(lambda: unicode(f.GetType().Name))
    ctx.data["flat_pattern"] = _safe(lambda: unicode(master(root).FlatPattern))
    ctx.data["bboxes"] = [bbox(x) for x in all_bodies()]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\08_sheetmetal\08_sheetmetal_unfold_001.py")
