# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B10_beam_sheetmetal.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '08_sheetmetal_flange_001_90deg_l20',
 'category': '08_sheetmetal',
 'commands': ['NONE in SpaceClaim.Api.V19.Scripting; raw API SheetMetalAspect/Bend are read-only (no '
              'Create)'],
 'expect': {'bodies': 1},
 'feature': 'sm_all',
 'inventory_expect': None,
 'notes': 'flange realised as L-shaped plate (base 100x50x2 + 20 mm wall) converted to sheet metal, then '
          'SheetMetalAspect.CreateMissingBends(r=1) on the crease (8 faces + 2 bend faces)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\08_sheetmetal',
 'params': {'angle_deg': 90, 'bend_r_mm': 1, 'length_mm': 20},
 'priority': 'P1',
 'title': 'Sheet metal (convert, flange, bend, unfold, junction, relief): 001_90deg_l20'}


def build(ctx):
    a = block((0, 0, 0), (100, 50, 2), "Flange_Part")
    w = block((98, 0, 2), (100, 50, 22), "Wall")
    Combine.Merge(sel(a, w))
    b = largest()
    root = GetRootPart()
    raw("sheetmetal", lambda: master(root).ConvertToSheetMetal())
    b = largest()
    asp = master(root).SheetMetal
    ctx.data["aspect_members"] = [n for n in dir(asp) if not n.startswith("_")]
    _safe(lambda: ctor_sigs(ctx, "BendSpecification"))
    inner = edge_nearest(b, (98, 25, 2))
    outer = edge_nearest(b, (100, 25, 0))
    LE = List[rawt("DesignEdge")]
    first_ok(ctx, "bends", [lambda: raw("bend", lambda: asp.CreateMissingBends(LE([master(inner)]), MM(1))),
                            lambda: raw("bend", lambda: asp.CreateMissingBends(LE([master(outer)]), MM(1))),
                            lambda: raw("bend", lambda: asp.CreateMissingBends(LE([master(inner), master(outer)]), MM(1)))])
    ctx.data["faces_after"] = face_count(largest())
    intent("faces_after_bend", face_count(largest()), 10)
    intent("volume_mm3", round(total_volume(), 2), 11914.17, 0.5)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\08_sheetmetal\08_sheetmetal_flange_001_90deg_l20.py")
