# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_splitbody_002_cyl_by_oblique_plane',
 'category': '05_boolean',
 'commands': ['SplitBody.ByCutter(body, Plane)', 'SplitBody.ByCutter(body, toolFaces, extend)'],
 'expect': {'bodies': 2, 'volume_mm3': 12566.370614},
 'feature': 'bool_split_body',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'plane': 'normal (1,0,1)'},
 'priority': 'P0',
 'title': 'Split body by plane / face / body: 002_cyl_by_oblique_plane'}


def build(ctx):
    b = cylinder((0, 0, 0), (0, 0, 40), 10, "Split_Cyl")
    s = 2 ** -0.5
    SplitBody.ByCutter(sel(b), Plane.Create(Frame.Create(P(0, 0, 20), D(s, 0, -s), D(0, 1, 0))))
    bs = sorted(bodies_now(), key=lambda x: bbox_center(x)[2])
    name_bodies(["Split_Cyl_Lower", "Split_Cyl_Upper"], bs)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_splitbody_002_cyl_by_oblique_plane.py")
