# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_imprint_001_block_cyl_curves',
 'category': '05_boolean',
 'commands': ['Combine.Intersect(target, tool, MakeCurvesOptions)', 'FixImprint'],
 'expect': {'bodies': 2},
 'feature': 'bool_imprint',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'mode': 'MakeCurves'},
 'priority': 'P1',
 'title': 'Imprint / intersect to curves: 001_block_cyl_curves'}


def build(ctx):
    a = block((0, 0, 0), (40, 40, 20), "Imprint_Block")
    c = cylinder((20, 20, 10), (20, 20, 40), 5, "Imprint_Tool")
    fa = shape_of(a).Faces.Count
    Combine.Intersect(sel(a), sel(c), MakeCurvesOptions())
    ctx.data["block_faces_before_after"] = [fa, shape_of(body_named("Imprint_Block")).Faces.Count]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_imprint_001_block_cyl_curves.py")
