# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_splitbody_003_by_face',
 'category': '05_boolean',
 'commands': ['SplitBody.ByCutter(body, Plane)', 'SplitBody.ByCutter(body, toolFaces, extend)'],
 'expect': {'bodies': 3},
 'feature': 'bool_split_body',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'tool': 'face of other body'},
 'priority': 'P0',
 'title': 'Split body by plane / face / body: 003_by_face'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Split_Target")
    t = sheet_rect(-10, -10, 50, 40, 8, "Split_Tool_Sheet")
    SplitBody.ByCutter(sel(b), sel(face0(t)), True)
    solids = sorted([x for x in bodies_now() if not is_sheet(x)], key=lambda x: bbox_center(x)[2])
    name_bodies(["Split_By_Face_Lower", "Split_By_Face_Upper"], solids)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_splitbody_003_by_face.py")
