# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_merge_001_two_blocks_overlap',
 'category': '05_boolean',
 'commands': ['Combine.Merge(target, tool)', 'MergeBodies.Execute'],
 'expect': {'bodies': 1, 'volume_mm3': 15000.0},
 'feature': 'bool_merge',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'a': 'block 0..20', 'b': 'block 10..30'},
 'priority': 'P0',
 'title': 'Combine - merge (union): 001_two_blocks_overlap'}


def build(ctx):
    a = block((0, 0, 0), (20, 20, 20), "Merge_A")
    b = block((10, 10, 10), (30, 30, 30), "Merge_B")
    first_ok(ctx, "merge", [
        lambda: Combine.Merge(sel(a, b)),
        lambda: Combine.Merge(sel(a), sel(b))])
    name_bodies(["Merged_Blocks"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_merge_001_two_blocks_overlap.py")
