# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_subtract_003_keep_cutter',
 'category': '05_boolean',
 'commands': ['Combine.Intersect(target, tool, MakeSolidsOptions)', 'Combine.RemoveRegions'],
 'expect': {'bodies': 2},
 'feature': 'bool_subtract',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'keepCutter': True},
 'priority': 'P0',
 'title': 'Combine - subtract (cut body with tool, RemoveRegions): 003_keep_cutter'}


def build(ctx):
    a = block((0, 0, 0), (40, 40, 20), "Plate")
    c = cylinder((20, 20, -5), (20, 20, 25), 5, "Cutter")
    k = subtract(ctx, a, c, keep_cutter=True)
    name_bodies(["Plate_With_Hole", "Cutter_Kept"], k)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_subtract_003_keep_cutter.py")
