# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_subtract_002_block_minus_sphere',
 'category': '05_boolean',
 'commands': ['Combine.Intersect(target, tool, MakeSolidsOptions)', 'Combine.RemoveRegions'],
 'expect': {'bodies': 1, 'volume_mm3': 62232.854132},
 'feature': 'bool_subtract',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'a': 'block 40', 'b': 'sphere r15 at corner'},
 'priority': 'P0',
 'title': 'Combine - subtract (cut body with tool, RemoveRegions): 002_block_minus_sphere'}


def build(ctx):
    a = block((0, 0, 0), (40, 40, 40), "Cube")
    s = sphere((40, 40, 40), 15, "Corner_Sphere")
    k = subtract(ctx, a, s)
    name_bodies(["Cube_Corner_Cut"], k)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_subtract_002_block_minus_sphere.py")
