# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_splitbody_001_block_by_plane_mid',
 'category': '05_boolean',
 'commands': ['SplitBody.ByCutter(body, Plane)', 'SplitBody.ByCutter(body, toolFaces, extend)'],
 'expect': {'bodies': 2, 'volume_mm3': 24000.0},
 'feature': 'bool_split_body',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'plane': 'z=10'},
 'priority': 'P0',
 'title': 'Split body by plane / face / body: 001_block_by_plane_mid'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Split_Block")
    SplitBody.ByCutter(sel(b), plane_xy(10))
    bs = sorted(bodies_now(), key=lambda x: bbox_center(x)[2])
    name_bodies(["Split_Lower", "Split_Upper"], bs)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_splitbody_001_block_by_plane_mid.py")
