# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_intersect_001_block_sphere',
 'category': '05_boolean',
 'commands': ['Combine.Intersect + RemoveRegions'],
 'expect': {'bodies': 1},
 'feature': 'bool_intersect',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'a': 'block 20', 'b': 'sphere r14 centered'},
 'priority': 'P0',
 'title': 'Combine - intersect (common): 001_block_sphere'}


def build(ctx):
    a = block((-10, -10, -10), (10, 10, 10), "Cube20")
    s = sphere((0, 0, 0), 14, "Sphere14")
    k = intersect_keep(ctx, a, s)
    name_bodies(["Cube_Sphere_Common"], [k])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_intersect_001_block_sphere.py")
