# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_intersect_002_two_cylinders_cross',
 'category': '05_boolean',
 'commands': ['Combine.Intersect + RemoveRegions'],
 'expect': {'bodies': 1, 'volume_mm3': 5333.333333},
 'feature': 'bool_intersect',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'a': 'cyl X r10', 'b': 'cyl Y r10'},
 'priority': 'P0',
 'title': 'Combine - intersect (common): 002_two_cylinders_cross'}


def build(ctx):
    a = cylinder((-30, 0, 0), (30, 0, 0), 10, "Cyl_X")
    b = cylinder((0, -30, 0), (0, 30, 0), 10, "Cyl_Y")
    k = intersect_keep(ctx, a, b)
    name_bodies(["Steinmetz"], [k])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_intersect_002_two_cylinders_cross.py")
