# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B05_boolean.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_merge_002_block_plus_cyl',
 'category': '05_boolean',
 'commands': ['Combine.Merge(target, tool)', 'MergeBodies.Execute'],
 'expect': {'bodies': 1, 'volume_mm3': 20021.238597},
 'feature': 'bool_merge',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\05_boolean',
 'params': {'a': 'block 40x40x10', 'b': 'cyl r8 h30 at center'},
 'priority': 'P0',
 'title': 'Combine - merge (union): 002_block_plus_cyl'}


def build(ctx):
    a = block((0, 0, 0), (40, 40, 10), "Merge_Base")
    b = cylinder((20, 20, 0), (20, 20, 30), 8, "Merge_Boss")
    first_ok(ctx, "merge", [
        lambda: Combine.Merge(sel(a, b)),
        lambda: Combine.Merge(sel(a), sel(b))])
    name_bodies(["Base_With_Boss"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\05_boolean\05_boolean_merge_002_block_plus_cyl.py")
