# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_move_scale_001_uniform_2x',
 'category': '06_move_pattern',
 'commands': ['Scale.Execute(sel, origin, scale)', 'Scale.Execute(sel, frame, Vector scale)'],
 'expect': {'bodies': 1, 'volume_mm3': 8000.0},
 'feature': 'mp_scale',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'s': 2},
 'priority': 'P2',
 'title': 'Scale body (uniform / non-uniform): 001_uniform_2x'}


def build(ctx):
    b = block((0, 0, 0), (10, 10, 10), "Scaled_2x")
    Scale.Execute(sel(b), P(0, 0, 0), 2.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_move_scale_001_uniform_2x.py")
