# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_move_mirror_001_block_about_yz',
 'category': '06_move_pattern',
 'commands': ['Mirror.Execute(sel, mirrorPlane, MirrorOptions)', 'DatumPlaneCreator.Create'],
 'expect': {'bodies': 2, 'volume_mm3': 2000.0},
 'feature': 'mp_mirror',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'plane': 'YZ'},
 'priority': 'P0',
 'title': 'Mirror body (and mirror relationship): 001_block_about_yz'}


def build(ctx):
    b = block((5, 0, 0), (15, 10, 10), "Mirror_Source")
    DatumPlaneCreator.Create(P(0, 0, 0), D(1, 0, 0))
    dp = list(GetRootPart().DatumPlanes)[-1]
    _safe(lambda: set_name(dp, "Mirror_Plane_YZ"))
    Mirror.Execute(sel(b), sel(dp), MirrorOptions())
    bs = sorted(bodies_now(), key=lambda x: bbox_center(x)[0], reverse=True)
    name_bodies(["Mirror_Source", "Mirror_Copy"], bs)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_move_mirror_001_block_about_yz.py")
