# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_move_translate_002_copy_y30',
 'category': '06_move_pattern',
 'commands': ['Move.Translate(sel, Direction, distance, MoveOptions)'],
 'expect': {'bodies': 2, 'volume_mm3': 2000.0},
 'feature': 'mp_translate',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'copy': True, 'd_mm': 30, 'dir': 'Y'},
 'priority': 'P1',
 'title': 'Move - translate: 002_copy_y30'}


def build(ctx):
    b = block((0, 0, 0), (10, 10, 10), "Block_Original")
    o = MoveOptions()
    o.Copy = True
    Move.Translate(sel(b), D(0, 1, 0), MM(30), o)
    bs = sorted(bodies_now(), key=lambda x: bbox_center(x)[1])
    name_bodies(["Block_Original", "Block_Copy_Y30"], bs)
    ctx.data["centres_mm"] = [bbox_center(x) for x in bs]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_move_translate_002_copy_y30.py")
