# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_move_translate_001_block_x25',
 'category': '06_move_pattern',
 'commands': ['Move.Translate(sel, Direction, distance, MoveOptions)'],
 'expect': {'bodies': 1, 'volume_mm3': 1000.0},
 'feature': 'mp_translate',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'d_mm': 25, 'dir': 'X'},
 'priority': 'P1',
 'title': 'Move - translate: 001_block_x25'}


def build(ctx):
    b = block((0, 0, 0), (10, 10, 10), "Moved_Block")
    Move.Translate(sel(b), D(1, 0, 0), MM(25), MoveOptions())
    ctx.data["bbox_after_mm"] = bbox(body_named("Moved_Block"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_move_translate_001_block_x25.py")
