# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_move_mirror_002_merge_halves',
 'category': '06_move_pattern',
 'commands': ['Mirror.Execute(sel, mirrorPlane, MirrorOptions)', 'DatumPlaneCreator.Create'],
 'expect': {'bodies': 1, 'volume_mm3': 4000.0},
 'feature': 'mp_mirror',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'merge': True},
 'priority': 'P0',
 'title': 'Mirror body (and mirror relationship): 002_merge_halves'}


def build(ctx):
    b = block((0, 0, 0), (10, 20, 10), "Mirror_Half")
    f = face_extreme(b, (1, 0, 0), -1)
    o = MirrorOptions()
    o.MergeObjects = True
    Mirror.Execute(sel(b), sel(f), o)
    name_bodies(["Mirror_Merged"], [largest()])
    ctx.data["bbox_mm"] = bbox(largest())

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_move_mirror_002_merge_halves.py")
