# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_move_rotate_001_block_z45',
 'category': '06_move_pattern',
 'commands': ['Move.Rotate(sel, Line axis, angle, MoveOptions)'],
 'expect': {'bodies': 1, 'volume_mm3': 1000.0},
 'feature': 'mp_rotate',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'axis': 'Z', 'deg': 45},
 'priority': 'P1',
 'title': 'Move - rotate: 001_block_z45'}


def build(ctx):
    b = block((0, 0, 0), (20, 10, 5), "Rotated_Block")
    Move.Rotate(sel(b), axis_line((0, 0, 0), (0, 0, 1)), DEG(45), MoveOptions())
    ctx.data["bbox_after_mm"] = bbox(body_named("Rotated_Block"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_move_rotate_001_block_z45.py")
