# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_move_rotate_002_cyl_x90_copy',
 'category': '06_move_pattern',
 'commands': ['Move.Rotate(sel, Line axis, angle, MoveOptions)'],
 'expect': {'bodies': 2},
 'feature': 'mp_rotate',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'axis': 'X', 'copy': True, 'deg': 90},
 'priority': 'P1',
 'title': 'Move - rotate: 002_cyl_x90_copy'}


def build(ctx):
    b = cylinder((0, 0, 0), (0, 0, 30), 5, "Cyl_Original")
    o = MoveOptions()
    o.Copy = True
    Move.Rotate(sel(b), axis_line((0, 0, 0), (1, 0, 0)), DEG(90), o)
    bs = sorted(bodies_now(), key=lambda x: bbox_center(x)[2], reverse=True)
    name_bodies(["Cyl_Original", "Cyl_Copy_RotX90"], bs)
    ctx.data["bboxes_mm"] = [bbox(x) for x in bs]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_move_rotate_002_cyl_x90_copy.py")
