# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R1_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_pattern_linear_002_hole_2d_3x4',
 'category': '06_move_pattern',
 'commands': ['Pattern.CreateLinear(sel, LinearPatternData)', 'Pattern.ModifyLinear'],
 'expect': {'bodies': 1},
 'feature': 'mp_pattern_linear',
 'inventory_expect': None,
 'notes': 'fix R1: plate 80x80x5, seed hole r2 at (34,40) so the 3x4 pattern stays on the plate whichever Y '
          'sign is inferred',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'count': [3, 4], 'member': 'through hole in plate', 'pitch_mm': [12, 10]},
 'priority': 'P0',
 'title': 'Linear pattern: 002_hole_2d_3x4'}


def build(ctx):
    plate = block((0, 0, 0), (80, 80, 5), "Plate_Holes")
    subtract(ctx, plate, cylinder((34, 40, -1), (34, 40, 6), 2, "Hole_Cutter"))
    p = largest()
    set_name(p, "Plate_Holes")
    hole = faces(p, "Cylinder")[0]
    d = LinearPatternData()
    setp(ctx, d, [("PatternDimension", PatternDimensionType.Two), ("LinearDirection", sel(edge_nearest(p, (40, 0, 0), "Line"))),
                  ("CountX", 3), ("PitchX", MM(12)), ("CountY", 4), ("PitchY", MM(10))], "linear")
    r = Pattern.CreateLinear(sel(hole), d, None)
    ctx.data["pattern_success"] = _safe(lambda: r.Success)
    ctx.data["hole_centres_mm"] = sorted([bbox_center(f)[:2] for f in faces(largest(), "Cylinder")])
    intent("hole_faces", len(faces(largest(), "Cylinder")), 12)
    intent("volume_mm3", round(total_volume(), 2), round(32000 - 12 * 3.14159265 * 4 * 5, 2), 0.5)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_pattern_linear_002_hole_2d_3x4.py")
