# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_pattern_circular_001_holes_6_360',
 'category': '06_move_pattern',
 'commands': ['Pattern.CreateCircular(sel, CircularPatternData)'],
 'expect': {'bodies': 1},
 'feature': 'mp_pattern_circular',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'angle_deg': 360, 'count': 6, 'member': 'hole r3 on disk r40'},
 'priority': 'P0',
 'title': 'Circular pattern: 001_holes_6_360'}


def build(ctx):
    disk = cylinder((0, 0, 0), (0, 0, 5), 40, "Disk_Holes")
    c = cylinder((25, 0, -1), (25, 0, 6), 3, "Hole_Cutter")
    subtract(ctx, disk, c)
    p = largest()
    set_name(p, "Disk_Holes")
    hole = [f for f in faces(p, "Cylinder") if abs(_dist(bbox_center(f), (25, 0, 2.5))) < 5][0]
    d = CircularPatternData()
    outer = max(faces(p, "Cylinder"), key=lambda f: bbox(f)[1][0] - bbox(f)[0][0])
    setp(ctx, d, [("PatternDimension", PatternDimensionType.One), ("CircularAxis", sel(outer)),
                  ("CircularCount", 6), ("CircularAngle", DEG(360))], "circular")
    r = Pattern.CreateCircular(sel(hole), d, None)
    ctx.data["pattern_success"] = _safe(lambda: r.Success)
    ctx.data["cyl_faces"] = len(faces(largest(), "Cylinder"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_pattern_circular_001_holes_6_360.py")
