# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_pattern_fill_001_holes_in_plate',
 'category': '06_move_pattern',
 'commands': ['Pattern.CreateFill(sel, FillPatternData)'],
 'expect': {'bodies': 1},
 'feature': 'mp_pattern_fill',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'member': 'hole r2', 'region': 'plate face 80x60'},
 'priority': 'P2',
 'title': 'Fill pattern: 001_holes_in_plate'}


def build(ctx):
    plate = block((0, 0, 0), (80, 60, 5), "Plate_Fill")
    c = cylinder((5, 5, -1), (5, 5, 6), 2, "Hole_Cutter")
    subtract(ctx, plate, c)
    p = largest()
    set_name(p, "Plate_Fill")
    hole = faces(p, "Cylinder")[0]
    region = top_face(p)
    d = FillPatternData()
    setp(ctx, d, [("FillPatternType", FillPatternType.Grid), ("XSpacing", MM(10)), ("YSpacing", MM(10)),
                  ("Margin", MM(3)), ("LinearDirection", sel(edge_nearest(p, (40, 0, 5), "Line")))], "fill")
    first_ok(ctx, "fill", [
        lambda: Pattern.CreateFill(sel(hole, region), d, None),
        lambda: Pattern.CreateFill(sel(hole), d, None)])
    ctx.data["hole_faces"] = len(faces(largest(), "Cylinder"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_pattern_fill_001_holes_in_plate.py")
