# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_pattern_linear_003_body_copy_3',
 'category': '06_move_pattern',
 'commands': ['Pattern.CreateLinear(sel, LinearPatternData)', 'Pattern.ModifyLinear'],
 'expect': {'bodies': 3},
 'feature': 'mp_pattern_linear',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'count': 3, 'pitch_mm': 25},
 'priority': 'P0',
 'title': 'Linear pattern: 003_body_copy_3'}


def build(ctx):
    b = block((0, 0, 0), (10, 10, 10), "Pattern_Block")
    d = LinearPatternData()
    setp(ctx, d, [("PatternDimension", PatternDimensionType.One), ("LinearDirection", sel(edge_nearest(b, (5, 0, 0), "Line"))),
                  ("CountX", 3), ("PitchX", MM(25))], "linear")
    r = Pattern.CreateLinear(sel(b), d, None)
    ctx.data["pattern_success"] = _safe(lambda: r.Success)
    name_bodies(["Pattern_Block"], sorted(bodies_now(), key=lambda x: bbox_center(x)[0]))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_pattern_linear_003_body_copy_3.py")
