# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_pattern_linear_001_cyl_1d_5x10',
 'category': '06_move_pattern',
 'commands': ['Pattern.CreateLinear(sel, LinearPatternData)', 'Pattern.ModifyLinear'],
 'expect': {'bodies': 5},
 'feature': 'mp_pattern_linear',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'count': 5, 'pitch_mm': 10},
 'priority': 'P0',
 'title': 'Linear pattern: 001_cyl_1d_5x10'}


def build(ctx):
    b = cylinder((0, 0, 0), (0, 0, 5), 2, "Pattern_Pin")
    dirc = dcurve(seg((0, -5, 0), (10, -5, 0)), "Pattern_Direction_X")
    d = LinearPatternData()
    setp(ctx, d, [("PatternDimension", PatternDimensionType.One), ("LinearDirection", sel(dirc)),
                  ("CountX", 5), ("PitchX", MM(10))], "linear")
    r = Pattern.CreateLinear(sel(b), d, None)
    ctx.data["pattern_success"] = _safe(lambda: r.Success)
    name_bodies(["Pattern_Pin"], sorted(bodies_now(), key=lambda x: bbox_center(x)[0]))
    ctx.data["pin_centres_mm"] = [bbox_center(x) for x in bodies_now()]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_pattern_linear_001_cyl_1d_5x10.py")
