# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B06_move_pattern.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '06_pattern_circular_002_bodies_4_180',
 'category': '06_move_pattern',
 'commands': ['Pattern.CreateCircular(sel, CircularPatternData)'],
 'expect': {'bodies': 4},
 'feature': 'mp_pattern_circular',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\06_move_pattern',
 'params': {'angle_deg': 180, 'count': 4},
 'priority': 'P0',
 'title': 'Circular pattern: 002_bodies_4_180'}


def build(ctx):
    b = block((20, -2, 0), (26, 2, 4), "Circ_Block")
    ax = dcurve(seg((0, 0, 0), (0, 0, 10)), "Pattern_Axis_Z")
    d = CircularPatternData()
    setp(ctx, d, [("PatternDimension", PatternDimensionType.One), ("CircularAxis", sel(ax)),
                  ("CircularCount", 4), ("CircularAngle", DEG(180))], "circular")
    r = Pattern.CreateCircular(sel(b), d, None)
    ctx.data["pattern_success"] = _safe(lambda: r.Success)
    name_bodies(["Circ_Block"])
    ctx.data["block_centres_mm"] = [bbox_center(x) for x in bodies_now()]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\06_move_pattern\06_pattern_circular_002_bodies_4_180.py")
