# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_cone_001_r10_h20',
 'category': '01_primitives',
 'commands': ['PlanarBody.Create (triangle in XZ)', 'RevolveFaces.Execute(360deg about Z)'],
 'expect': {'bodies': 1, 'volume_mm3': 2094.395102},
 'feature': 'prim_cone_revolve',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'h_mm': 20, 'r_base_mm': 10},
 'priority': 'P0',
 'title': 'Cone / frustum (revolve of triangle/trapezoid): 001_r10_h20'}


def build(ctx):
    s = planar(poly_curves([(0, 0, 0), (10, 0, 0), (0, 0, 20)]), plane_xz(), "Cone_Profile")
    revolve(face0(s), (0, 0, 0), (0, 0, 1), 360)
    name_bodies(["Cone"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_cone_001_r10_h20.py")
