# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_block_003_thin_100x100x0p5',
 'category': '01_primitives',
 'commands': ['BlockBody.Create(Point,Point,ExtrudeType)'],
 'expect': {'bodies': 1, 'faces': 6, 'volume_mm3': 5000.0},
 'feature': 'prim_block',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'p0_mm': [0, 0, 0], 'p1_mm': [100, 100, 0.5]},
 'priority': 'P0',
 'title': 'Block: 003_thin_100x100x0p5'}


def build(ctx):
    block((0, 0, 0), (100, 100, 0.5), "Thin_Plate")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_block_003_thin_100x100x0p5.py")
