# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_sphere_001_r10',
 'category': '01_primitives',
 'commands': ['SphereBody.Create(center,endPoint,ExtrudeType)'],
 'expect': {'bodies': 1, 'faces': 1, 'volume_mm3': 4188.790205},
 'feature': 'prim_sphere',
 'inventory_expect': {'faces': 1},
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'c_mm': [0, 0, 0], 'r_mm': 10},
 'priority': 'P0',
 'title': 'Sphere: 001_r10'}


def build(ctx):
    sphere((0, 0, 0), 10, "Sphere_R10")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_sphere_001_r10.py")
