# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_sphere_002_r3_offcenter',
 'category': '01_primitives',
 'commands': ['SphereBody.Create(center,endPoint,ExtrudeType)'],
 'expect': {'bodies': 1, 'faces': 1, 'volume_mm3': 113.097336},
 'feature': 'prim_sphere',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'c_mm': [5, -7, 2], 'r_mm': 3},
 'priority': 'P0',
 'title': 'Sphere: 002_r3_offcenter'}


def build(ctx):
    sphere((5, -7, 2), 3, "Sphere_R3_Off")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_sphere_002_r3_offcenter.py")
