# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_planar_002_circle_r15',
 'category': '01_primitives',
 'commands': ['PlanarBody.Create(Plane, curves, parent, name)'],
 'expect': {'area_mm2': 706.858347, 'bodies': 1, 'faces': 1},
 'feature': 'prim_planar_body',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'plane': 'XY', 'r_mm': 15},
 'priority': 'P1',
 'title': 'Planar (sheet) body from curves: 002_circle_r15'}


def build(ctx):
    sheet_circle((0, 0, 0), 15, "Planar_Circle")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_planar_002_circle_r15.py")
