# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_block_001_10x20x30',
 'category': '01_primitives',
 'commands': ['BlockBody.Create(Point,Point,ExtrudeType)'],
 'expect': {'bodies': 1, 'edges': 12, 'faces': 6, 'vertices': 8, 'volume_mm3': 6000.0},
 'feature': 'prim_block',
 'inventory_expect': {'edges': 12, 'faces': 6, 'volume_mm3': 6000},
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'p0_mm': [0, 0, 0], 'p1_mm': [10, 20, 30]},
 'priority': 'P0',
 'title': 'Block: 001_10x20x30'}


def build(ctx):
    block((0, 0, 0), (10, 20, 30), "Block_10x20x30")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_block_001_10x20x30.py")
