# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_planar_001_rect_40x20',
 'category': '01_primitives',
 'commands': ['PlanarBody.Create(Plane, curves, parent, name)'],
 'expect': {'area_mm2': 800.0, 'bodies': 1, 'faces': 1},
 'feature': 'prim_planar_body',
 'inventory_expect': {'faces': 1, 'sheet': True},
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'plane': 'XY', 'rect_mm': [40, 20]},
 'priority': 'P1',
 'title': 'Planar (sheet) body from curves: 001_rect_40x20'}


def build(ctx):
    sheet_rect(0, 0, 40, 20, 0, "Planar_Rect")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_planar_001_rect_40x20.py")
