# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_cone_002_frustum_r10_r5_h15',
 'category': '01_primitives',
 'commands': ['PlanarBody.Create (trapezoid in XZ)', 'RevolveFaces.Execute(360deg about Z)'],
 'expect': {'bodies': 1, 'volume_mm3': 2748.893572},
 'feature': 'prim_cone_revolve',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'h_mm': 15, 'r1_mm': 10, 'r2_mm': 5},
 'priority': 'P0',
 'title': 'Cone / frustum (revolve of triangle/trapezoid): 002_frustum_r10_r5_h15'}


def build(ctx):
    s = planar(poly_curves([(0, 0, 0), (10, 0, 0), (5, 0, 15), (0, 0, 15)]), plane_xz(), "Frustum_Profile")
    revolve(face0(s), (0, 0, 0), (0, 0, 1), 360)
    name_bodies(["Frustum"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_cone_002_frustum_r10_r5_h15.py")
