# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_block_002_offset_neg',
 'category': '01_primitives',
 'commands': ['BlockBody.Create(Point,Point,ExtrudeType)'],
 'expect': {'bodies': 1, 'faces': 6, 'volume_mm3': 1500.0},
 'feature': 'prim_block',
 'inventory_expect': {'volume_mm3': 1500},
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'p0_mm': [-15, -5, -2.5], 'p1_mm': [15, 5, 2.5]},
 'priority': 'P0',
 'title': 'Block: 002_offset_neg'}


def build(ctx):
    block((-15, -5, -2.5), (15, 5, 2.5), "Block_Offset_Neg")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_block_002_offset_neg.py")
