# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_tube_001_line_r2_l50',
 'category': '01_primitives',
 'commands': ['TubeBody.Create(ISelection curve, radius, ExtrudeType)'],
 'expect': {'bodies': 1},
 'feature': 'prim_tube',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'path': 'line 50mm', 'r_mm': 2},
 'priority': 'P1',
 'title': 'Tube around curve: 001_line_r2_l50'}


def build(ctx):
    c = dcurve(seg((0, 0, 0), (50, 0, 0)), "Tube_Path_Line")
    r = TubeBody.Create(sel(c), MM(2), ExtrudeType.ForceIndependent)

    name_bodies(["Tube_Line"])
    ctx.data["tube_volume_mm3"] = vol(largest())

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_tube_001_line_r2_l50.py")
