# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_torus_001_R20_r5',
 'category': '01_primitives',
 'commands': ['CircularSurface.Create', 'RevolveFaces.Execute(360deg about Z)'],
 'expect': {'bodies': 1, 'volume_mm3': 9869.604401},
 'feature': 'prim_torus_revolve',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'major_r_mm': 20, 'minor_r_mm': 5},
 'priority': 'P0',
 'title': 'Torus (revolve of circle): 001_R20_r5'}


def build(ctx):
    r = CircularSurface.Create(MM(5), D(0, 1, 0), P(20, 0, 0))
    revolve(face0(r.CreatedBody), (0, 0, 0), (0, 0, 1), 360)
    name_bodies(["Torus"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_torus_001_R20_r5.py")
