# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_tube_003_spline_r1',
 'category': '01_primitives',
 'commands': ['TubeBody.Create(ISelection curve, radius, ExtrudeType)'],
 'expect': {'bodies': 1},
 'feature': 'prim_tube',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'path': '3D spline 4pts', 'r_mm': 1},
 'priority': 'P1',
 'title': 'Tube around curve: 003_spline_r1'}


def build(ctx):
    c = dcurve(spline_curve([(0, 0, 0), (10, 5, 5), (20, 0, 10), (30, 5, 15)]), "Tube_Path_Spline")
    TubeBody.Create(sel(c), MM(1), ExtrudeType.ForceIndependent)
    name_bodies(["Tube_Spline"])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_tube_003_spline_r1.py")
