# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_cylinder_001_r10_h20_z',
 'category': '01_primitives',
 'commands': ['CylinderBody.Create(center,start,end,ExtrudeType)'],
 'expect': {'bodies': 1, 'faces': 3, 'volume_mm3': 6283.185307},
 'feature': 'prim_cylinder',
 'inventory_expect': {'edges': 3, 'faces': 3},
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'axis': 'Z', 'h_mm': 20, 'r_mm': 10},
 'priority': 'P0',
 'title': 'Cylinder: 001_r10_h20_z'}


def build(ctx):
    cylinder((0, 0, 0), (0, 0, 20), 10, "Cyl_Z")
    ctx.data["cylinder_arg_order"] = CYL_ORDER[0]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_cylinder_001_r10_h20_z.py")
