# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_torus_002_partial_180deg',
 'category': '01_primitives',
 'commands': ['CircularSurface.Create', 'RevolveFaces.Execute(180deg about Z)'],
 'expect': {'bodies': 1, 'volume_mm3': 4934.802201},
 'feature': 'prim_torus_revolve',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'angle_deg': 180, 'major_r_mm': 20, 'minor_r_mm': 5},
 'priority': 'P0',
 'title': 'Torus (revolve of circle): 002_partial_180deg'}


def build(ctx):
    r = CircularSurface.Create(MM(5), D(0, 1, 0), P(20, 0, 0))
    revolve(face0(r.CreatedBody), (0, 0, 0), (0, 0, 1), 180)
    name_bodies(["Torus_Half"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_torus_002_partial_180deg.py")
