# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_cylinder_002_r5_h50_x',
 'category': '01_primitives',
 'commands': ['CylinderBody.Create(center,start,end,ExtrudeType)'],
 'expect': {'bodies': 1, 'faces': 3, 'volume_mm3': 3926.990817},
 'feature': 'prim_cylinder',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'axis': 'X', 'h_mm': 50, 'r_mm': 5},
 'priority': 'P0',
 'title': 'Cylinder: 002_r5_h50_x'}


def build(ctx):
    cylinder((0, 0, 0), (50, 0, 0), 5, "Cyl_X")
    ctx.data["cylinder_arg_order"] = CYL_ORDER[0]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_cylinder_002_r5_h50_x.py")
