# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B01_primitives.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '01_primitives_cylinder_003_r2_h1_oblique',
 'category': '01_primitives',
 'commands': ['CylinderBody.Create(center,start,end,ExtrudeType)'],
 'expect': {'bodies': 1, 'faces': 3, 'volume_mm3': 12.566371},
 'feature': 'prim_cylinder',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\01_primitives',
 'params': {'axis': [1, 1, 1], 'h_mm': 1, 'r_mm': 2},
 'priority': 'P0',
 'title': 'Cylinder: 003_r2_h1_oblique'}


def build(ctx):
    s = 3 ** -0.5
    cylinder((0, 0, 0), (s, s, s), 2, "Cyl_Oblique")
    ctx.data["cylinder_arg_order"] = CYL_ORDER[0]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\01_primitives\01_primitives_cylinder_003_r2_h1_oblique.py")
