# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_draft_024_molded_part',
 'category': '20_combo',
 'commands': ['so_draft', 'edge_round', 'so_shell'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'steps: block; draft 4 sides; round; shell | headless_feasibility: needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Molded box: extrude, draft 3deg, round r2, shell t1.5'}


def build(ctx):
    def drafted(ctx, name, kind="block"):
        """Draft the side faces so the part narrows towards the top (neutral plane = bottom face). Tries angle sign /
        draft side combinations on a fresh body and keeps the first whose volume shrinks and whose bbox stays inside."""
        import math
        forms = [("This", -5), ("This", 5), ("Other", 5), ("Other", -5), ("NoSplit", -5), ("NoSplit", 5)]
        ang0 = 5 if kind == "block" else 3
        v_full = 24000.0 if kind == "block" else math.pi * 100 * 20
        lim = (0.0, 40.0) if kind == "block" else (-10.0, 10.0)
        log = []
        for sd, sgn in forms:
            if bodies_now():
                Delete.Execute(sel(bodies_now()))
            if kind == "block":
                b = block((0, 0, 0), (40, 30, 20), name)
                sides = [face_extreme(b, a, s) for a in [(1, 0, 0), (0, 1, 0)] for s in (1, -1)]
            else:
                b = cylinder((0, 0, 0), (0, 0, 20), 10, name)
                sides = faces(b, "Cylinder")
            ang = ang0 if sgn > 0 else -ang0
            try:
                DraftFaces.Execute(sel(sides), sel(bottom_face(b)), getattr(DraftSide, sd), DEG(ang), getattr(ExtrudeType, "None"), DraftOptions())
            except Exception as e:
                log.append([sd, ang, "error: " + unicode(e)[:120]])
                continue
            b = largest()
            v, bb = vol(b), bbox(b)
            log.append([sd, ang, v, bb])
            if v is not None and v < v_full - 1.0 and bb[0][0] >= lim[0] - 1e-3 and bb[1][0] <= lim[1] + 1e-3:
                ctx.data["draft_form"] = [sd, ang]
                ctx.data["draft_log"] = log
                return b
        ctx.data["draft_log"] = log
        raise Exception("no draft form narrowed the part inward: %s" % log)

    b = drafted(ctx, "Molded_Part")
    ConstantRound.Execute(sel(edges_at_z(largest(), 20)), MM(2), ConstantRoundOptions())
    Shell.RemoveFaces(sel(bottom_face(largest())), MM(-1.5))
    name_bodies(["Molded_Part"], [largest()])
    intent_range("volume_mm3", total_volume(), 2000, 9000)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_draft_024_molded_part.py")
