# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_sweep_009_pipe_bend',
 'category': '20_combo',
 'commands': ['pull_sweep', 'so_shell'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: path chain; sweep circle r10; shell remove 2 end faces t1 | headless_feasibility: needs '
          'selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Bent pipe: sweep circle along line-arc-line path, shell both ends'}


def build(ctx):
    p1 = dcurve(seg((0, 0, 0), (0, 0, 30)), "Path_L1")
    p2 = dcurve(arc_curve((40, 0, 30), 40, -90, 0, (0, 1, 0), (0, 0, 1)), "Path_Arc")
    p3 = dcurve(seg((40, 0, 70), (80, 0, 70)), "Path_L2")
    ctx.data["arc_ends"] = [edge_mid(p2)]
    r = CircularSurface.Create(MM(10), D(0, 0, 1), P(0, 0, 0))
    Sweep.Execute(sel(face0(r.CreatedBody)), sel(p1, p2, p3), SweepCommandOptions())
    delete_sheets()
    b = largest()
    e1 = face_extreme(b, (0, 0, 1), -1)
    e2 = face_extreme(b, (1, 0, 0), 1)
    Shell.RemoveFaces(sel(e1, e2), MM(-1))
    name_bodies(["Pipe_Bend"], [largest()])
    L = 30 + 40 * 3.14159265 / 2 + 40
    intent("volume_mm3", round(total_volume(), 1), round(L * 3.14159265 * (100 - 81), 1), 80.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_sweep_009_pipe_bend.py")
