# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_loft_008_loft_shell',
 'category': '20_combo',
 'commands': ['pull_loft', 'so_shell'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: 3 profiles; loft; shell | headless_feasibility: needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Bottle: loft rect->circle->circle, shell open top 1mm'}


def build(ctx):
    fs = [face0(sheet_circle((0, 0, z), r, "Loft_C%d" % i)) for i, (z, r) in enumerate([(0, 10), (20, 6), (40, 12)])]
    Loft.Create(sel(fs), None, LoftOptions())
    delete_sheets()
    b = largest()
    v0 = vol(b)
    Shell.RemoveFaces(sel(top_face(b)), MM(-1))
    name_bodies(["Loft_Shell"], [largest()])
    ctx.data["loft_volume_mm3"] = v0
    intent_range("shell_fraction", round(vol(largest()) / v0, 3), 0.05, 0.4)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_loft_008_loft_shell.py")
