# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R3_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_wrap_026_cylinder_wrap_text_pull',
 'category': '20_combo',
 'commands': ['sc_project_wrap', 'pull_face_offset'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'fix R3: Wrap.Create(target body, sheet face/edges) checked for an imprint, then the imprinted '
          'patch pulled out 1 mm | steps: cyl; sketch rect; Wrap; pull imprint | headless_feasibility: needs '
          'selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P2',
 'title': 'Cylinder with wrapped rectangle imprint pulled 1mm'}


def build(ctx):
    def wrap_rect(ctx, cy, sh, strict=True):
        o = WrapOptions()
        ctx.data["wrap_opts_members"] = [n for n in dir(o) if not n.startswith("_")]
        n_c0 = len(curves_now())
        def cyl_faces():
            return max(face_count(x) for x in all_bodies() if not is_sheet(x))
        def chk():
            ctx.data["after_wrap"] = {"cyl_faces": cyl_faces(), "curves": len(curves_now()), "bodies": [[unicode(x.Name), is_sheet(x), face_count(x)] for x in all_bodies()]}
            if cyl_faces() <= 3 and (strict or len(curves_now()) <= n_c0):
                raise Exception("no imprint (faces=%d)" % cyl_faces())
        def w1():
            Wrap.Create(sel(cy), sel(face0(sh)), o)
            chk()
        def w2():
            Wrap.Create(sel(cy), sel(list(sh.Edges)), o)
            chk()
        def w3():
            Wrap.Create(sel(cy), sel(sh), o)
            chk()
        first_ok(ctx, "wrap", [w1, w2, w3])
        return cyl_faces()

    cy = cylinder((0, 0, 0), (0, 0, 40), 10, "Wrap_Cyl")
    sh = planar(poly_curves([(10, -5, 15), (10, 5, 15), (10, 5, 25), (10, -5, 25)]), plane_at((10, 0, 20), (1, 0, 0)), "Wrap_Rect")
    nf = wrap_rect(ctx, cy, sh, strict=True)
    ctx.data["faces_after_wrap"] = nf
    delete_sheets()
    cy = largest()
    small = min([f for f in cy.Faces if gtype(f) != "Plane"], key=lambda f: shape_of(f).Area)
    first_ok(ctx, "pull", [lambda: ExtrudeFaces.Execute(sel(small), MM(1), ExtrudeFaceOptions())])
    name_bodies(["Wrap_Cyl"], [largest()])
    intent_range("volume_gain_mm3", total_volume() - 3.14159265 * 100 * 40, 50, 150)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_wrap_026_cylinder_wrap_text_pull.py")
