# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_split_011_split_multi_body_names_colors',
 'category': '20_combo',
 'commands': ['bool_split_body', 'doc_rename', 'doc_colors'],
 'expect': {'bodies': 3, 'volume_mm3': 36000.0},
 'feature': 'combo',
 'inventory_expect': {'bodies': 3},
 'notes': 'steps: block; split z=10; split z=20; rename Part_A..C; colors | headless_feasibility: yes',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Block split into 3 bodies by 2 planes, each renamed + colored'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 30), "Split_Stack")
    SplitBody.ByCutter(sel(b), plane_xy(10))
    up = [x for x in bodies_now() if bbox(x)[0][2] > 5][0]
    SplitBody.ByCutter(sel(up), plane_xy(20))
    bs = sorted(bodies_now(), key=lambda x: bbox(x)[0][2])
    name_bodies(["Part_A", "Part_B", "Part_C"], bs)
    cols = [Color.FromArgb(255, 255, 0, 0), Color.FromArgb(255, 0, 180, 0), Color.FromArgb(255, 0, 0, 255)]
    for x, col in zip(bs, cols):
        ColorHelper.SetColor(sel(x), SetColorOptions(), col)
    intent("names", sorted([unicode(x.Name) for x in all_bodies()]), [u"Part_A", u"Part_B", u"Part_C"])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_split_011_split_multi_body_names_colors.py")
