# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_asm_016_nested_3levels_colors_layers',
 'category': '20_combo',
 'commands': ['asm_component', 'doc_layers', 'doc_colors'],
 'expect': {'components': 3},
 'feature': 'combo',
 'inventory_expect': {'components': 3},
 'notes': 'steps: root/sub/subsub comps; bodies in each; layers/colors | headless_feasibility: yes',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Nested assembly 3 levels, bodies colored + layered'}


def build(ctx):
    c1 = ComponentHelper.CreateAtRoot("Level_1")
    c2 = first_ok(ctx, "l2", [lambda: list(ComponentHelper.CreateAtComponent(c1, "Level_2").CreatedComponents)[0], lambda: list(c1.Components)[0]])
    c3 = first_ok(ctx, "l3", [lambda: list(ComponentHelper.CreateAtComponent(c2, "Level_3").CreatedComponents)[0], lambda: list(c2.Components)[0]])
    Layers.Create("L_level_1")
    Layers.Create("L_level_3")
    for i, c in enumerate([c1, c2, c3]):
        ComponentHelper.SetActive(c)
        b = block((30 * i, 0, 0), (30 * i + 20, 20, 10 * (i + 1)), "Level_%d_Body" % (i + 1))
        ColorHelper.SetColor(sel(b), SetColorOptions(), Color.FromArgb(255, 80 * i, 100, 255 - 80 * i))
        if i != 1:
            Layers.AssignLayer(sel(b), "L_level_%d" % (i + 1))
    ComponentHelper.SetRootActive()
    ctx.data["component_list"] = doc_stats()["component_list"]
    intent("bodies", len(all_bodies()), 3)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_asm_016_nested_3levels_colors_layers.py")
