# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_asm_017_mates_align_tangent',
 'category': '20_combo',
 'commands': ['asm_component', 'asm_conditions'],
 'expect': {'components': 2, 'mating_conditions': 2},
 'feature': 'combo',
 'inventory_expect': {'conditions': 2},
 'notes': 'steps: plate + pin comps; align axis; tangent faces | headless_feasibility: needs selection setup '
          '(raw API conditions, verify)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': '2-component assembly with align + tangent conditions'}


def build(ctx):
    plate = block((0, 0, 0), (60, 40, 10), "Plate_Body")
    subtract(ctx, plate, cylinder((30, 20, -5), (30, 20, 15), 4, "Hole_Cutter"))
    set_name(largest(), "Plate_Body")
    cylinder((100, 20, 5), (100, 20, 35), 4, "Pin_Body")
    ComponentHelper.CreateSeparateComponents(sel(bodies_now()))
    comps = list(GetRootPart().Components)
    cp = [c for c in comps if any(x.Name == "Plate_Body" for x in comp_bodies(c))][0]
    cq = [c for c in comps if any(x.Name == "Pin_Body" for x in comp_bodies(c))][0]
    pb = comp_bodies(cp)[0]
    pin = comp_bodies(cq)[0]
    raw("align", lambda: AlignCondition.Create(GetRootPart(), faces(pb, "Cylinder")[0], faces(pin, "Cylinder")[0]))
    raw("tangent", lambda: TangentCondition.Create(GetRootPart(), top_face(pb), bottom_face(pin)))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_asm_017_mates_align_tangent.py")
