# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_units_027_inch_doc_primitives',
 'category': '20_combo',
 'commands': ['doc_units', 'prim_block', 'prim_cylinder'],
 'expect': {'bodies': 2},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'steps: set units IN; block 1x2x3 in; cyl | headless_feasibility: unknown (units setter)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Inch document with block+cylinder (unit factor check)'}


def build(ctx):
    doc = DocumentHelper.GetActiveDocument()
    raw("units", lambda: setattr(doc.Units, "ActiveUnitsSystem", UnitsSystemType.Imperial))
    _safe(lambda: raw("iu", lambda: setattr(doc.Units, "ImperialUnits", rawt("ImperialUnits")(ImperialLengthUnit.Inches, enum_pick(rawt("ImperialMassUnit"), "Pounds", "PoundMass"), rawt("AngleUnit").Degrees))))
    block((0, 0, 0), (25.4, 50.8, 76.2), "Block_1x2x3in")
    cylinder((50.8, 25.4, 0), (50.8, 25.4, 25.4), 12.7, "Cyl_D1in_H1in")
    intent("units_system", unicode(doc.Units.ActiveUnitsSystem), u"Imperial")
    intent("volume_mm3", round(total_volume(), 1), round(25.4 ** 3 * (6 + 3.14159265 * 0.25), 1), 5.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_units_027_inch_doc_primitives.py")
