# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R2_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_asm_014_two_components',
 'category': '20_combo',
 'commands': ['asm_component', 'doc_rename'],
 'expect': {'bodies': 2, 'components': 2},
 'feature': 'combo',
 'inventory_expect': {'bodies': 2, 'components': 2},
 'notes': 'fix R2: component display name lives on the component template; name set with checked forms '
          '(ComponentHelper.SetName / RenameObject / Template.Name) and read back from Name or Template.Name '
          '| steps: block in comp Plate; cyl in comp Boss; SetName | headless_feasibility: yes',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': '2-component assembly: plate + boss in separate components, renamed'}


def build(ctx):
    cp = component("Plate", lambda: block((0, 0, 0), (60, 40, 10), "Plate_Body"))
    cb = component("Boss", lambda: cylinder((30, 20, 10), (30, 20, 30), 8, "Boss_Body"))
    def cname(c):
        return [unicode(_safe(lambda: c.Name, "")), unicode(_safe(lambda: c.Template.Name, "")), unicode(_safe(lambda: master(c).Template.Name, ""))]
    def chk():
        if u"Base_Plate" not in cname(cp):
            raise Exception("name not visible: %s" % cname(cp))
    def s1():
        ComponentHelper.SetName(cp, "Base_Plate")
        chk()
    def s2():
        RenameObject.Execute(sel(cp), "Base_Plate")
        chk()
    def s3():
        raw("template_name", lambda: setattr(master(cp).Template, "Name", "Base_Plate"))
        chk()
    ctx.data["names_before"] = [cname(x) for x in GetRootPart().Components]
    first_ok(ctx, "setname", [s1, s2, s3])
    ctx.data["component_names"] = [cname(x) for x in GetRootPart().Components]
    intent("has_Base_Plate", any(u"Base_Plate" in cname(x) for x in GetRootPart().Components), True)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_asm_014_two_components.py")
