# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_plate_003_linear_pattern_holes_round',
 'category': '20_combo',
 'commands': ['prim_block', 'pull_extrude_cut', 'mp_pattern_linear', 'edge_round'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: block; hole r2; linear pattern 3x4; round r1 outer edges | headless_feasibility: needs '
          'selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Plate 100x60x5 with 3x4 hole pattern and all-edge rounds'}


def build(ctx):
    plate = block((0, 0, 0), (80, 80, 5), "Plate_Holes")
    subtract(ctx, plate, cylinder((34, 40, -1), (34, 40, 6), 2, "Hole_Cutter"))
    p = largest()
    hole = faces(p, "Cylinder")[0]
    d = LinearPatternData()
    setp(ctx, d, [("PatternDimension", PatternDimensionType.Two), ("LinearDirection", sel(edge_nearest(p, (40, 0, 0), "Line"))),
                  ("CountX", 3), ("PitchX", MM(12)), ("CountY", 4), ("PitchY", MM(10))], "linear")
    Pattern.CreateLinear(sel(hole), d, None)
    p = largest()
    ctx.data["hole_faces"] = len(faces(p, "Cylinder"))
    vert = [e for e in edges(p, "Line") if abs(bbox(e)[1][2] - bbox(e)[0][2] - 5) < 1e-3]
    ConstantRound.Execute(sel(vert), MM(1), ConstantRoundOptions())
    name_bodies(["Plate_Holes"], [largest()])
    intent("hole_faces", ctx.data["hole_faces"], 12)
    intent("vertical_edges_rounded", len(vert), 4)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_plate_003_linear_pattern_holes_round.py")
