# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_flange_002_revolve_pattern_chamfer',
 'category': '20_combo',
 'commands': ['pull_revolve', 'pull_extrude_cut', 'mp_pattern_circular', 'edge_chamfer'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: revolve flange section; cut hole r5 at R40; circular pattern 6; chamfer 1mm | '
          'headless_feasibility: needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Pipe flange: revolve profile, circular pattern of 6 bolt holes, chamfer outer edge'}


def build(ctx):
    s = planar(poly_curves([(10, 0, 0), (50, 0, 0), (50, 0, 10), (20, 0, 10), (20, 0, 30), (10, 0, 30)]), plane_xz(), "Flange")
    revolve(face0(s), (0, 0, 0), (0, 0, 1), 360)
    delete_sheets()
    subtract(ctx, largest(), cylinder((40, 0, -1), (40, 0, 11), 5, "Hole_Cutter"))
    p = largest()
    hole = [f for f in faces(p, "Cylinder") if _dist(bbox_center(f), (40, 0, 5)) < 6][0]
    outer = max(faces(p, "Cylinder"), key=lambda f: bbox(f)[1][0] - bbox(f)[0][0])
    d = CircularPatternData()
    setp(ctx, d, [("PatternDimension", PatternDimensionType.One), ("CircularAxis", sel(outer)),
                  ("CircularCount", 6), ("CircularAngle", DEG(360))], "circular")
    Pattern.CreateCircular(sel(hole), d, None)
    p = largest()
    rim = max(edges_at_z(p, 10), key=lambda e: bbox(e)[1][0] - bbox(e)[0][0])
    Chamfer.Execute(sel(rim), MM(1))
    name_bodies(["Flange"], [largest()])
    intent("hole_faces", len([f for f in faces(largest(), "Cylinder") if abs(bbox(f)[1][0] - bbox(f)[0][0] - 10) < 0.01]), 6)
    intent_range("volume_mm3", total_volume(), 89250, 89480)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_flange_002_revolve_pattern_chamfer.py")
