# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_doc_012_layers_colors_named_selections',
 'category': '20_combo',
 'commands': ['doc_layers', 'doc_colors', 'doc_named_selection', 'doc_rename'],
 'expect': {'bodies': 3},
 'feature': 'combo',
 'inventory_expect': {'bodies': 3, 'layers': 3, 'named_selections': 3},
 'notes': 'steps: 3 primitives; 2 layers; face colors; NamedSelection x3 | headless_feasibility: yes',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Doc attributes: 3 bodies on 2 layers, face colors, 3 named selections (inlet/outlet/wall)'}


def build(ctx):
    a = block((0, 0, 0), (20, 20, 20), "Doc_Block")
    c = cylinder((40, 10, 0), (40, 10, 20), 8, "Doc_Cylinder")
    s = sphere((70, 10, 10), 10, "Doc_Sphere")
    Layers.Create("L_solids_A")
    Layers.Create("L_solids_B")
    Layers.AssignLayer(sel(a, c), "L_solids_A")
    Layers.AssignLayer(sel(s), "L_solids_B")
    ColorHelper.SetColor(sel(top_face(a)), SetColorOptions(), Color.FromArgb(255, 255, 128, 0))
    ColorHelper.SetColor(sel(faces(c, "Cylinder")), SetColorOptions(), Color.FromArgb(255, 0, 128, 255))
    for nm, obj in [("NS_Block_Top", [top_face(a)]), ("NS_Cyl_Side", faces(c, "Cylinder")), ("NS_Sphere", [s])]:
        r = NamedSelection.Create(sel(obj), Selection.Empty())
        NamedSelection.Rename(unicode(r.CreatedNamedSelection.Name), nm)
    intent("ns_count", len(doc_stats()["named_selections"]), 3)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_doc_012_layers_colors_named_selections.py")
