# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_beam_019_frame_with_profiles',
 'category': '20_combo',
 'commands': ['beam_profile', 'beam_create', 'sk_datum_curve'],
 'expect': {'beams': 6},
 'feature': 'combo',
 'inventory_expect': {'beams': 6},
 'notes': 'steps: 6 design curves; BeamProfile I & Rect; Beam.Create; orientation | headless_feasibility: '
          'needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Beam frame: rectangular frame of 4 lines + 2 diagonals, I profile + rect tube'}


def build(ctx):
    def nn(x):
        if x is None:
            raise Exception("None")
        return x
    def profile_part(ctx, r):
        ctx.data["profile_result_members"] = _safe(lambda: [n for n in dir(r) if not n.startswith("_")][:40])
        comps = list(GetRootPart().Components)
        return first_ok(ctx, "profile_part", [lambda: nn(_safe(lambda: r.CreatedProfile)), lambda: nn(comps[-1].Template),
                                              lambda: nn(master(comps[-1]).Template)])
    def make_beams(ctx, prof, curves):
        BM = rawt("Beam")
        out = []
        for c in curves:
            out.append(first_ok(ctx, "beam", [lambda: raw("beam", lambda: BM.Create(prof, master(c))),
                                              lambda: raw("beam", lambda: BM.Create(prof, c)),
                                              lambda: Beam.Create(sel(c), prof)]))
        return out

    hz = [((0, 0, 0), (1000, 0, 0)), ((1000, 0, 0), (1000, 500, 0)), ((1000, 500, 0), (0, 500, 0)), ((0, 500, 0), (0, 0, 0))]
    vt = [((0, 0, 0), (0, 0, 800)), ((1000, 0, 0), (1000, 0, 800))]
    ch = [dcurve(seg(p, q), "Frame_H_%d" % (i + 1)) for i, (p, q) in enumerate(hz)]
    cv = [dcurve(seg(p, q), "Frame_V_%d" % (i + 1)) for i, (p, q) in enumerate(vt)]
    pi = profile_part(ctx, BeamProfile.CreateI(MM(50), MM(100), MM(8), MM(5), "I_100x50"))
    make_beams(ctx, pi, ch)
    pr = profile_part(ctx, BeamProfile.CreateRectangular(MM(3), MM(60), MM(40), "Rect_Tube_60x40x3"))
    bv = make_beams(ctx, pr, cv)
    ctx.attempt("orientation", lambda: Beam.SetOrientation(sel(bv), DEG(30)))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_beam_019_frame_with_profiles.py")
