# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_shaft_006_revolve_chamfer_keyway',
 'category': '20_combo',
 'commands': ['pull_revolve', 'edge_chamfer', 'pull_extrude_cut'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: revolve stepped profile; chamfer both ends 1mm; keyway pocket 6x30 depth 3 | '
          'headless_feasibility: needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Stepped shaft: revolve 3 diameters, chamfer ends, keyway pocket'}


def build(ctx):
    s = planar(poly_curves([(0, 0, 0), (10, 0, 0), (10, 0, 40), (8, 0, 40), (8, 0, 70), (0, 0, 70)]), plane_xz(), "Shaft")
    revolve(face0(s), (0, 0, 0), (0, 0, 1), 360)
    delete_sheets()
    b = largest()
    ends = [max(edges_at_z(b, 0), key=lambda e: bbox(e)[1][0]), max(edges_at_z(b, 70), key=lambda e: bbox(e)[1][0])]
    Chamfer.Execute(sel(ends), MM(1))
    subtract(ctx, largest(), block((7, -3, 5), (11, 3, 35), "Keyway_Cutter"))
    name_bodies(["Shaft"], [largest()])
    v0 = 3.14159265 * (100 * 40 + 64 * 30)
    intent_range("volume_mm3", total_volume(), v0 - 700, v0 - 450)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_shaft_006_revolve_chamfer_keyway.py")
