# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_sm_018_sheetmetal_bracket',
 'category': '20_combo',
 'commands': ['sm_all'],
 'expect': {},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'steps: plate 100x50x2; convert to sheet metal; flange 90deg x2; unfold | headless_feasibility: '
          'GUI-only',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Sheet metal bracket: convert plate, 2 flanges, relief, unfold'}


def build(ctx):
    a = block((0, 0, 0), (100, 50, 2), "U_Bracket")
    w1 = block((0, 0, 2), (2, 50, 22), "Wall_1")
    w2 = block((98, 0, 2), (100, 50, 22), "Wall_2")
    Combine.Merge(sel(a, w1, w2))
    root = GetRootPart()
    raw("sheetmetal", lambda: master(root).ConvertToSheetMetal())
    b = largest()
    asp = master(root).SheetMetal
    LE = List[rawt("DesignEdge")]
    cre = [edge_nearest(b, (2, 25, 2)), edge_nearest(b, (98, 25, 2))]
    first_ok(ctx, "bends", [lambda: raw("bend", lambda: asp.CreateMissingBends(LE([master(e) for e in cre]), MM(1)))])
    ctx.data["faces_after_bends"] = face_count(largest())
    f = first_ok(ctx, "unfold", [lambda: raw("unfold", lambda: asp.Unfold(master(bottom_face(largest()))))])
    ctx.data["bboxes"] = [bbox(x) for x in all_bodies()]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_sm_018_sheetmetal_bracket.py")
