# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_mirror_010_half_model_mirror_merge',
 'category': '20_combo',
 'commands': ['mp_mirror', 'bool_merge'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: half bracket; mirror YZ merge | headless_feasibility: needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Half model mirrored about YZ and merged'}


def build(ctx):
    b = block((0, 0, 0), (30, 20, 5), "Bracket_Half")
    c = cylinder((20, 10, 5), (20, 10, 15), 4, "Boss")
    Combine.Merge(sel(b, c))
    b = largest()
    o = MirrorOptions()
    o.MergeObjects = True
    Mirror.Execute(sel(b), sel(face_extreme(b, (1, 0, 0), -1)), o)
    name_bodies(["Bracket_Full"], [largest()])
    intent("volume_mm3", round(total_volume(), 1), round(2 * (3000 + 3.14159265 * 16 * 10), 1), 1.0)
    intent("x_min_mm", round(bbox(largest())[0][0], 3), -30.0, 0.01)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_mirror_010_half_model_mirror_merge.py")
