# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_multi_029_many_components_8',
 'category': '20_combo',
 'commands': ['asm_component'],
 'expect': {'bodies': 8, 'components': 8},
 'feature': 'combo',
 'inventory_expect': {'bodies': 8, 'components': 8},
 'notes': 'steps: 8 comps x 1 body | headless_feasibility: yes',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': '8 components each with one body (IMPROVEMENT_PRIORITIES P0-1 id collision scenario)'}


def build(ctx):
    for i in range(8):
        component("Comp_%d" % (i + 1), lambda: block((30 * i, 0, 0), (30 * i + 20, 20, 10 + 2 * i), "Comp_%d_Body" % (i + 1)))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_multi_029_many_components_8.py")
