# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_housing_004_block_shell_round',
 'category': '20_combo',
 'commands': ['prim_block', 'edge_round', 'so_shell'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: block 80x60x40; round 4 vertical edges r8; shell remove top t2 | headless_feasibility: '
          'needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Housing: block, round vertical edges r8, shell open top t2'}


def build(ctx):
    b = block((0, 0, 0), (80, 60, 40), "Housing")
    vert = [e for e in edges(b, "Line") if abs(bbox(e)[1][2] - bbox(e)[0][2] - 40) < 1e-3]
    ConstantRound.Execute(sel(vert), MM(8), ConstantRoundOptions())
    b = largest()
    Shell.RemoveFaces(sel(top_face(b)), MM(-2))
    name_bodies(["Housing"], [largest()])
    intent("vertical_edges", len(vert), 4)
    intent("volume_mm3", round(total_volume(), 1), 29248.6, 60.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_housing_004_block_shell_round.py")
