# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_view_031_named_views_section',
 'category': '20_combo',
 'commands': ['doc_named_view', 'asm_component'],
 'expect': {'components': 2},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'steps: assembly from 014; CreateNamedView x2; SetSectionPlane | headless_feasibility: needs GUI '
          'window? (test)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Named views + section plane on assembly'}


def build(ctx):
    cp = component("Plate", lambda: block((0, 0, 0), (60, 40, 10), "Plate_Body"))
    cb = component("Boss", lambda: cylinder((30, 20, 10), (30, 20, 30), 8, "Boss_Body"))
    ViewHelper.SetProjection(ViewHelper.ViewProjection.Isometric, True, False)
    ViewHelper.CreateNamedView("Iso_Assembly")
    ViewHelper.SetProjection(ViewHelper.ViewProjection.Front, True, False)
    ViewHelper.CreateNamedView("Front_Assembly")
    r = ViewHelper.SetSectionPlane(Plane.Create(Frame.Create(P(0, 20, 0), D(1, 0, 0), D(0, 0, 1))))
    ctx.data["section_ok"] = _safe(lambda: r.Success)
    intent("activate_iso", bool(ViewHelper.ActivateNamedView("Iso_Assembly", True, False)), True)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_view_031_named_views_section.py")
