# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_multi_028_many_bodies_8',
 'category': '20_combo',
 'commands': ['prim_block', 'prim_cylinder', 'prim_sphere', 'doc_rename', 'doc_colors'],
 'expect': {'bodies': 8},
 'feature': 'combo',
 'inventory_expect': {'bodies': 8},
 'notes': 'steps: 8 primitives; rename; colors | headless_feasibility: yes',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': '8 bodies (mixed primitives) in root, each named/colored - id allocation stress'}


def build(ctx):
    bs = []
    for i in range(8):
        x = 30 * i
        if i % 3 == 0:
            bs.append(block((x, 0, 0), (x + 20, 20, 10 + i), "Body_%d_Block" % (i + 1)))
        elif i % 3 == 1:
            bs.append(cylinder((x + 10, 10, 0), (x + 10, 10, 15 + i), 8, "Body_%d_Cyl" % (i + 1)))
        else:
            bs.append(sphere((x + 10, 10, 10), 9, "Body_%d_Sphere" % (i + 1)))
    for i, b in enumerate(bs):
        ColorHelper.SetColor(sel(b), SetColorOptions(), Color.FromArgb(255, (37 * i) % 256, (91 * i) % 256, (53 * i + 60) % 256))
    intent("names_unique", len(set(unicode(b.Name) for b in all_bodies())), 8)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_multi_028_many_bodies_8.py")
