# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R2_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_helix_023_spring_ends_ground',
 'category': '20_combo',
 'commands': ['pull_helix', 'bool_split_body'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'fix R2: helical-sweep bboxes are loose, so the two end pieces after splitting at z=2/z=18 are '
          'identified as the two smallest pieces (not by bbox) | steps: revolve by helix; split body by 2 '
          'planes; delete ends | headless_feasibility: needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Spring: helix sweep of circle, ends cut flat by split planes'}


def build(ctx):
    r = CircularSurface.Create(MM(1), D(0, 1, 0), P(10, 0, 0))
    RevolveFaces.ByHelix(sel(face0(r.CreatedBody)), axis_line(), D(0, 0, 1), MM(20), MM(5), 0.0, True, False, RevolveFaceOptions())
    delete_sheets()
    v_full = vol(largest())
    ctx.data["volume_full_mm3"] = v_full
    SplitBody.ByCutter(sel(largest()), plane_xy(2))
    SplitBody.ByCutter(sel([x for x in bodies_now()]), plane_xy(18))
    ps = sorted(bodies_now(), key=lambda x: vol(x) or 0)
    ctx.data["piece_volumes"] = [vol(x) for x in ps]
    gone = ps[:-1] if len(ps) >= 3 else []
    ctx.data["pieces_deleted"] = len(gone)
    if gone:
        Delete.Execute(sel(gone))
    name_bodies(["Spring"])
    intent("pieces_deleted", len(gone), 2)
    intent_range("kept_fraction", total_volume() / v_full, 0.70, 0.90)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_helix_023_spring_ends_ground.py")
