# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_asm_015_instances_pattern',
 'category': '20_combo',
 'commands': ['asm_component', 'asm_instance', 'mp_translate', 'mp_rotate'],
 'expect': {'components': 4},
 'feature': 'combo',
 'inventory_expect': {'components': 4, 'part_defs': 2},
 'notes': 'steps: comp Bolt; copy/paste 3x; move/rotate instances | headless_feasibility: needs selection '
          'setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Assembly with 1 part definition instanced 4x (translated + rotated)'}


def build(ctx):
    comp = component("Bolt", lambda: cylinder((0, 0, 0), (0, 0, 30), 4, "Bolt_Body"))
    root = GetRootPart()
    tmpl = _safe(lambda: comp.Template) or master(comp).Template
    for i in range(1, 4):
        def inst():
            n0 = len(list(root.Components))
            Copy.ToClipboard(sel(comp))
            Paste.FromClipboard()
            cs = list(root.Components)
            if len(cs) <= n0:
                raise Exception("paste created no component")
            return cs[-1]
        c = first_ok(ctx, "copy_%d" % i, [inst, lambda: raw("instance", lambda: Component.Create(master(root), tmpl))])
        c.Transform(Matrix.CreateTranslation(Vector.Create(MM(30 * i), 0, 0)))
        if i == 3:
            c.Transform(Matrix.CreateRotation(Line.Create(P(90, 0, 0), D(1, 0, 0)), DEG(90)))
    ctx.data["part_defs"] = doc_stats()["part_defs"]
    intent("bodies", len(all_bodies()), 4)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_asm_015_instances_pattern.py")
