# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_prep_020_midsurface_share_topology',
 'category': '20_combo',
 'commands': ['rp_midsurface', 'rp_share_topology'],
 'expect': {},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'steps: 2 plates T-joint; Midsurface; ShareTopology | headless_feasibility: yes',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Plate assembly midsurfaced and topology shared'}


def build(ctx):
    a = block((0, 0, 0), (100, 50, 3), "Plate_Base")
    b = block((48.5, 0, 3), (51.5, 50, 40), "Plate_Web")
    def chk_mid():
        if not any(is_sheet(x) for x in all_bodies()):
            raise Exception("no midsurface sheet created")
    def mk_mid():
        try:
            return Midsurface(MidsurfaceOptions())
        except Exception:
            return Midsurface()
    def mid_range():
        m = mk_mid()
        m.AddFacePairsByRange(sel(a, b), MM(2), MM(4))
        m.Execute()
        chk_mid()
    def mid_pairs():
        m = mk_mid()
        m.AddMatchingFacePairs(top_face(a), bottom_face(a))
        m.AddMatchingFacePairs(face_extreme(b, (1, 0, 0), 1), face_extreme(b, (1, 0, 0), -1))
        m.Execute()
        chk_mid()
    def mid_conv():
        Midsurface.Convert(sel(a, b), MM(3))
        chk_mid()
    first_ok(ctx, "midsurface", [mid_range, mid_pairs, mid_conv])
    ctx.data["after_mid"] = [[unicode(x.Name), is_sheet(x)] for x in all_bodies()]
    first_ok(ctx, "share", [lambda: ShareTopology.FindAndFix(sel(all_bodies()), ShareTopologyOptions()), lambda: ShareTopology.FindAndFix()])
    intent_range("sheet_bodies", len([x for x in all_bodies() if is_sheet(x)]), 1, 3)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_prep_020_midsurface_share_topology.py")
