# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R2_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_mesh_032_mesh_plus_solid',
 'category': '20_combo',
 'commands': ['mesh_facet', 'prim_cylinder'],
 'expect': {'bodies': 1, 'meshes': 1},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'fix R2: headless Copy/Paste left no body, so the second cylinder is modelled directly and '
          'converted to a facet mesh | steps: cyl; copy; FacetConvert | headless_feasibility: yes',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P2',
 'title': 'Document with solid body + facet body converted from a copy'}


def build(ctx):
    c = cylinder((0, 0, 0), (0, 0, 30), 10, "Solid_Cyl")
    c2 = cylinder((40, 0, 0), (40, 0, 30), 10, "Cyl_To_Mesh")
    FacetConvert.Create(sel(c2), FacetConvertOptions())
    _safe(lambda: set_name(list(GetRootPart().Meshes)[0], "Cyl_Mesh"))
    intent("solid_volume_mm3", round(total_volume(), 1), round(3.14159265 * 100 * 30, 1), 1.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_mesh_032_mesh_plus_solid.py")
