# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_bracket_001_sketch_pull_round_hole',
 'category': '20_combo',
 'commands': ['sk_line', 'pull_extrude_face', 'edge_round', 'pull_extrude_cut'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: sketch L chain 60x40 t8; extrude 30; ConstantRound inner edge r5; cut 2 holes r3 | '
          'headless_feasibility: needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'L-bracket: sketch L profile, pull 30, round inner edge r5, 2 through holes r3'}


def build(ctx):
    s = planar(poly_curves([(0, 0, 0), (60, 0, 0), (60, 8, 0), (8, 8, 0), (8, 40, 0), (0, 40, 0)]), plane_xy(0), "L_Bracket")
    extrude(face0(s), 30)
    b = largest()
    ConstantRound.Execute(sel(edge_nearest(b, (8, 8, 15), "Line")), MM(5), ConstantRoundOptions())
    b = largest()
    for x in (30, 50):
        subtract(ctx, largest(), cylinder((x, -1, 15), (x, 9, 15), 3, "Hole_Cutter"))
    delete_sheets()
    name_bodies(["L_Bracket"], [largest()])
    intent("volume_mm3", round(total_volume(), 1), 21788.5, 3.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_bracket_001_sketch_pull_round_hole.py")
