# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_doc_013_datums_named_selection_on_edges',
 'category': '20_combo',
 'commands': ['doc_datum', 'edge_round', 'doc_named_selection'],
 'expect': {'bodies': 1, 'datum_planes': 1},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'steps: block; round; datum plane z=5; datum axis; NS of round faces | headless_feasibility: needs '
          'selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Datum plane + axis + named selection of edges on filleted block'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Datum_Round_Block")
    ConstantRound.Execute(sel(edges_at_z(b, 20)), MM(2), ConstantRoundOptions())
    b = largest()
    DatumPlaneCreator.Create(P(0, 0, 5), D(0, 0, 1))
    first_ok(ctx, "datum_axis", [lambda: DatumLineCreator.Create(P(20, 15, 0), D(0, 0, 1))])
    rounds = faces(b, "Cylinder")
    r = NamedSelection.Create(sel(rounds), Selection.Empty())
    NamedSelection.Rename(unicode(r.CreatedNamedSelection.Name), "NS_Round_Faces")
    intent("round_faces", len(rounds), 4)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_doc_013_datums_named_selection_on_edges.py")
