# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R2_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_edit_030_pull_after_pattern',
 'category': '20_combo',
 'commands': ['mp_pattern_linear', 'pull_face_offset', 'edge_round'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'fix R2: patterning a whole body creates pattern components, so the boss is merged first and its '
          'faces are patterned (4 bosses on one body); then the plate bottom is pulled 2 mm and the boss top '
          'edges rounded | steps: plate; boss; linear pattern 4; pull base -2; round bosses r1 | '
          'headless_feasibility: needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Pattern of bosses then pull base face + round (pattern relation survives edit)'}


def build(ctx):
    plate = block((0, 0, 0), (60, 40, 5), "Base_Plate")
    boss = cylinder((10, 20, 5), (10, 20, 10), 3, "Boss")
    Combine.Merge(sel(plate, boss))
    b = largest()
    bf = [f for f in b.Faces if _dist(bbox_center(f), (10, 20, 7.5)) < 3.0]
    ctx.data["boss_faces"] = len(bf)
    dirc = dcurve(seg((0, -5, 0), (10, -5, 0)), "Pattern_Direction_X")
    d = LinearPatternData()
    setp(ctx, d, [("PatternDimension", PatternDimensionType.One), ("LinearDirection", sel(dirc)), ("CountX", 4), ("PitchX", MM(12))], "linear")
    Pattern.CreateLinear(sel(bf), d, None)
    b = largest()
    extrude(bottom_face(b), 2)
    b = largest()
    tops = [e for e in edges_at_z(b, 10)]
    ConstantRound.Execute(sel(tops), MM(1), ConstantRoundOptions())
    name_bodies(["Base_Plate"], [largest()])
    intent("bodies", len(bodies_now()), 1)
    intent("boss_top_edges", len(tops), 4)
    intent_range("volume_mm3", total_volume(), 60 * 40 * 7 + 4 * 3.14159265 * 9 * 5 - 60, 60 * 40 * 7 + 4 * 3.14159265 * 9 * 5)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_edit_030_pull_after_pattern.py")
