# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_prep_021_enclosure_named_selection',
 'category': '20_combo',
 'commands': ['rp_volume_extract', 'doc_named_selection'],
 'expect': {'bodies': 2},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'steps: body; Enclosure; NamedSelection faces | headless_feasibility: needs selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'CFD prep: body + box enclosure (cushion 20) + named selections inlet/outlet'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Inner_Body")
    o = EnclosureOptions()
    setp(ctx, o, [("EnclosureType", _safe(lambda: EnclosureType.Box))], "encl_opts")
    Enclosure.Create(sel(b), o)
    enc = [x for x in all_bodies() if x.Name != "Inner_Body"]
    ctx.data["enclosure_names"] = [unicode(x.Name) for x in enc]
    e = max(enc, key=lambda x: bbox(x)[1][0] - bbox(x)[0][0])
    set_name(e, "Enclosure_Box")
    r = NamedSelection.Create(sel(face_extreme(e, (1, 0, 0), -1)), Selection.Empty())
    NamedSelection.Rename(unicode(r.CreatedNamedSelection.Name), "Inlet")
    r = NamedSelection.Create(sel(face_extreme(e, (1, 0, 0), 1)), Selection.Empty())
    NamedSelection.Rename(unicode(r.CreatedNamedSelection.Name), "Outlet")
    intent("ns_count", len(doc_stats()["named_selections"]), 2)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_prep_021_enclosure_named_selection.py")
