# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_bool_005_block_cyl_sphere',
 'category': '20_combo',
 'commands': ['bool_merge', 'bool_subtract', 'bool_intersect'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: block; cyl merge; sphere subtract; intersect with big cyl | headless_feasibility: yes',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Boolean chain: block + cylinder boss merge, subtract sphere, intersect with cylinder'}


def build(ctx):
    b = block((0, 0, 0), (40, 40, 20), "Bool_Part")
    c = cylinder((20, 20, 20), (20, 20, 40), 10, "Boss")
    Combine.Merge(sel(b, c))
    b = largest()
    subtract(ctx, b, sphere((20, 20, 40), 8, "Sphere_Cutter"))
    tool = cylinder((20, 20, -1), (20, 20, 50), 18, "Intersect_Tool")
    intersect_keep(ctx, largest([x for x in bodies_now() if x.Name != "Intersect_Tool"]), tool)
    name_bodies(["Bool_Part"], [largest()])
    bb = bbox(largest())
    intent("x_span_mm", round(bb[1][0] - bb[0][0], 3), 36.0, 0.01)
    intent("bodies_left", len(bodies_now()), 1)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_bool_005_block_cyl_sphere.py")
