# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_hole_022_holes_pattern_plate',
 'category': '20_combo',
 'commands': ['hole_standard', 'mp_pattern_circular'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'steps: plate; StandardHoles cbore M6; circular pattern 4 | headless_feasibility: needs selection '
          'setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P1',
 'title': 'Plate with counterbored M6 hole circular-patterned 4x'}


def build(ctx):
    def std_hole(ctx, b, x, y, opts):
        top = top_face(b)
        pt = P(x, y, bbox(b)[1][2])
        HL = find_type(ctx, "HoleLocation")
        _safe(lambda: ctor_sigs(ctx, "HoleLocation"))
        mf = master(top)
        uv = _safe(lambda: mf.Shape.ProjectPoint(pt).Param)
        pool = [("IDesignFace", top), ("DesignFace", mf), ("Point", pt), ("PointUV", uv),
                ("IList`1", List[Point]([pt])), ("ICollection`1", List[Point]([pt])), ("IEnumerable`1", List[Point]([pt]))]
        def by_auto():
            loc = auto_new(ctx, "HoleLocation", HL, pool)
            L = List[HL]()
            L.Add(loc)
            return StandardHoles.Create(L, None, opts)
        def by_auto2():
            loc = auto_new(ctx, "HoleLocation2", HL, pool)
            L = List[HL]()
            L.Add(loc)
            return StandardHoles.Create(L, opts)
        r = first_ok(ctx, "standard_hole", [by_auto, by_auto2])
        ctx.data["hole_result"] = _safe(lambda: [n for n in dir(r) if not n.startswith("_")])
        return r

    plate = cylinder((0, 0, 0), (0, 0, 10), 50, "Hole_Disk")
    o = StandardHolesOptions()
    setp(ctx, o, [("SeriesName", "ISO"), ("FastenerName", "M6"), ("HoleRadius", MM(3.2)), ("CounterboreRadius", MM(5.5)), ("CounterboreDepth", MM(6.5)), ("HoleDepth", MM(10))], "hole_opts")
    std_hole(ctx, plate, 30, 0, o)
    p = largest()
    hf = [f for f in p.Faces if gtype(f) != "Plane" and _dist(bbox_center(f), (30, 0, 5)) < 8]
    outer = max(faces(p, "Cylinder"), key=lambda f: bbox(f)[1][0] - bbox(f)[0][0])
    d = CircularPatternData()
    setp(ctx, d, [("PatternDimension", PatternDimensionType.One), ("CircularAxis", sel(outer)), ("CircularCount", 4), ("CircularAngle", DEG(360))], "circular")
    first_ok(ctx, "pattern", [lambda: Pattern.CreateCircular(sel(hf), d, None)])
    ctx.data["faces_after"] = face_count(largest())

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_hole_022_holes_pattern_plate.py")
