# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B13_combo_a.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_spline_007_spline_extrude_round',
 'category': '20_combo',
 'commands': ['sk_spline', 'pull_extrude_face', 'edge_round'],
 'expect': {'bodies': 1},
 'feature': 'combo',
 'inventory_expect': {'bodies': 1},
 'notes': 'steps: sketch periodic spline; extrude 10; round top edge r1 | headless_feasibility: needs '
          'selection setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P0',
 'title': 'Spline cam: closed spline profile extruded 10, rounded r1'}


def build(ctx):
    import math
    pts = [(25 * math.cos(a) * (1 + 0.15 * math.cos(3 * a)), 25 * math.sin(a) * (1 + 0.15 * math.cos(3 * a)), 0) for a in [i * math.pi / 4 for i in range(8)]]
    s = planar([spline_curve(pts, True)], plane_xy(0), "Spline_Disk")
    extrude(face0(s), 10)
    delete_sheets()
    b = largest()
    ConstantRound.Execute(sel(edges_at_z(b, 10)), MM(1), ConstantRoundOptions())
    name_bodies(["Spline_Disk"], [largest()])
    intent_range("faces", face_count(largest()), 4, 8)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_spline_007_spline_extrude_round.py")
