# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B14_combo_b.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '20_combo_surface_025_sheets_stitch_thicken',
 'category': '20_combo',
 'commands': ['prim_planar_body', 'sc_surfaces', 'rp_fix', 'so_thicken'],
 'expect': {},
 'feature': 'combo',
 'inventory_expect': {},
 'notes': 'steps: planar bodies; surface body; StitchFaces; Thicken | headless_feasibility: needs selection '
          'setup',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\20_combo',
 'params': {},
 'priority': 'P2',
 'title': 'Sheets: 2 planar + 1 cylindrical surface stitched, thickened 2mm'}


def build(ctx):
    import math
    a = sheet_rect(0, 0, 20, 20, 0, "Sheet_Floor")
    w = planar(poly_curves([(20, 0, 0), (20, 20, 0), (20, 20, 20), (20, 0, 20)]), plane_at((20, 10, 10), (1, 0, 0)), "Sheet_Wall")
    srf = Cylinder.Create(Frame.Create(P(0, 0, 0), D(1, 0, 0), D(0, 1, 0)), MM(5))
    ctx.attempt("surface_body", lambda: SurfaceBody.Create(srf, BoxUV.Create(Interval.Create(0, math.pi), Interval.Create(MM(30), MM(40))), GetRootPart(), "Cyl_Patch"))
    first_ok(ctx, "stitch", [lambda: StitchFaces.FindAndFix(sel(a, w)), lambda: StitchFaces.FindAndFix(sel(a, w), StitchOptions())])
    st = [x for x in all_bodies() if is_sheet(x) and face_count(x) == 2]
    ctx.data["stitched"] = len(st)
    tgt = st[0] if st else a
    first_ok(ctx, "thicken", [lambda: ThickenFaces.Execute(sel(list(tgt.Faces)), MM(1), ThickenFaceOptions()),
                              lambda: ThickenFaces.Execute(sel(list(tgt.Faces)), D(0, 0, 1), MM(1), ThickenFaceOptions()),
                              lambda: ThickenFaces.Execute(sel(tgt), MM(1), ThickenFaceOptions())])
    ctx.data["bodies_after"] = [[unicode(x.Name), is_sheet(x), round(vol(x) or 0, 1)] for x in all_bodies()]
    intent("stitched_two_face_sheet", len(st), 1)
    intent("has_solid", any(not is_sheet(x) for x in all_bodies()), True)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\20_combo\20_combo_surface_025_sheets_stitch_thicken.py")
