# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B10_beam_sheetmetal.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '09_beam_profile_002_rect_tube_60x40x3',
 'category': '09_beam',
 'commands': ['BeamProfile.CreateI/CreateL/CreateT/CreateChannel/CreateRectangular/CreateCircular/CreateDisk/CreateFlatBar/CreateHat/CreateZ/CreateCustom',
              'BeamProfile.CreateFromLibrary'],
 'expect': {},
 'feature': 'beam_profile',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\09_beam',
 'params': {'d': 40, 't': 3, 'type': 'Rectangular', 'w': 60},
 'priority': 'P1',
 'title': 'Beam profile creation (I/L/T/channel/rect/circular/...): 002_rect_tube_60x40x3'}


def build(ctx):
    def nn(x):
        if x is None:
            raise Exception("None")
        return x
    def profile_part(ctx, r):
        ctx.data["profile_result_members"] = _safe(lambda: [n for n in dir(r) if not n.startswith("_")][:40])
        comps = list(GetRootPart().Components)
        return first_ok(ctx, "profile_part", [lambda: nn(_safe(lambda: r.CreatedProfile)), lambda: nn(comps[-1].Template),
                                              lambda: nn(master(comps[-1]).Template)])
    def make_beams(ctx, prof, curves):
        BM = rawt("Beam")
        out = []
        for c in curves:
            out.append(first_ok(ctx, "beam", [lambda: raw("beam", lambda: BM.Create(prof, master(c))),
                                              lambda: raw("beam", lambda: BM.Create(prof, c)),
                                              lambda: Beam.Create(sel(c), prof)]))
        return out

    r = BeamProfile.CreateRectangular(MM(3), MM(60), MM(40), "Rect_Tube_60x40x3")
    prof = profile_part(ctx, r)
    dcurve(seg((0, 0, 0), (500, 0, 0)), "Beam_Path")
    make_beams(ctx, prof, curves_now())
    intent("beams", doc_stats()["beams"], 1)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\09_beam\09_beam_profile_002_rect_tube_60x40x3.py")
