# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B10_beam_sheetmetal.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '09_beam_create_002_frame_4lines_rect',
 'category': '09_beam',
 'commands': ['Beam.Create(sel curves, profile)',
              'Beam.SetOrientation/SetPosition/SetType/ReverseBeam',
              'Beam.ExtractProfile'],
 'expect': {'beams': 4},
 'feature': 'beam_create',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\09_beam',
 'params': {'curve': 'rect frame 1000x500', 'profile': 'Rectangular'},
 'priority': 'P1',
 'title': 'Beam along curve: 002_frame_4lines_rect'}


def build(ctx):
    def nn(x):
        if x is None:
            raise Exception("None")
        return x
    def profile_part(ctx, r):
        ctx.data["profile_result_members"] = _safe(lambda: [n for n in dir(r) if not n.startswith("_")][:40])
        comps = list(GetRootPart().Components)
        return first_ok(ctx, "profile_part", [lambda: nn(_safe(lambda: r.CreatedProfile)), lambda: nn(comps[-1].Template),
                                              lambda: nn(master(comps[-1]).Template)])
    def make_beams(ctx, prof, curves):
        BM = rawt("Beam")
        out = []
        for c in curves:
            out.append(first_ok(ctx, "beam", [lambda: raw("beam", lambda: BM.Create(prof, master(c))),
                                              lambda: raw("beam", lambda: BM.Create(prof, c)),
                                              lambda: Beam.Create(sel(c), prof)]))
        return out

    pts = [(0, 0, 0), (1000, 0, 0), (1000, 500, 0), (0, 500, 0)]
    for i in range(4):
        dcurve(seg(pts[i], pts[(i + 1) % 4]), "Frame_Edge_%d" % (i + 1))
    prof = profile_part(ctx, BeamProfile.CreateRectangular(MM(3), MM(60), MM(40), "Rect_Tube_60x40x3"))
    make_beams(ctx, prof, curves_now())

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\09_beam\09_beam_create_002_frame_4lines_rect.py")
