# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B10_beam_sheetmetal.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '09_beam_profile_001_I_100x50',
 'category': '09_beam',
 'commands': ['BeamProfile.CreateI/CreateL/CreateT/CreateChannel/CreateRectangular/CreateCircular/CreateDisk/CreateFlatBar/CreateHat/CreateZ/CreateCustom',
              'BeamProfile.CreateFromLibrary'],
 'expect': {},
 'feature': 'beam_profile',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\09_beam',
 'params': {'baseWidth': 50, 'depth': 100, 'tf': 8, 'tw': 5, 'type': 'I'},
 'priority': 'P1',
 'title': 'Beam profile creation (I/L/T/channel/rect/circular/...): 001_I_100x50'}


def build(ctx):
    def nn(x):
        if x is None:
            raise Exception("None")
        return x
    def profile_part(ctx, r):
        ctx.data["profile_result_members"] = _safe(lambda: [n for n in dir(r) if not n.startswith("_")][:40])
        comps = list(GetRootPart().Components)
        return first_ok(ctx, "profile_part", [lambda: nn(_safe(lambda: r.CreatedProfile)), lambda: nn(comps[-1].Template),
                                              lambda: nn(master(comps[-1]).Template)])
    def make_beams(ctx, prof, curves):
        BM = rawt("Beam")
        out = []
        for c in curves:
            out.append(first_ok(ctx, "beam", [lambda: raw("beam", lambda: BM.Create(prof, master(c))),
                                              lambda: raw("beam", lambda: BM.Create(prof, c)),
                                              lambda: Beam.Create(sel(c), prof)]))
        return out

    r = BeamProfile.CreateI(MM(50), MM(100), MM(8), MM(5), "I_100x50")
    prof = profile_part(ctx, r)
    ctx.data["profile"] = [unicode(_safe(lambda: prof.Name)), unicode(_safe(lambda: prof.GetType().Name))]
    dcurve(seg((0, 0, 0), (0, 0, 500)), "Beam_Path")
    make_beams(ctx, prof, curves_now())
    intent("beams", doc_stats()["beams"], 1)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\09_beam\09_beam_profile_001_I_100x50.py")
