# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B07_shell_offset.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_detach_001_block_top',
 'category': '07_shell_offset',
 'commands': ['ReplaceFacesWithFace.Execute', 'DetachFaces.Execute'],
 'expect': {'bodies': 2},
 'feature': 'so_replace_detach',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {},
 'priority': 'P2',
 'title': 'Replace faces / detach faces: block_top'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Detach_Block")
    DetachFaces.Execute(sel(top_face(b)))
    bs = sorted(bodies_now(), key=lambda x: 0 if is_sheet(x) else 1)
    name_bodies(["Detached_Top_Face", "Detach_Block"], bs)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_detach_001_block_top.py")
