# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R1_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_draft_001_block_4sides_5deg',
 'category': '07_shell_offset',
 'commands': ['DraftFaces.Execute(sel, refFaces, DraftSide, angle, ExtrudeType, DraftOptions)'],
 'expect': {'bodies': 1, 'faces': 6},
 'feature': 'so_draft',
 'inventory_expect': None,
 'notes': 'fix R1: draft must narrow the block towards the top (neutral plane bottom face); sign/side chosen '
          'by validated trial on a fresh body',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {'angle_deg': 5, 'neutral': '-Z'},
 'priority': 'P1',
 'title': 'Draft faces: block_4sides_5deg'}


def build(ctx):
    def drafted(ctx, name, kind="block"):
        """Draft the side faces so the part narrows towards the top (neutral plane = bottom face). Tries angle sign /
        draft side combinations on a fresh body and keeps the first whose volume shrinks and whose bbox stays inside."""
        import math
        forms = [("This", -5), ("This", 5), ("Other", 5), ("Other", -5), ("NoSplit", -5), ("NoSplit", 5)]
        ang0 = 5 if kind == "block" else 3
        v_full = 24000.0 if kind == "block" else math.pi * 100 * 20
        lim = (0.0, 40.0) if kind == "block" else (-10.0, 10.0)
        log = []
        for sd, sgn in forms:
            if bodies_now():
                Delete.Execute(sel(bodies_now()))
            if kind == "block":
                b = block((0, 0, 0), (40, 30, 20), name)
                sides = [face_extreme(b, a, s) for a in [(1, 0, 0), (0, 1, 0)] for s in (1, -1)]
            else:
                b = cylinder((0, 0, 0), (0, 0, 20), 10, name)
                sides = faces(b, "Cylinder")
            ang = ang0 if sgn > 0 else -ang0
            try:
                DraftFaces.Execute(sel(sides), sel(bottom_face(b)), getattr(DraftSide, sd), DEG(ang), getattr(ExtrudeType, "None"), DraftOptions())
            except Exception as e:
                log.append([sd, ang, "error: " + unicode(e)[:120]])
                continue
            b = largest()
            v, bb = vol(b), bbox(b)
            log.append([sd, ang, v, bb])
            if v is not None and v < v_full - 1.0 and bb[0][0] >= lim[0] - 1e-3 and bb[1][0] <= lim[1] + 1e-3:
                ctx.data["draft_form"] = [sd, ang]
                ctx.data["draft_log"] = log
                return b
        ctx.data["draft_log"] = log
        raise Exception("no draft form narrowed the part inward: %s" % log)

    b = drafted(ctx, "Draft_Block", "block")
    ctx.data["bbox_after_mm"] = bbox(b)
    ctx.data["volume_after_mm3"] = vol(b)
    bt = [f for f in b.Faces if gtype(f) == "Plane" and abs(bbox(f)[0][2] - 20) < 1e-6 and abs(bbox(f)[1][2] - 20) < 1e-6][0]
    tb = bbox(bt)
    intent_range("top_face_x_span_mm", tb[1][0] - tb[0][0], 36.0, 39.9)
    intent_range("volume_mm3", vol(b), 20000, 23999)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_draft_001_block_4sides_5deg.py")
