# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B07_shell_offset.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_offset_002_cyl_face_minus1',
 'category': '07_shell_offset',
 'commands': ['OffsetFaces.Execute(sel, offset, OffsetFaceOptions)', 'OffsetRelation.ChangeOffset'],
 'expect': {'bodies': 1, 'faces': 3},
 'feature': 'so_offset',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {'d_mm': -1},
 'priority': 'P1',
 'title': 'Offset faces: cyl_face_minus1'}


def build(ctx):
    b = cylinder((0, 0, 0), (0, 0, 20), 10, "Offset_Cyl")
    OffsetFaces.Execute(sel(faces(b, "Cylinder")), MM(-1), OffsetFaceOptions())
    ctx.data["volume_after_mm3"] = vol(body_named("Offset_Cyl"))
    ctx.data["r9_volume_mm3"] = round(math.pi * 81 * 20, 6)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_offset_002_cyl_face_minus1.py")
