# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B07_shell_offset.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_offset_001_block_top_plus3',
 'category': '07_shell_offset',
 'commands': ['OffsetFaces.Execute(sel, offset, OffsetFaceOptions)', 'OffsetRelation.ChangeOffset'],
 'expect': {'bodies': 1, 'faces': 6, 'volume_mm3': 27600.0},
 'feature': 'so_offset',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {'d_mm': 3},
 'priority': 'P1',
 'title': 'Offset faces: block_top_plus3'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Offset_Block")
    OffsetFaces.Execute(sel(top_face(b)), MM(3), OffsetFaceOptions())

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_offset_001_block_top_plus3.py")
