# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R1_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_replaceface_001_block_top_to_plane',
 'category': '07_shell_offset',
 'commands': ['ReplaceFacesWithFace.Execute', 'DetachFaces.Execute'],
 'expect': {'bodies': 1, 'faces': 6, 'volume_mm3': 24000.0},
 'feature': 'so_replace_detach',
 'inventory_expect': None,
 'notes': 'reinterpreted (R1): V19 ReplaceFacesWithFace only merges several faces into one face (no '
          'target/source replace exists); block top split in two, then both halves replaced by one face '
          '(faces 7 -> 6)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {},
 'priority': 'P2',
 'title': 'Replace faces / detach faces: block_top_to_plane'}


def build(ctx):
    def not_feasible_if_all_fail(ctx, key, fns, reason):
        try:
            return first_ok(ctx, key, fns)
        except Exception as e:
            raise NotFeasible(reason + " | last error: " + unicode(e)[-300:])

    b = block((0, 0, 0), (40, 30, 20), "Replace_Block")
    SplitFace.ByTwoPoints(sel(top_face(b)), P(20, 0, 20), P(20, 30, 20))
    b = largest()
    halves = [f for f in b.Faces if gtype(f) == "Plane" and abs(bbox(f)[0][2] - 20) < 1e-6 and abs(bbox(f)[1][2] - 20) < 1e-6]
    ctx.data["top_halves"] = len(halves)
    ctx.data["faces_before"] = face_count(b)
    def chk():
        if face_count(largest()) != 6:
            raise Exception("faces still %d" % face_count(largest()))
    def fl(fs):
        l = List[API.IDesignFace]()
        for f in fs:
            l.Add(f)
        return l
    def f1():
        ReplaceFacesWithFace.Execute(sel(halves))
        chk()
    def f2():
        ReplaceFacesWithFace.Execute(sel(halves), ReplaceFacesWithFaceOptions())
        chk()
    def f3():
        ReplaceFacesWithFace.Execute(fl(halves))
        chk()
    not_feasible_if_all_fail(ctx, "replace", [f1, f2, f3], "ReplaceFacesWithFace did not merge the split faces headless")
    set_name(largest(), "Replace_Block")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_replaceface_001_block_top_to_plane.py")
