# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B07_shell_offset.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_shell_open_001_block_top_t2',
 'category': '07_shell_offset',
 'commands': ['Shell.RemoveFaces(sel faces, thickness)', 'Shell.ShellBodies(sel bodies, thickness)'],
 'expect': {'bodies': 1, 'faces': 11, 'volume_mm3': 7152.0},
 'feature': 'so_shell',
 'inventory_expect': None,
 'notes': 't=2 inward: Shell.RemoveFaces(..., MM(-2)) (V18 API: positive grows outward)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {'base': 'block 40x30x20', 'remove': '+Z', 't_mm': 2},
 'priority': 'P0',
 'title': 'Shell (remove faces / hollow): 001_block_top_t2'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Housing")
    Shell.RemoveFaces(sel(top_face(b)), MM(-2))
    ctx.data["bbox_after_mm"] = bbox(body_named("Housing"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_shell_open_001_block_top_t2.py")
