# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B07_shell_offset.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_shell_open_003_cyl_top_t1p5',
 'category': '07_shell_offset',
 'commands': ['Shell.RemoveFaces(sel faces, thickness)', 'Shell.ShellBodies(sel bodies, thickness)'],
 'expect': {'bodies': 1, 'faces': 5, 'volume_mm3': 2955.845988},
 'feature': 'so_shell',
 'inventory_expect': None,
 'notes': 't=1.5 inward',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {'base': 'cyl r10 h30', 'remove': 'top', 't_mm': 1.5},
 'priority': 'P0',
 'title': 'Shell (remove faces / hollow): 003_cyl_top_t1p5'}


def build(ctx):
    b = cylinder((0, 0, 0), (0, 0, 30), 10, "Cup")
    Shell.RemoveFaces(sel(top_face(b)), MM(-1.5))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_shell_open_003_cyl_top_t1p5.py")
