# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B07_shell_offset.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_shell_closed_002_hollow_sphere_t1',
 'category': '07_shell_offset',
 'commands': ['Shell.RemoveFaces(sel faces, thickness)', 'Shell.ShellBodies(sel bodies, thickness)'],
 'expect': {'bodies': 1, 'faces': 2, 'volume_mm3': 1135.162145},
 'feature': 'so_shell',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {'base': 'sphere r10', 't_mm': 1},
 'priority': 'P0',
 'title': 'Shell (remove faces / hollow): 002_hollow_sphere_t1'}


def build(ctx):
    b = sphere((0, 0, 0), 10, "Hollow_Sphere")
    first_ok(ctx, "shell_body", [
        lambda: Shell.ShellBodies(sel(b), MM(-1)),
        lambda: Shell.ShellBodies(sel(b), MM(1))])
    ctx.data["volume_after_mm3"] = vol(body_named("Hollow_Sphere"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_shell_closed_002_hollow_sphere_t1.py")
