# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B07_shell_offset.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_thicken_002_cyl_sheet_t1',
 'category': '07_shell_offset',
 'commands': ['ThickenFaces.Execute(sel, Direction, value, ThickenFaceOptions)'],
 'expect': {'bodies': 1},
 'feature': 'so_thicken',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {'base': 'half-cylinder sheet r20', 't_mm': 1},
 'priority': 'P1',
 'title': 'Thicken surface to solid: cyl_sheet_t1'}


def build(ctx):
    c = dcurve(arc_curve((0, 0, 0), 20, 0, 180), "HalfCyl_Arc")
    ExtrudeEdges.Execute(sel(c), P(20, 0, 0), D(0, 0, 1), MM(30), ExtrudeEdgeOptions())
    sh = [x for x in bodies_now() if is_sheet(x)]
    ctx.data["sheets"] = len(sh)
    s = sh[0]
    set_name(s, "HalfCyl_Thick")
    ThickenFaces.Execute(sel(face0(s)), D(1, 0, 0), MM(1), ThickenFaceOptions())
    name_bodies(["HalfCyl_Thick"], [largest()])
    ctx.data["volume_outward_mm3"] = round(math.pi * (21 ** 2 - 20 ** 2) / 2 * 30, 6)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_thicken_002_cyl_sheet_t1.py")
