# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B07_shell_offset.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_thicken_001_planar_t2',
 'category': '07_shell_offset',
 'commands': ['ThickenFaces.Execute(sel, Direction, value, ThickenFaceOptions)'],
 'expect': {'bodies': 1, 'faces': 6, 'volume_mm3': 1600.0},
 'feature': 'so_thicken',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\07_shell_offset',
 'params': {'base': 'planar rect 40x20', 't_mm': 2},
 'priority': 'P1',
 'title': 'Thicken surface to solid: planar_t2'}


def build(ctx):
    s = sheet_rect(0, 0, 40, 20, 0, "Thickened_Plate")
    ThickenFaces.Execute(sel(face0(s)), D(0, 0, 1), MM(2), ThickenFaceOptions())
    name_bodies(["Thickened_Plate"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\07_shell_offset\07_thicken_001_planar_t2.py")
