# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_tangent_001_face_face',
 'category': '10_assembly',
 'commands': ['(raw API) AlignCondition.Create / TangentCondition.Create / OrientCondition.Create / '
              'AnchorCondition.Create / RigidCondition.Create / GearCondition.Create (SpaceClaim.Api.V19)'],
 'expect': {'components': 2, 'mating_conditions': 1},
 'feature': 'asm_conditions',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {},
 'priority': 'P0',
 'title': 'Assembly conditions (align, tangent, orient, anchor, rigid, gear): 001_face_face'}


def build(ctx):
    ca = component("Lower", lambda: block((0, 0, 0), (40, 40, 10), "Lower_Body"))
    cb = component("Upper", lambda: block((0, 0, 20), (20, 20, 30), "Upper_Body"))
    raw("tangent", lambda: TangentCondition.Create(GetRootPart(), top_face(comp_bodies(ca)[0]), bottom_face(comp_bodies(cb)[0])))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_tangent_001_face_face.py")
