# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_instance_002_rotated_instance',
 'category': '10_assembly',
 'commands': ['Copy.ToClipboard/Paste.FromClipboard',
              'ComponentHelper.CopyToComponent',
              'Move.Translate on component',
              'ComponentHelper.MakeIndependent'],
 'expect': {'bodies': 2, 'components': 2, 'part_defs': 1},
 'feature': 'asm_instance',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {'deg': 90},
 'priority': 'P0',
 'title': 'Component instances (copy/paste component, transform): 002_rotated_instance'}


def build(ctx):
    comp = component("Arm", lambda: block((0, -2, 0), (40, 2, 4), "Arm_Body"))
    root = GetRootPart()
    tmpl = _safe(lambda: comp.Template) or master(comp).Template
    c = raw("instance", lambda: Component.Create(master(root), tmpl))
    c.Transform(Matrix.CreateRotation(Line.Create(P(0, 0, 0), D(0, 0, 1)), DEG(90)))
    bbs = [bbox(b) for b in all_bodies()]
    ctx.data["bboxes"] = bbs
    intent("rotated_y_max_mm", round(max(x[1][1] for x in bbs), 3), 40.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_instance_002_rotated_instance.py")
