# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_component_001_two_bodies_two_comps',
 'category': '10_assembly',
 'commands': ['ComponentHelper.CreateAtRoot',
              'ComponentHelper.MoveBodiesToComponent',
              'ComponentHelper.CreateSeparateComponents',
              'ComponentHelper.SetName'],
 'expect': {'bodies': 2, 'components': 2},
 'feature': 'asm_component',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {'bodies': ['block', 'cyl']},
 'priority': 'P0',
 'title': 'Create component / move bodies to component: 001_two_bodies_two_comps'}


def build(ctx):
    a = block((0, 0, 0), (30, 20, 10), "Base_Block")
    c = cylinder((50, 10, 0), (50, 10, 20), 5, "Boss_Cyl")
    r = ComponentHelper.CreateSeparateComponents(sel(a, c))
    comps = list(GetRootPart().Components)
    for cp in comps:
        n = [x.Name for x in comp_bodies(cp)]
        ctx.attempt("setname_" + (n[0] if n else "?"), lambda: ComponentHelper.SetName(cp, "Comp_" + (n[0] if n else "X")))
    ctx.data["component_names"] = [unicode(x.Name) for x in GetRootPart().Components]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_component_001_two_bodies_two_comps.py")
