# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_mirrorcomp_001',
 'category': '10_assembly',
 'commands': ['MirrorComponents.Execute'],
 'expect': {'components': 2},
 'feature': 'asm_mirror_components',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {'plane': 'YZ'},
 'priority': 'P2',
 'title': 'Mirror components: 001'}


def build(ctx):
    comp = component("Wing", lambda: block((10, 0, 0), (30, 10, 5), "Wing_Body"))
    r = DatumPlaneCreator.Create(P(0, 0, 0), D(1, 0, 0))
    dp = list(GetRootPart().DatumPlanes)[-1]
    _safe(lambda: set_name(dp, "Mirror_YZ"))
    MirrorComponents.Execute(sel(comp), sel(dp))
    ctx.data["bboxes"] = [bbox(b) for b in all_bodies()]
    intent("mirrored_x_min_mm", round(min(bbox(b)[0][0] for b in all_bodies()), 3), -30.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_mirrorcomp_001.py")
