# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_insert_001_step_block',
 'category': '10_assembly',
 'commands': ['DocumentInsert.Execute(filename)'],
 'expect': {'bodies': 2},
 'feature': 'asm_insert_file',
 'inventory_expect': None,
 'notes': 'STEP written by this case to 10_assembly\\\\_inputs (scdm_cases only), then inserted next to a '
          'native block',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {'file': 'STEP generated in 01_primitives'},
 'priority': 'P2',
 'title': 'Insert external file as component: 001_step_block'}


def build(ctx):
    import System
    d = System.IO.Path.Combine(CASE["out_dir"], "_inputs")
    if not System.IO.Directory.Exists(d):
        System.IO.Directory.CreateDirectory(d)
    stp = System.IO.Path.Combine(d, "insert_block_20x10x5.stp")
    block((0, 0, 0), (20, 10, 5), "Step_Source_Block")
    first_ok(ctx, "export_step", [lambda: DocumentSave.Execute(stp), lambda: DocumentHelper.GetActiveDocument().SaveAs(stp)])
    ctx.data["step_exists"] = System.IO.File.Exists(stp)
    Delete.Execute(sel(bodies_now()))
    block((40, 0, 0), (60, 10, 5), "Native_Block")
    if System.IO.File.Exists(stp):
        DocumentInsert.Execute(stp)
    else:
        raise Exception("STEP export produced no file")
    ctx.data["bodies_after_insert"] = [unicode(b.Name) for b in all_bodies()]
    intent("total_volume_mm3", total_volume(), 2000.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_insert_001_step_block.py")
