# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_instance_003_make_independent',
 'category': '10_assembly',
 'commands': ['Copy.ToClipboard/Paste.FromClipboard',
              'ComponentHelper.CopyToComponent',
              'Move.Translate on component',
              'ComponentHelper.MakeIndependent'],
 'expect': {'bodies': 2, 'components': 2, 'part_defs': 2},
 'feature': 'asm_instance',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {},
 'priority': 'P0',
 'title': 'Component instances (copy/paste component, transform): 003_make_independent'}


def build(ctx):
    comp = component("Pin", lambda: cylinder((0, 0, 0), (0, 0, 20), 3, "Pin_Body"))
    root = GetRootPart()
    tmpl = _safe(lambda: comp.Template) or master(comp).Template
    c = raw("instance", lambda: Component.Create(master(root), tmpl))
    c.Transform(Matrix.CreateTranslation(Vector.Create(MM(30), 0, 0)))
    ctx.data["part_defs_before"] = doc_stats()["part_defs"]
    comps = list(root.Components)
    first_ok(ctx, "make_independent", [lambda: ComponentHelper.MakeIndependent(comps[-1]),
                                       lambda: ComponentHelper.MakeIndependent(sel(comps[-1]))])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_instance_003_make_independent.py")
