# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_component_002_nested_2levels',
 'category': '10_assembly',
 'commands': ['ComponentHelper.CreateAtRoot',
              'ComponentHelper.MoveBodiesToComponent',
              'ComponentHelper.CreateSeparateComponents',
              'ComponentHelper.SetName'],
 'expect': {'bodies': 1, 'components': 2},
 'feature': 'asm_component',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {'levels': 2},
 'priority': 'P0',
 'title': 'Create component / move bodies to component: 002_nested_2levels'}


def build(ctx):
    c1 = ComponentHelper.CreateAtRoot("Level_1")
    r = ComponentHelper.CreateAtComponent(c1, "Level_2")
    c2 = first_ok(ctx, "level2", [lambda: list(r.CreatedComponents)[0], lambda: list(c1.Components)[0]])
    ComponentHelper.SetActive(c2)
    block((0, 0, 0), (20, 20, 20), "Nested_Block")
    ComponentHelper.SetRootActive()
    ctx.data["paths"] = doc_stats()["component_list"]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_component_002_nested_2levels.py")
