# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_instance_001_3_instances_translated',
 'category': '10_assembly',
 'commands': ['Copy.ToClipboard/Paste.FromClipboard',
              'ComponentHelper.CopyToComponent',
              'Move.Translate on component',
              'ComponentHelper.MakeIndependent'],
 'expect': {'bodies': 3, 'components': 3, 'part_defs': 1},
 'feature': 'asm_instance',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {'n': 3, 'pitch_mm': 50},
 'priority': 'P0',
 'title': 'Component instances (copy/paste component, transform): 001_3_instances_translated'}


def build(ctx):
    comp = component("Bolt", lambda: cylinder((0, 0, 0), (0, 0, 30), 4, "Bolt_Body"))
    root = GetRootPart()
    tmpl = _safe(lambda: comp.Template) or master(comp).Template
    for i in (1, 2):
        c = raw("instance", lambda: Component.Create(master(root), tmpl))
        c.Transform(Matrix.CreateTranslation(Vector.Create(MM(50 * i), 0, 0)))
    intent("instance_x_max_mm", round(max(bbox(b)[1][0] for b in all_bodies()), 3), 104.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_instance_001_3_instances_translated.py")
