# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_component_003_separate_components_4',
 'category': '10_assembly',
 'commands': ['ComponentHelper.CreateAtRoot',
              'ComponentHelper.MoveBodiesToComponent',
              'ComponentHelper.CreateSeparateComponents',
              'ComponentHelper.SetName'],
 'expect': {'bodies': 4, 'components': 4},
 'feature': 'asm_component',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {'bodies': 4},
 'priority': 'P0',
 'title': 'Create component / move bodies to component: 003_separate_components_4'}


def build(ctx):
    bs = [block((30 * i, 0, 0), (30 * i + 20, 20, 10 + 5 * i), "Part_%d" % (i + 1)) for i in range(4)]
    ComponentHelper.CreateSeparateComponents(sel(bs))
    ctx.data["component_names"] = [unicode(x.Name) for x in GetRootPart().Components]

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_component_003_separate_components_4.py")
