# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B08_assembly.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_align_001_axis_axis',
 'category': '10_assembly',
 'commands': ['(raw API) AlignCondition.Create / TangentCondition.Create / OrientCondition.Create / '
              'AnchorCondition.Create / RigidCondition.Create / GearCondition.Create (SpaceClaim.Api.V19)'],
 'expect': {'components': 2, 'mating_conditions': 1},
 'feature': 'asm_conditions',
 'inventory_expect': None,
 'notes': 'condition is stored; headless RunScript does not solve/move components',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\10_assembly',
 'params': {'a': 'plate hole axis', 'b': 'pin axis'},
 'priority': 'P0',
 'title': 'Assembly conditions (align, tangent, orient, anchor, rigid, gear): 001_axis_axis'}


def build(ctx):
    plate = block((0, 0, 0), (60, 40, 10), "Plate_Body")
    subtract(ctx, plate, cylinder((30, 20, -5), (30, 20, 15), 4, "Hole_Cutter"))
    set_name(largest(), "Plate_Body")
    cylinder((100, 20, 5), (100, 20, 35), 4, "Pin_Body")
    ComponentHelper.CreateSeparateComponents(sel(bodies_now()))
    comps = list(GetRootPart().Components)
    cp = [c for c in comps if any(x.Name == "Plate_Body" for x in comp_bodies(c))][0]
    cq = [c for c in comps if any(x.Name == "Pin_Body" for x in comp_bodies(c))][0]
    pb = comp_bodies(cp)[0]
    hole = faces(pb, "Cylinder")[0]
    pin = faces(comp_bodies(cq)[0], "Cylinder")[0]
    raw("align", lambda: AlignCondition.Create(GetRootPart(), hole, pin))
    ctx.data["pin_bbox_after"] = bbox(comp_bodies(cq)[0])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\10_assembly\10_assembly_align_001_axis_axis.py")
