# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R2_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '13_convertsolid_001_closed_sheets',
 'category': '13_surface_curve',
 'commands': ['ConvertToSolid.Execute', 'AutoSkin.Execute'],
 'expect': {'bodies': 1},
 'feature': 'sc_convert_solid',
 'inventory_expect': None,
 'notes': "reinterpreted (R2): V19 ConvertToSolid only accepts a Mesh selection ('must include a Mesh "
          "selection'); block 20 mm -> FacetConvert mesh -> ConvertToSolid(mergeFaces=True) -> solid 8000 "
          'mm3',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\13_surface_curve',
 'params': {},
 'priority': 'P2',
 'title': 'Convert to solid / auto-skin / skin from height field: closed_sheets'}


def build(ctx):
    b = block((0, 0, 0), (20, 20, 20), "Convert_Source")
    FacetConvert.Create(sel(b), FacetConvertOptions())
    m = list(GetRootPart().Meshes)[0]
    ctx.data["meshes_before"] = len(list(GetRootPart().Meshes))
    first_ok(ctx, "convert", [lambda: ConvertToSolid.Execute(sel(m), True), lambda: ConvertToSolid.Execute(sel(m), False)])
    _safe(lambda: set_name(largest(), "Converted_Solid"))
    ctx.data["bodies_after"] = [[unicode(x.Name), is_sheet(x), round(vol(x) or 0, 1), face_count(x)] for x in all_bodies()]
    intent("solid_8000", any((not is_sheet(x)) and abs((vol(x) or 0) - 8000) < 1 for x in all_bodies()), True)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\13_surface_curve\13_convertsolid_001_closed_sheets.py")
