# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B12_surface_holes_mesh.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '13_fill_001_cap_open_box',
 'category': '13_surface_curve',
 'commands': ['Fill.Execute(sel, secondary, FillOptions, FillMode)'],
 'expect': {'bodies': 1},
 'feature': 'sc_fill',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\13_surface_curve',
 'params': {},
 'priority': 'P1',
 'title': 'Fill / patch (cap holes, N-sided patch): cap_open_box'}


def build(ctx):
    b = block((0, 0, 0), (20, 20, 20), "Capped_Box")
    Delete.Execute(sel(top_face(b)))
    b = largest()
    loop = edges_at_z(b, 20)
    o = FillOptions()
    setp(ctx, o, [("FillType", _safe(lambda: FillType.Cap))], "fill_opts")
    first_ok(ctx, "fill", [lambda: Fill.Execute(sel(loop), Selection.Empty(), o, FillMode.ThreeD),
                           lambda: Fill.Execute(sel(loop)),
                           lambda: Fill.Execute(sel(loop), None, FillOptions(), FillMode.ThreeD)])
    b = largest()
    intent("faces", face_count(b), 6)
    intent("volume_mm3", round(vol(b) or 0, 2), 8000.0, 1.0)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\13_surface_curve\13_fill_001_cap_open_box.py")
