# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B12_surface_holes_mesh.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '13_fill_002_patch_4_splines',
 'category': '13_surface_curve',
 'commands': ['Fill.Execute(sel, secondary, FillOptions, FillMode)'],
 'expect': {},
 'feature': 'sc_fill',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\13_surface_curve',
 'params': {},
 'priority': 'P1',
 'title': 'Fill / patch (cap holes, N-sided patch): patch_4_splines'}


def build(ctx):
    c = [spline_curve([(0, 0, 0), (15, 0, 4), (30, 0, 0)]), spline_curve([(30, 0, 0), (30, 15, 4), (30, 30, 0)]),
         spline_curve([(30, 30, 0), (15, 30, 4), (0, 30, 0)]), spline_curve([(0, 30, 0), (0, 15, 4), (0, 0, 0)])]
    dc = [dcurve(s, "Boundary_%d" % (i + 1)) for i, s in enumerate(c)]
    first_ok(ctx, "fill", [lambda: Fill.Execute(sel(dc), Selection.Empty(), FillOptions(), FillMode.ThreeD),
                           lambda: Fill.Execute(sel(dc))])
    name_bodies(["Spline_Patch"])
    intent("sheet_bodies", len([x for x in all_bodies() if is_sheet(x)]), 1)
    intent_range("area_mm2", doc_stats()["area_mm2"], 850, 1100)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\13_surface_curve\13_fill_002_patch_4_splines.py")
