# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B12_surface_holes_mesh.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '13_project_001_circle_onto_block_top',
 'category': '13_surface_curve',
 'commands': ['ProjectToSolid.Execute', 'Wrap.Create', 'ProjectToSketch.Create', 'MoveImprintEdges.Execute'],
 'expect': {'bodies': 1, 'volume_mm3': 24000.0},
 'feature': 'sc_project_wrap',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\13_surface_curve',
 'params': {},
 'priority': 'P2',
 'title': 'Project curves to solid / wrap / imprint: circle_onto_block_top'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Project_Block")
    c = dcurve(circle_curve((20, 15, 30), 5), "Circle_R5")
    o = ProjectToSolidOptions()
    first_ok(ctx, "project", [lambda: ProjectToSolid.Execute(sel(c), sel(top_face(b)), Selection.Empty(), o),
                              lambda: ProjectToSolid.Execute(sel(c), sel(top_face(b)), sel(edge_nearest(b, (0, 0, 10))), o),
                              lambda: ProjectToSolid.Execute(sel(c), sel(b), Selection.Empty(), o)])
    intent("faces", face_count(largest()), 7)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\13_surface_curve\13_project_001_circle_onto_block_top.py")
