# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B12_surface_holes_mesh.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '13_surface_body_001_cylinder_patch',
 'category': '13_surface_curve',
 'commands': ['CircularSurface.Create', 'RectangularSurface.Create', 'SurfaceBody.Create(Surface, BoxUV)'],
 'expect': {'bodies': 1},
 'feature': 'sc_surfaces',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\13_surface_curve',
 'params': {'surface': 'Cylinder r10', 'uv': '0..pi x 0..20'},
 'priority': 'P1',
 'title': 'Surface bodies: circular/rectangular surface, SurfaceBody from API surface: 001_cylinder_patch'}


def build(ctx):
    import math
    srf = Cylinder.Create(Frame.World, MM(10))
    box = BoxUV.Create(Interval.Create(0, math.pi), Interval.Create(0, MM(20)))
    first_ok(ctx, "surface_body", [lambda: SurfaceBody.Create(srf, box, GetRootPart(), "Cylinder_Patch"),
                                   lambda: SurfaceBody.Create(srf, box, master(GetRootPart()), "Cylinder_Patch"),
                                   lambda: SurfaceBody.Create(srf, box)])
    name_bodies(["Cylinder_Patch"])
    intent("area_mm2", round(doc_stats()["area_mm2"], 2), 628.32, 0.5)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\13_surface_curve\13_surface_body_001_cylinder_patch.py")
