# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B12_surface_holes_mesh.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '13_surface_rect_001_30x10',
 'category': '13_surface_curve',
 'commands': ['CircularSurface.Create', 'RectangularSurface.Create', 'SurfaceBody.Create(Surface, BoxUV)'],
 'expect': {'bodies': 1},
 'feature': 'sc_surfaces',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\13_surface_curve',
 'params': {},
 'priority': 'P1',
 'title': 'Surface bodies: circular/rectangular surface, SurfaceBody from API surface: 001_30x10'}


def build(ctx):
    first_ok(ctx, "rect", [lambda: RectangularSurface.Create(MM(30), MM(10), P(0, 0, 0)),
                           lambda: RectangularSurface.Create(MM(30), MM(10))])
    name_bodies(["Rect_Surface_30x10"])
    intent("area_mm2", round(doc_stats()["area_mm2"], 2), 300.0, 0.5)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\13_surface_curve\13_surface_rect_001_30x10.py")
