# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B12_surface_holes_mesh.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '13_splitedge_001_by_count3',
 'category': '13_surface_curve',
 'commands': ['SplitFace.ByTwoPoints/ByCutter/ByParametric/ByCurves',
              'SplitEdge.ByCount/ByLength/ByProportion'],
 'expect': {'bodies': 1, 'edges': 14},
 'feature': 'sc_split_face',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\13_surface_curve',
 'params': {'n': 3},
 'priority': 'P1',
 'title': 'Split face (by curves/cutter/two points/parametric), split edge: by_count3'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Split_Edge_Block")
    SplitEdge.ByCount(sel(edge_nearest(b, (20, 0, 20))), 3)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\13_surface_curve\13_splitedge_001_by_count3.py")
