# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R3_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '13_wrap_001_rect_onto_cylinder',
 'category': '13_surface_curve',
 'commands': ['ProjectToSolid.Execute', 'Wrap.Create', 'ProjectToSketch.Create', 'MoveImprintEdges.Execute'],
 'expect': {},
 'feature': 'sc_project_wrap',
 'inventory_expect': None,
 'notes': 'fix R3: Wrap.Create(selectObject = target body, secondarySelection = sheet face / edges to wrap, '
          'WrapOptions); checked for an imprint on the cylinder',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\13_surface_curve',
 'params': {},
 'priority': 'P2',
 'title': 'Project curves to solid / wrap / imprint: rect_onto_cylinder'}


def build(ctx):
    def wrap_rect(ctx, cy, sh, strict=True):
        o = WrapOptions()
        ctx.data["wrap_opts_members"] = [n for n in dir(o) if not n.startswith("_")]
        n_c0 = len(curves_now())
        def cyl_faces():
            return max(face_count(x) for x in all_bodies() if not is_sheet(x))
        def chk():
            ctx.data["after_wrap"] = {"cyl_faces": cyl_faces(), "curves": len(curves_now()), "bodies": [[unicode(x.Name), is_sheet(x), face_count(x)] for x in all_bodies()]}
            if cyl_faces() <= 3 and (strict or len(curves_now()) <= n_c0):
                raise Exception("no imprint (faces=%d)" % cyl_faces())
        def w1():
            Wrap.Create(sel(cy), sel(face0(sh)), o)
            chk()
        def w2():
            Wrap.Create(sel(cy), sel(list(sh.Edges)), o)
            chk()
        def w3():
            Wrap.Create(sel(cy), sel(sh), o)
            chk()
        first_ok(ctx, "wrap", [w1, w2, w3])
        return cyl_faces()

    cy = cylinder((0, 0, 0), (0, 0, 40), 10, "Wrap_Target_Cyl")
    sh = planar(poly_curves([(10, -5, 15), (10, 5, 15), (10, 5, 25), (10, -5, 25)]), plane_at((10, 0, 20), (1, 0, 0)), "Wrap_Rect")
    nf = wrap_rect(ctx, cy, sh, strict=False)
    ctx.data["cyl_faces"] = nf
    intent_range("cyl_faces_after_imprint", nf, 4, 12)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\13_surface_curve\13_wrap_001_rect_onto_cylinder.py")
