# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_revolve_003_spline_profile_360',
 'category': '03_pull',
 'commands': ['RevolveFaces.Execute(sel, Line axis, angle, RevolveFaceOptions)', 'RevolveEdges.Execute'],
 'expect': {'bodies': 1},
 'feature': 'pull_revolve',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'angle_deg': 360, 'profile': 'spline+line closed'},
 'priority': 'P0',
 'title': 'Revolve: 003_spline_profile_360'}


def build(ctx):
    cs = [spline_curve([(5, 0, 0), (12, 0, 6), (9, 0, 14), (5, 0, 20)]), seg((5, 0, 20), (5, 0, 0))]
    s = planar(cs, plane_xz(), "Revolve_Spline")
    revolve(face0(s), (0, 0, 0), (0, 0, 1), 360)
    name_bodies(["Revolve_Spline"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_revolve_003_spline_profile_360.py")
