# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_loft_001_rect_to_circle',
 'category': '03_pull',
 'commands': ['Loft.Create(blendSelection, guideSelection, LoftOptions)', 'Loft.CreateCenterLine'],
 'expect': {'bodies': 1},
 'feature': 'pull_loft',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'profiles': ['rect 20x20 z=0', 'circle r8 z=30']},
 'priority': 'P0',
 'title': 'Loft / blend between profiles: 001_rect_to_circle'}


def build(ctx):
    a = sheet_rect(-10, -10, 10, 10, 0, "Loft_Rect")
    b = sheet_circle((0, 0, 30), 8, "Loft_Circle")
    Loft.Create(sel(face0(a), face0(b)), None, LoftOptions())
    name_bodies(["Loft_RectCircle"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_loft_001_rect_to_circle.py")
