# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_cut_001_pocket_rect_depth5',
 'category': '03_pull',
 'commands': ['ExtrudeFaces.Execute ExtrudeType.Cut', 'ExtrudeFaces.UpTo'],
 'expect': {'bodies': 1, 'volume_mm3': 31500.0},
 'feature': 'pull_extrude_cut',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'base': 'block 40x40x20', 'pocket': 'rect 10x10 depth 5'},
 'priority': 'P0',
 'title': 'Extrude cut (pocket / through hole): 001_pocket_rect_depth5'}


def build(ctx):
    b = block((0, 0, 0), (40, 40, 20), "Pocket_Block")
    s = sheet_rect(15, 15, 25, 25, 20, "Pocket_Profile")
    extrude(face0(s), 5, (0, 0, -1), ExtrudeType.Cut)
    delete_sheets(ctx)
    name_bodies(["Pocket_Block"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_cut_001_pocket_rect_depth5.py")
