# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_extrude_002_circle_r10_h25',
 'category': '03_pull',
 'commands': ['ExtrudeFaces.Execute(sel, Direction, distance, ExtrudeFaceOptions)'],
 'expect': {'bodies': 1, 'faces': 3, 'volume_mm3': 7853.981634},
 'feature': 'pull_extrude_face',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'h_mm': 25, 'profile': 'circle r10'},
 'priority': 'P0',
 'title': 'Extrude (pull) sketch region to solid: 002_circle_r10_h25'}


def build(ctx):
    s = sheet_circle((0, 0, 0), 10, "Extrude_Circle")
    extrude(face0(s), 25, (0, 0, 1))
    name_bodies(["Extrude_Circle"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_extrude_002_circle_r10_h25.py")
