# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_sweep_003_along_polyline',
 'category': '03_pull',
 'commands': ['Sweep.Execute(sel, trajectories, SweepCommandOptions)'],
 'expect': {'bodies': 1},
 'feature': 'pull_sweep',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'path': 'L-shaped line chain'},
 'priority': 'P0',
 'title': 'Sweep profile along trajectory: 003_along_polyline'}


def build(ctx):
    p1 = dcurve(seg((0, 0, 0), (0, 0, 30)), "Sweep_Path_L1")
    p2 = dcurve(seg((0, 0, 30), (20, 0, 30)), "Sweep_Path_L2")
    r = CircularSurface.Create(MM(2), D(0, 0, 1), P(0, 0, 0))
    Sweep.Execute(sel(face0(r.CreatedBody)), sel(p1, p2), SweepCommandOptions())
    name_bodies(["Sweep_L"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_sweep_003_along_polyline.py")
