# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_sweep_002_rect_along_spline',
 'category': '03_pull',
 'commands': ['Sweep.Execute(sel, trajectories, SweepCommandOptions)'],
 'expect': {'bodies': 1},
 'feature': 'pull_sweep',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'path': '3D spline', 'profile': 'rect 4x2'},
 'priority': 'P0',
 'title': 'Sweep profile along trajectory: 002_rect_along_spline'}


def build(ctx):
    path = dcurve(spline_curve([(0, 0, 0), (10, 5, 10), (20, 0, 20), (30, -5, 25)]), "Sweep_Path_Spline")
    n = _unit((10, 5, 10))
    try:
        ev = path.Shape.Geometry.Evaluate(path.Shape.Bounds.Start)
        d = ev.Tangent
        n = _unit((d.X, d.Y, d.Z))
    except Exception as e:
        ctx.data["tangent_eval_error"] = unicode(e)
    x = _perp(n)
    y = _cross(n, x)
    cor = [tuple(a * x[i] + b * y[i] for i in range(3)) for a, b in [(-2, -1), (2, -1), (2, 1), (-2, 1)]]
    s = planar(poly_curves(cor), Plane.Create(Frame.Create(P(0, 0, 0), D(*x), D(*y))), "Sweep_Profile_Rect")
    Sweep.Execute(sel(face0(s)), sel(path), SweepCommandOptions())
    name_bodies(["Sweep_Spline"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_sweep_002_rect_along_spline.py")
