# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_extrudeedge_002_arc_to_sheet',
 'category': '03_pull',
 'commands': ['ExtrudeEdges.Execute'],
 'expect': {'area_mm2': 628.318531, 'bodies': 1, 'faces': 1},
 'feature': 'pull_extrude_edges',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'curve': 'arc R20 180deg', 'd_mm': 10},
 'priority': 'P1',
 'title': 'Extrude edges/curves to surface: 002_arc_to_sheet'}


def build(ctx):
    c = dcurve(arc_curve((0, 0, 0), 20, 0, 180), "Edge_Arc180")
    first_ok(ctx, "extrude_edge", [
        lambda: ExtrudeEdges.Execute(sel(c), P(20, 0, 0), D(0, 0, 1), MM(10), ExtrudeEdgeOptions()),
        lambda: ExtrudeEdges.Execute(sel(c), MM(10), ExtrudeEdgeOptions())])
    name_bodies(["Sheet_From_Arc"])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_extrudeedge_002_arc_to_sheet.py")
