# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R1_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_cut_003_upto_face',
 'category': '03_pull',
 'commands': ['ExtrudeFaces.Execute ExtrudeType.Cut', 'ExtrudeFaces.UpTo'],
 'expect': {'bodies': 2},
 'feature': 'pull_extrude_cut',
 'inventory_expect': None,
 'notes': 'fix R1: boss (sketch circle r5 on the plate) pulled up to the underside of a separate ceiling '
          'block with ForceIndependent, then merged into the plate only; ceiling stays a separate body',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'mode': 'UpTo'},
 'priority': 'P0',
 'title': 'Extrude cut (pocket / through hole): 003_upto_face'}


def build(ctx):
    plate = block((0, 0, 0), (40, 40, 10), "UpTo_Plate")
    ceil = block((0, 0, 30), (40, 40, 35), "UpTo_Ceiling")
    s = sheet_circle((20, 20, 10), 5, "UpTo_Profile")
    target = bottom_face(ceil)
    o = ExtrudeFaceOptions()
    o.ExtrudeType = ExtrudeType.ForceIndependent
    first_ok(ctx, "upto", [
        lambda: ExtrudeFaces.UpTo(sel(face0(s)), D(0, 0, 1), sel(target), P(20, 20, 10), o),
        lambda: ExtrudeFaces.UpTo(sel(face0(s)), D(0, 0, 1), sel(target), P(20, 20, 30), o)])
    delete_sheets()
    boss = [x for x in bodies_now() if abs(bbox(x)[0][2] - 10) < 1e-6 and abs(bbox(x)[1][2] - 30) < 1e-6]
    ctx.data["boss_found"] = len(boss)
    Combine.Merge(sel(body_named("UpTo_Plate"), boss[0]))
    pl = [x for x in bodies_now() if bbox(x)[0][2] < 1e-6][0]
    set_name(pl, "UpTo_Plate")
    ctx.data["bodies_after"] = [[unicode(x.Name), vol(x), bbox(x)] for x in bodies_now()]
    intent("ceiling_volume_mm3", vol(body_named("UpTo_Ceiling")), 8000.0)
    intent("plate_boss_volume_mm3", round(vol(body_named("UpTo_Plate")), 2), round(16000 + 3.14159265 * 25 * 20, 2), 0.5)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_cut_003_upto_face.py")
