# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_extrude_003_spline_profile_h5',
 'category': '03_pull',
 'commands': ['ExtrudeFaces.Execute(sel, Direction, distance, ExtrudeFaceOptions)'],
 'expect': {'bodies': 1},
 'feature': 'pull_extrude_face',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'h_mm': 5, 'profile': 'closed spline'},
 'priority': 'P0',
 'title': 'Extrude (pull) sketch region to solid: 003_spline_profile_h5'}


def build(ctx):
    pts = [(0, 0, 0), (20, -5, 0), (35, 5, 0), (25, 20, 0), (5, 18, 0)]
    s = planar([spline_curve(pts, True)], plane_xy(0), "Extrude_Spline")
    extrude(face0(s), 5, (0, 0, 1))
    name_bodies(["Extrude_Spline"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_extrude_003_spline_profile_h5.py")
