# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R1_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_profile_002_circle_r6_h12',
 'category': '03_pull',
 'commands': ['ExtrudeProfile.Execute(Profile, distance, parent, name)'],
 'expect': {'bodies': 1, 'faces': 3, 'volume_mm3': 1357.168026},
 'feature': 'pull_extrude_profile',
 'inventory_expect': None,
 'notes': 'retry R1: CircleProfile(Plane, r, PointUV location, angle) with explicit PointUV.Create(0,0) and '
          '0.0',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'h_mm': 12, 'profile': 'CircleProfile r6'},
 'priority': 'P2',
 'title': 'Extrude API Profile directly: 002_circle_r6_h12'}


def build(ctx):
    def not_feasible_if_all_fail(ctx, key, fns, reason):
        try:
            return first_ok(ctx, key, fns)
        except Exception as e:
            raise NotFeasible(reason + " | last error: " + unicode(e)[-300:])

    CP = find_type(ctx, "CircleProfile")
    _safe(lambda: ctor_sigs(ctx, "CircleProfile"))
    def mk():
        return CP(Plane.PlaneXY, MM(6), PointUV.Create(0, 0), 0.0)
    not_feasible_if_all_fail(ctx, "extrude_profile", [
        lambda: ExtrudeProfile.Execute(mk(), MM(12), master(GetRootPart()), "Profile_Circle"),
        lambda: ExtrudeProfile.Execute(mk(), MM(12)),
        lambda: ExtrudeProfile.Execute(CP(Plane.PlaneXY, MM(6), PointUV.Origin, 0.0), MM(12))],
        "ExtrudeProfile with CircleProfile not usable from RunScript")
    name_bodies(["Profile_Circle"])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_profile_002_circle_r6_h12.py")
