# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_helix_001_circle_r1_pitch5_h20',
 'category': '03_pull',
 'commands': ['RevolveFaces.ByHelix', 'RevolveEdges.ByHelix'],
 'expect': {'bodies': 1},
 'feature': 'pull_helix',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'h_mm': 20, 'pitch_mm': 5, 'profile': 'circle r1 at R10'},
 'priority': 'P1',
 'title': 'Revolve by helix (spring/thread): 001_circle_r1_pitch5_h20'}


def build(ctx):
    r = CircularSurface.Create(MM(1), D(0, 1, 0), P(10, 0, 0))
    f = face0(r.CreatedBody)
    RevolveFaces.ByHelix(sel(f), axis_line(), D(0, 0, 1), MM(20), MM(5), 0.0, True, False, RevolveFaceOptions())
    name_bodies(["Helix_Coil"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_helix_001_circle_r1_pitch5_h20.py")
