# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_revolve_001_rect_360',
 'category': '03_pull',
 'commands': ['RevolveFaces.Execute(sel, Line axis, angle, RevolveFaceOptions)', 'RevolveEdges.Execute'],
 'expect': {'bodies': 1, 'volume_mm3': 12566.370614},
 'feature': 'pull_revolve',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'angle_deg': 360, 'profile': 'rect 10x20 offset 5 from axis'},
 'priority': 'P0',
 'title': 'Revolve: 001_rect_360'}


def build(ctx):
    s = planar(poly_curves([(5, 0, 0), (15, 0, 0), (15, 0, 20), (5, 0, 20)]), plane_xz(), "Revolve_Ring")
    revolve(face0(s), (0, 0, 0), (0, 0, 1), 360)
    name_bodies(["Revolve_Ring"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_revolve_001_rect_360.py")
