# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_face_001_block_top_plus10',
 'category': '03_pull',
 'commands': ['ExtrudeFaces.Execute on body face'],
 'expect': {'bodies': 1, 'faces': 6, 'volume_mm3': 36000.0},
 'feature': 'pull_face_offset',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'d_mm': 10, 'face': '+Z'},
 'priority': 'P1',
 'title': 'Pull existing face (grow/shrink body): 001_block_top_plus10'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Block_TopPulled")
    ExtrudeFaces.Execute(sel(top_face(b)), MM(10), ExtrudeFaceOptions())

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_face_001_block_top_plus10.py")
