# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R1_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_profile_001_rect_30x10_h5',
 'category': '03_pull',
 'commands': ['ExtrudeProfile.Execute(Profile, distance, parent, name)'],
 'expect': {'bodies': 1, 'faces': 6, 'volume_mm3': 1500.0},
 'feature': 'pull_extrude_profile',
 'inventory_expect': None,
 'notes': 'retry R1: RectangleProfile(Plane, w, h, PointUV location, angle) with explicit '
          'PointUV.Create(0,0) and 0.0',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'h_mm': 5, 'profile': 'RectangleProfile 30x10'},
 'priority': 'P2',
 'title': 'Extrude API Profile directly: 001_rect_30x10_h5'}


def build(ctx):
    def not_feasible_if_all_fail(ctx, key, fns, reason):
        try:
            return first_ok(ctx, key, fns)
        except Exception as e:
            raise NotFeasible(reason + " | last error: " + unicode(e)[-300:])

    RP = find_type(ctx, "RectangleProfile")
    _safe(lambda: ctor_sigs(ctx, "RectangleProfile"))
    def mk():
        return RP(Plane.PlaneXY, MM(30), MM(10), PointUV.Create(0, 0), 0.0)
    not_feasible_if_all_fail(ctx, "extrude_profile", [
        lambda: ExtrudeProfile.Execute(mk(), MM(5), master(GetRootPart()), "Profile_Rect"),
        lambda: ExtrudeProfile.Execute(mk(), MM(5)),
        lambda: ExtrudeProfile.Execute(RP(Plane.PlaneXY, MM(30), MM(10), PointUV.Origin, 0.0), MM(5))],
        "ExtrudeProfile with RectangleProfile not usable from RunScript")
    name_bodies(["Profile_Rect"])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_profile_001_rect_30x10_h5.py")
