# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_loft_002_three_circles',
 'category': '03_pull',
 'commands': ['Loft.Create(blendSelection, guideSelection, LoftOptions)', 'Loft.CreateCenterLine'],
 'expect': {'bodies': 1},
 'feature': 'pull_loft',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'profiles': ['r10 z0', 'r5 z20', 'r12 z40']},
 'priority': 'P0',
 'title': 'Loft / blend between profiles: 002_three_circles'}


def build(ctx):
    fs = [face0(sheet_circle((0, 0, z), r, "Loft_C%d" % i)) for i, (z, r) in enumerate([(0, 10), (20, 5), (40, 12)])]
    Loft.Create(sel(fs), None, LoftOptions())
    name_bodies(["Loft_3Circles"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_loft_002_three_circles.py")
