# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_extrude_004_symmetric_h20',
 'category': '03_pull',
 'commands': ['ExtrudeFaces.Execute(sel, Direction, distance, ExtrudeFaceOptions)'],
 'expect': {'bodies': 1, 'faces': 6},
 'feature': 'pull_extrude_face',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'PullSymmetric': True, 'h_mm': 20, 'profile': 'rect'},
 'priority': 'P0',
 'title': 'Extrude (pull) sketch region to solid: 004_symmetric_h20'}


def build(ctx):
    s = sheet_rect(0, 0, 40, 20, 0, "Extrude_Symmetric")
    extrude(face0(s), 20, (0, 0, 1), sym=True)
    b = largest()
    name_bodies(["Extrude_Symmetric"], [b])
    ctx.data["bbox_mm"] = bbox(b)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_extrude_004_symmetric_h20.py")
