# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_loft_003_ruled',
 'category': '03_pull',
 'commands': ['Loft.Create(blendSelection, guideSelection, LoftOptions)', 'Loft.CreateCenterLine'],
 'expect': {'bodies': 1, 'volume_mm3': 4666.666667},
 'feature': 'pull_loft',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'ruled': True},
 'priority': 'P0',
 'title': 'Loft / blend between profiles: 003_ruled'}


def build(ctx):
    a = sheet_rect(-10, -10, 10, 10, 0, "Ruled_Bottom")
    b = sheet_rect(-5, -5, 5, 5, 20, "Ruled_Top")
    o = LoftOptions()
    o.IsRuled = True
    Loft.Create(sel(face0(a), face0(b)), None, o)
    name_bodies(["Loft_Ruled"], [largest()])

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_loft_003_ruled.py")
