# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B03_pull.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_sweep_001_circle_along_arc',
 'category': '03_pull',
 'commands': ['Sweep.Execute(sel, trajectories, SweepCommandOptions)'],
 'expect': {'bodies': 1},
 'feature': 'pull_sweep',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\03_pull',
 'params': {'path': 'arc R40 90deg', 'profile': 'circle r3'},
 'priority': 'P0',
 'title': 'Sweep profile along trajectory: 001_circle_along_arc'}


def build(ctx):
    path = dcurve(arc_curve((0, 0, 0), 40, 0, 90), "Sweep_Path_Arc")
    r = CircularSurface.Create(MM(3), D(0, 1, 0), P(40, 0, 0))
    Sweep.Execute(sel(face0(r.CreatedBody)), sel(path), SweepCommandOptions())
    b = largest()
    name_bodies(["Sweep_Arc"], [b])
    ctx.data["volume_pappus_mm3"] = round(math.pi * 9 * (math.pi / 2 * 40), 6)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\03_pull\03_pull_sweep_001_circle_along_arc.py")
