# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_constraint_901_pilot_rect_hv_dims',
 'category': '02_sketch',
 'feature': 'sk_constraints',
 'title': 'Constraint sketch: 4 lines, horizontal/vertical constraints, length dimensions',
 'params': {'lines': 4, 'constraints': ['Horizontal', 'Vertical'], 'dims_mm': [40, 20]},
 'expect': {},
 'commands': ['SketchHelper.StartConstraintSketching',
              'SketchLine.Create',
              'Constraint.CreateHorizontal',
              'Constraint.CreateVertical',
              'Dimension.CreateLength'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    ViewHelper.SetSketchPlane(Plane.PlaneXY)
    ctx.attempt("StartConstraintSketching", lambda: SketchHelper.StartConstraintSketching())
    pts = [(0, 0), (40, 1), (41, 20), (0, 20)]
    cs = []
    for i in range(4):
        a, b = pts[i], pts[(i + 1) % 4]
        r = SketchLine.Create(P2(*a), P2(*b))
        cs.append(list(r.CreatedCurves)[0])
    ctx.attempt("horizontal_c1", lambda: Constraint.CreateHorizontal(sel(cs[0])))
    ctx.attempt("horizontal_c3", lambda: Constraint.CreateHorizontal(sel(cs[2])))
    ctx.attempt("vertical_c2", lambda: Constraint.CreateVertical(sel(cs[1])))
    ctx.attempt("dim_length_c1_40", lambda: Dimension.CreateLength(sel(cs[0]), MM(40)))
    ctx.attempt("dim_length_c2_20", lambda: Dimension.CreateLength(sel(cs[1]), MM(20)))
    ctx.data["well_defined"] = _safe(lambda: ConstraintHelper.ModelWellDefined())
    ctx.data["satisfied"] = _safe(lambda: ConstraintHelper.ModelSatisfied())
    ctx.data["curves_mm"] = _safe(lambda: [[mm(c.Shape.StartPoint), mm(c.Shape.EndPoint)] for c in GetRootPart().Curves])
    if not (ctx.ok("horizontal_c1") or ctx.ok("dim_length_c1_40")):
        raise Exception("no constraint/dimension created")
    # leave sketch mode: the closed constrained loop becomes a planar surface body
    def _exit():
        try:
            return ViewHelper.SetViewMode(InteractionMode.Solid, None)
        except Exception:
            return ViewHelper.SetViewMode(InteractionMode.Solid)
    ctx.attempt("exit_to_solid", _exit)
    ctx.data["bodies_after_exit"] = _safe(lambda: [[unicode(b.Name), bbox(b)] for b in GetRootPart().Bodies])
    for b in list(GetRootPart().Bodies):
        ctx.attempt("name_body", lambda: set_name(b, "Constrained_Rect_Surface"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\02_sketch_constraint_901_pilot_rect_hv_dims.py")
