# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '03_pull_extrude_901_pilot_circle_r10_h25',
 'category': '03_pull',
 'feature': 'pull_extrude_face',
 'title': 'Sketch circle -> solidify -> extrude face',
 'params': {'profile': 'circle r10 on XY', 'h_mm': 25},
 'expect': {'bodies': 1, 'faces': 3, 'volume_mm3': 7853.981634},
 'commands': ['ViewHelper.SetSketchPlane',
              'SketchCircle.Create',
              'ViewHelper.SetViewMode(Solid)',
              'ExtrudeFaces.Execute'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    ViewHelper.SetSketchPlane(Plane.PlaneXY)
    SketchCircle.Create(P2(0, 0), MM(10))
    r = ViewHelper.SetViewMode(InteractionMode.Solid)
    root = GetRootPart()
    ctx.data["bodies_after_solidify"] = root.Bodies.Count
    sheet = list(root.Bodies)[-1]
    f = list(sheet.Faces)[0]
    r = ExtrudeFaces.Execute(sel(f), D(0, 0, 1), MM(25), ExtrudeFaceOptions())
    ctx.data["success"] = r.Success
    set_name(list(root.Bodies)[-1], "Cyl_Extruded")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\03_pull_extrude_901_pilot_circle_r10_h25.py")
