# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '04_edge_round_901_pilot_block_edge_r3',
 'category': '04_edge',
 'feature': 'edge_round',
 'title': 'Round one selected edge (selection-by-geometry check)',
 'params': {'block_mm': [40, 30, 20], 'edge': 'line edge nearest (20,30,20)', 'r_mm': 3},
 'expect': {'bodies': 1, 'faces': 7, 'edges': 15, 'vertices': 10, 'volume_mm3': 23922.743317},
 'commands': ['BlockBody.Create', 'ConstantRound.Execute'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Block_A")
    e = edge_nearest(b, (20, 30, 20), "Line")
    ctx.data["picked_edge_mid_mm"] = edge_mid(e)
    r = ConstantRound.Execute(sel(e), MM(3), ConstantRoundOptions())
    ctx.data["success"] = r.Success
    b = body_named("Block_A")
    ctx.data["cylinder_faces"] = len(faces(b, "Cylinder"))
    if ctx.data["cylinder_faces"] != 1:
        raise Exception("round face not created")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\04_edge_round_901_pilot_block_edge_r3.py")
