# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '05_boolean_subtract_901_pilot_block_minus_cyl',
 'category': '05_boolean',
 'feature': 'bool_subtract',
 'title': 'Subtract = Combine.Intersect + RemoveRegions',
 'params': {'target': 'block 40x40x20', 'tool': 'cylinder r5 through at (20,20)'},
 'expect': {'bodies': 1, 'faces': 7, 'volume_mm3': 30429.203673},
 'commands': ['Combine.Intersect(MakeSolidsOptions)', 'Combine.RemoveRegions'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    a = block((0, 0, 0), (40, 40, 20), "Plate")
    c = cylinder((20, 20, -5), (20, 20, 25), 5, "Cutter")
    r = Combine.Intersect(sel(a), sel(c), MakeSolidsOptions())
    root = GetRootPart()
    ctx.data["after_intersect"] = [[unicode(x.Name), round(x.Shape.Volume * 1e9, 3)] for x in root.Bodies]
    bs = sorted(list(root.Bodies), key=lambda x: x.Shape.Volume)
    keep = bs[-1]
    rm = bs[:-1]
    if rm:
        ctx.attempt("RemoveRegions", lambda: Combine.RemoveRegions(sel(rm)))
    if root.Bodies.Count > 1:
        ctx.attempt("Delete_fallback", lambda: Delete.Execute(sel([x for x in root.Bodies if x.Shape.Volume < keep.Shape.Volume])))
    b = sorted(list(root.Bodies), key=lambda x: x.Shape.Volume)[-1]
    set_name(b, "Plate_With_Hole")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\05_boolean_subtract_901_pilot_block_minus_cyl.py")
