# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '07_shell_open_902_pilot_block_top_tneg2',
 'category': '07_shell_offset',
 'feature': 'so_shell',
 'title': 'Shell removing the top face, thickness -2 (inward)',
 'params': {'block_mm': [40, 30, 20], 'remove': 'top face (+Z)', 't_mm': -2},
 'expect': {'bodies': 1, 'faces': 11, 'volume_mm3': 7152.0},
 'commands': ['BlockBody.Create', 'Shell.RemoveFaces'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Housing")
    t = top_face(b)
    ctx.data["top_face_center_mm"] = bbox_center(t)
    r = Shell.RemoveFaces(sel(t), MM(-2))
    ctx.data["success"] = r.Success
    ctx.data["bbox_after_mm"] = bbox(body_named("Housing"))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\07_shell_open_902_pilot_block_top_tneg2.py")
