# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '08_sheetmetal_convert_901_pilot_root_plate_t2',
 'category': '08_sheetmetal',
 'feature': 'sm_all',
 'title': 'Part.ConvertToSheetMetal() on root part with plate 100x50x2',
 'params': {'plate_mm': [100, 50, 2]},
 'expect': {'bodies': 1},
 'commands': ['Part.ConvertToSheetMetal (raw)'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    block((0, 0, 0), (100, 50, 2), "SM_Plate")
    root = GetRootPart()
    raw("sheetmetal", lambda: master(root).ConvertToSheetMetal())
    ctx.data["sheetmetal_aspect"] = _safe(lambda: unicode(master(root).SheetMetal))
    ctx.data["part_type"] = _safe(lambda: unicode(master(root).Type))
    if master(root).SheetMetal is None:
        raise Exception("SheetMetal aspect is None after convert")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\08_sheetmetal_convert_901_pilot_root_plate_t2.py")
