# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '08_sheetmetal_convert_902_pilot_component_plate_t2',
 'category': '08_sheetmetal',
 'feature': 'sm_all',
 'title': 'ConvertToSheetMetal() on a component part',
 'params': {'plate_mm': [100, 50, 2], 'component': 'SM_Part'},
 'expect': {'bodies': 1, 'components': 1},
 'commands': ['Part.ConvertToSheetMetal (raw)'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    c = component("SM_Part", lambda: block((0, 0, 0), (100, 50, 2), "SM_Plate"))
    t = _safe(lambda: c.Template) or master(c).Template
    raw("sheetmetal", lambda: t.ConvertToSheetMetal())
    ctx.data["sheetmetal_aspect"] = _safe(lambda: unicode(t.SheetMetal))
    if t.SheetMetal is None:
        raise Exception("SheetMetal aspect is None after convert")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\08_sheetmetal_convert_902_pilot_component_plate_t2.py")
