# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_instance_902_pilot_copy_paste',
 'category': '10_assembly',
 'feature': 'asm_instance',
 'title': 'Copy.ToClipboard + Paste.FromClipboard of a component',
 'params': {'component': 'Bolt (cyl r4 h30)', 'paste_move_mm': [50, 0, 0]},
 'expect': {'components': 2, 'bodies': 2},
 'commands': ['Copy.ToClipboard', 'Paste.FromClipboard', 'Move.Translate'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    comp = component("Bolt", lambda: cylinder((0, 0, 0), (0, 0, 30), 4, "Bolt_Body"))
    root = GetRootPart()
    Copy.ToClipboard(sel(comp))
    r = Paste.FromClipboard()
    created = _safe(lambda: list(r.CreatedObjects), [])
    ctx.data["paste_created"] = [unicode(x) for x in created]
    comps = list(root.Components)
    ctx.data["components_after_paste"] = len(comps)
    if len(comps) < 2:
        raise Exception("paste created no component")
    ctx.attempt("move_pasted", lambda: Move.Translate(sel(comps[-1]), D(1, 0, 0), MM(50), MoveOptions()))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\10_assembly_instance_902_pilot_copy_paste.py")
