# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_conditions_901_pilot_anchor_align_tangent_orient',
 'category': '10_assembly',
 'feature': 'asm_conditions',
 'title': 'Raw-API assembly conditions between two components',
 'params': {'Plate': 'block 60x40x10',
            'Pin': 'cyl r4 h30 at (100,20)',
            'conditions': ['anchor Plate',
                           'align Plate top / Pin bottom',
                           'tangent Pin cyl / Plate +X face',
                           'orient Plate top / Pin top']},
 'expect': {'components': 2, 'mating_conditions': 4},
 'commands': ['AnchorCondition.Create', 'AlignCondition.Create', 'TangentCondition.Create', 'OrientCondition.Create'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    cp = component("Plate", lambda: block((0, 0, 0), (60, 40, 10), "Plate_Body"))
    cq = component("Pin", lambda: cylinder((100, 20, 5), (100, 20, 35), 4, "Pin_Body"))
    root = GetRootPart()
    pb = list(cp.Content.Bodies)[0]
    qb = list(cq.Content.Bodies)[0]
    top, pin_bottom, pin_top = top_face(pb), bottom_face(qb), top_face(qb)
    pin_cyl = faces(qb, "Cylinder")[0]
    side = face_extreme(pb, (1, 0, 0), 1)
    ctx.data["pin_bbox_before"] = bbox(qb)
    ctx.attempt("anchor", lambda: raw("anchor", lambda: AnchorCondition.Create(root, cp)))
    ctx.attempt("align_plane_plane", lambda: raw("align", lambda: AlignCondition.Create(root, top, pin_bottom)))
    ctx.attempt("tangent_cyl_plane", lambda: raw("tangent", lambda: TangentCondition.Create(root, pin_cyl, side)))
    ctx.attempt("orient_plane_plane", lambda: raw("orient", lambda: OrientCondition.Create(root, top, pin_top)))
    ctx.data["pin_bbox_after"] = _safe(lambda: bbox(list(cq.Content.Bodies)[0]))
    ctx.data["mating_conditions"] = _safe(lambda: [unicode(m.GetType().Name) for m in master(root).MatingConditions])
    if not any(v.get("ok") for v in ctx.rec["items"].values()):
        raise Exception("no condition created")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\10_assembly_conditions_901_pilot_anchor_align_tangent_orient.py")
