# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_instance_901_pilot_component_create_x3',
 'category': '10_assembly',
 'feature': 'asm_instance',
 'title': 'Instances via raw Component.Create(root, template) + ComponentHelper.CopyToRoot',
 'params': {'component': 'Bolt (cyl r4 h30)', 'instances': 3, 'pitch_mm': 50},
 'expect': {'components': 4, 'bodies': 4, 'part_defs': 1},
 'commands': ['ComponentHelper.CreateAtRoot',
              'Component.Create (raw)',
              'ComponentHelper.CopyToRoot',
              'IComponent.Transform'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    comp = component("Bolt", lambda: cylinder((0, 0, 0), (0, 0, 30), 4, "Bolt_Body"))
    root = GetRootPart()
    tmpl = _safe(lambda: comp.Template) or master(comp).Template
    def inst(i):
        c = raw("instance", lambda: Component.Create(master(root), tmpl))
        c.Transform(Matrix.CreateTranslation(Vector.Create(MM(50 * i), 0, 0)))
        return c
    ctx.attempt("raw_Component.Create_1", lambda: inst(1))
    ctx.attempt("raw_Component.Create_2", lambda: inst(2))
    def cp():
        c = ComponentHelper.CopyToRoot(comp)
        c.Transform(Matrix.CreateTranslation(Vector.Create(0, MM(50), 0)))
        return c
    ctx.attempt("ComponentHelper.CopyToRoot", cp)
    if not (ctx.ok("raw_Component.Create_1") or ctx.ok("ComponentHelper.CopyToRoot")):
        raise Exception("no instancing path worked")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\10_assembly_instance_901_pilot_component_create_x3.py")
