# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '10_assembly_rigid_901_pilot_two_components',
 'category': '10_assembly',
 'feature': 'asm_conditions',
 'title': 'Raw-API RigidCondition between two components',
 'params': {'A': 'block 30x30x10', 'B': 'block 30x30x10 at x=40'},
 'expect': {'components': 2, 'mating_conditions': 1},
 'commands': ['RigidCondition.Create'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    ca = component("Part_A", lambda: block((0, 0, 0), (30, 30, 10), "Body_A"))
    cb = component("Part_B", lambda: block((40, 0, 0), (70, 30, 10), "Body_B"))
    root = GetRootPart()
    raw("rigid", lambda: RigidCondition.Create(root, ca, cb))

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\10_assembly_rigid_901_pilot_two_components.py")
