# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_note_901_pilot_text_on_datum',
 'category': '11_doc_attrs',
 'feature': 'doc_notes',
 'title': 'Note.Create on a datum plane and on a face',
 'params': {'text': 'HELLO_NOTE', 'font_size_mm': 5},
 'expect': {'bodies': 1, 'datum_planes': 1},
 'commands': ['DatumPlane.Create (raw)', 'Note.Create (raw)'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Note_Block")
    root = GetRootPart()
    lp = enum_pick(LocationPoint, "Center", "MiddleCenter", "TopLeft")
    dp = raw("datum", lambda: DatumPlane.Create(root, "Note_Plane", Plane.Create(Frame.Create(P(0, 0, 30), D(1, 0, 0), D(0, 1, 0)))))
    ctx.attempt("note_on_datum", lambda: raw("note1", lambda: Note.Create(dp, PointUV.Create(MM(10), MM(10)), lp, MM(5), "HELLO_NOTE")))
    ctx.attempt("note_on_face", lambda: raw("note2", lambda: Note.Create(top_face(b), PointUV.Create(0, 0), lp, MM(3), "FACE_NOTE")))
    ctx.data["datum_notes"] = _safe(lambda: master(dp).Notes.Count)
    if not (ctx.ok("note_on_datum") or ctx.ok("note_on_face")):
        raise Exception("no note created")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\11_doc_note_901_pilot_text_on_datum.py")
