# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_attrs_901_pilot_ns_layer_color',
 'category': '11_doc_attrs',
 'feature': 'doc_named_selection',
 'title': 'Named selection (2 faces) + layer + body/face colors',
 'params': {'named_selection': 'Top_Bottom', 'layer': 'L_red', 'face_color': [0, 200, 0]},
 'expect': {'bodies': 1},
 'commands': ['NamedSelection.Create',
              'NamedSelection.Rename',
              'Layers.Create',
              'Layers.AssignLayer',
              'Layers.SetColor',
              'ColorHelper.SetColor'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Attr_Block")
    t, bt = top_face(b), bottom_face(b)
    def ns():
        r = NamedSelection.Create(sel(t, bt), Selection.Empty())
        g = r.CreatedNamedSelection
        old = unicode(g.Name)
        NamedSelection.Rename(old, "Top_Bottom")
        return old
    ctx.attempt("named_selection", ns)
    ctx.attempt("layer_create", lambda: Layers.Create("L_red"))
    ctx.attempt("layer_assign", lambda: Layers.AssignLayer(sel(b), "L_red"))
    ctx.attempt("layer_color", lambda: Layers.SetColor(List[str](["L_red"]), Color.FromArgb(255, 255, 0, 0), True))
    ctx.attempt("face_color", lambda: ColorHelper.SetColor(sel(t), SetColorOptions(), Color.FromArgb(255, 0, 200, 0)))
    bad = [k for k, v in ctx.rec["items"].items() if not v["ok"]]
    if len(bad) == len(ctx.rec["items"]):
        raise Exception("all attribute items failed")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\11_doc_attrs_901_pilot_ns_layer_color.py")
