# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_units_901_pilot_imperial',
 'category': '11_doc_attrs',
 'feature': 'doc_units',
 'title': 'Document units -> imperial via raw Document.Units.ActiveUnitsSystem',
 'params': {'units': 'Imperial', 'block_in': [1, 2, 3]},
 'expect': {'bodies': 1},
 'commands': ['Document.Units.ActiveUnitsSystem (raw)'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    block((0, 0, 0), (25.4, 50.8, 76.2), "Inch_Block")
    doc = DocumentHelper.GetActiveDocument()
    u = doc.Units
    ctx.data["UnitsSystemType_names"] = list(System.Enum.GetNames(UnitsSystemType))
    ctx.data["before"] = [unicode(u.ActiveUnitsSystem), unicode(u.Length)]
    ctx.data["imperial_members"] = _safe(lambda: [n for n in dir(u.ImperialUnits) if not n.startswith("_")])
    v = enum_pick(UnitsSystemType, "Imperial", "English")
    raw("units", lambda: setattr(u, "ActiveUnitsSystem", v))
    ctx.data["after"] = [unicode(doc.Units.ActiveUnitsSystem), unicode(doc.Units.Length)]
    if ctx.data["after"] == ctx.data["before"]:
        raise Exception("units unchanged")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\11_doc_units_901_pilot_imperial.py")
