# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_drawing_901_pilot_A3_general_projected',
 'category': '11_doc_attrs',
 'feature': 'doc_drawing_sheet',
 'title': 'Drawing sheet + general + projected view (raw API)',
 'params': {'sheet_m': [0.42, 0.297], 'views': ['general', 'projected']},
 'expect': {'bodies': 1, 'drawing_sheets': 1},
 'commands': ['DrawingSheet.Create (raw)',
              'DrawingView.CreateGeneralView (raw)',
              'DrawingView.CreateProjectedView (raw)'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    block((0, 0, 0), (40, 30, 20), "Drawing_Block")
    doc = DocumentHelper.GetActiveDocument()
    ds = raw("sheet", lambda: DrawingSheet.Create(doc, 0.42, 0.297))
    ctx.attempt("sheet_name", lambda: raw("name", lambda: setattr(ds, "Name", "Sheet_A3")))
    v = ctx.attempt("general_view", lambda: raw("gv", lambda: DrawingView.CreateGeneralView(ds, master(GetRootPart()), Matrix.Identity, PointUV.Create(0.12, 0.15))))
    if v is not None:
        ctx.attempt("projected_view", lambda: raw("pv", lambda: DrawingView.CreateProjectedView(v, PointUV.Create(0.30, 0.15))))
    ctx.data["views"] = _safe(lambda: ds.Views.Count)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\11_doc_drawing_901_pilot_A3_general_projected.py")
