# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_view_901_pilot_named_iso_front',
 'category': '11_doc_attrs',
 'feature': 'doc_named_view',
 'title': 'Named views via ViewHelper.CreateNamedView',
 'params': {'views': ['Iso_View', 'Front_View']},
 'expect': {'bodies': 1},
 'commands': ['ViewHelper.SetProjection', 'ViewHelper.CreateNamedView', 'ViewHelper.ActivateNamedView'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    block((0, 0, 0), (40, 30, 20), "View_Block")
    ctx.data["active_window"] = _safe(lambda: unicode(GetActiveWindow()))
    ViewHelper.SetProjection(ViewHelper.ViewProjection.Isometric, True, False)
    ViewHelper.CreateNamedView("Iso_View")
    ViewHelper.SetProjection(ViewHelper.ViewProjection.Front, True, False)
    ViewHelper.CreateNamedView("Front_View")
    ok = ViewHelper.ActivateNamedView("Iso_View", True, False)
    ctx.data["activate_ok"] = ok
    if not ok:
        raise Exception("ActivateNamedView returned False")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\11_doc_view_901_pilot_named_iso_front.py")
