# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_material_901_pilot_steel_7850',
 'category': '11_doc_attrs',
 'feature': 'doc_material',
 'title': 'DocumentMaterial.Create + DesignBody.Material',
 'params': {'material': 'Steel_Test', 'density_kg_m3': 7850.0},
 'expect': {'bodies': 1},
 'commands': ['DocumentMaterial.Create (raw)', 'DesignBody.Material (raw)'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Steel_Block")
    doc = DocumentHelper.GetActiveDocument()
    m = raw("material", lambda: DocumentMaterial.Create(doc, "Steel_Test", 7850.0))
    raw("assign", lambda: setattr(master(b), "Material", m))
    ctx.data["body_material"] = _safe(lambda: unicode(master(b).Material.Name))
    ctx.data["mass_kg"] = _safe(lambda: master(b).MassProperties.Mass)
    ctx.attempt("library_first10", lambda: [unicode(x) for x in list(LibraryMaterial.Library.Keys)[:10]])
    if ctx.data["body_material"] != "Steel_Test":
        raise Exception("material not assigned")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\11_doc_material_901_pilot_steel_7850.py")
