# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_units_902_pilot_metric_meter',
 'category': '11_doc_attrs',
 'feature': 'doc_units',
 'title': 'Document units -> metric meters via raw Units.MetricUnits',
 'params': {'units': 'Metric/Meters'},
 'expect': {'bodies': 1},
 'commands': ['Document.Units.MetricUnits (raw)'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    block((0, 0, 0), (40, 30, 20), "Meter_Block")
    doc = DocumentHelper.GetActiveDocument()
    u = doc.Units
    mu = u.MetricUnits
    ctx.data["metric_type"] = unicode(mu.GetType().FullName)
    ctx.data["metric_members"] = [n for n in dir(mu) if not n.startswith("_")]
    ctx.data["MetricLengthUnit_names"] = list(System.Enum.GetNames(MetricLengthUnit))
    ctx.data["before"] = unicode(u.Length)
    meters = None
    for n in System.Enum.GetNames(MetricLengthUnit):
        if n.lower() in ("meters", "meter", "m"):
            meters = System.Enum.Parse(MetricLengthUnit, n)
    def by_ctor():
        t = mu.GetType()
        for c in t.GetConstructors():
            ctx.note("ctor", unicode(c))
        raise Exception("inspect only")
    ctx.attempt("ctor_list", by_ctor)
    def set_len():
        m2 = u.MetricUnits
        m2.Length = meters
        raw("metric", lambda: setattr(u, "MetricUnits", m2))
        return unicode(doc.Units.Length)
    ctx.attempt("set_MetricUnits.Length", set_len)
    ctx.data["after"] = unicode(doc.Units.Length)
    if ctx.data["after"] == ctx.data["before"]:
        raise Exception("length unit unchanged")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\11_doc_units_902_pilot_metric_meter.py")
