# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, V19 RunScript). Generated by the phase-A pilot generator.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '11_doc_section_901_pilot_plane_z10',
 'category': '11_doc_attrs',
 'feature': 'doc_named_view',
 'title': 'Section plane via ViewHelper.SetSectionPlane (z=10)',
 'params': {'plane': 'z=10'},
 'expect': {'bodies': 1},
 'commands': ['ViewHelper.SetSectionPlane'],
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\_pilot\\out'}

def build(ctx):
    block((0, 0, 0), (40, 30, 20), "Section_Block")
    r = ViewHelper.SetSectionPlane(Plane.Create(Frame.Create(P(0, 0, 10), D(1, 0, 0), D(0, 1, 0))))
    ctx.data["success"] = r.Success
    ctx.data["mode"] = unicode(ViewHelper.GetViewMode())
    if not r.Success:
        raise Exception("SetSectionPlane failed")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\_pilot\cases\11_doc_section_901_pilot_plane_z10.py")
