# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B12_surface_holes_mesh.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '14_hole_csink_001_90deg',
 'category': '14_holes_threads',
 'commands': ['StandardHoles.Create(nomFaceToLocations, StandardHolesOptions)',
              'StandardHoles.Modify*',
              'StandardHoles.Find/Convert',
              '(raw API) Hole.Create'],
 'expect': {'bodies': 1},
 'feature': 'hole_standard',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\14_holes_threads',
 'params': {'csink_angle_deg': 90},
 'priority': 'P1',
 'title': 'Standard holes (simple, counterbore, countersink, tapped, cosmetic thread): 001_90deg'}


def build(ctx):
    def std_hole(ctx, b, x, y, opts):
        top = top_face(b)
        pt = P(x, y, bbox(b)[1][2])
        HL = find_type(ctx, "HoleLocation")
        _safe(lambda: ctor_sigs(ctx, "HoleLocation"))
        mf = master(top)
        uv = _safe(lambda: mf.Shape.ProjectPoint(pt).Param)
        pool = [("IDesignFace", top), ("DesignFace", mf), ("Point", pt), ("PointUV", uv),
                ("IList`1", List[Point]([pt])), ("ICollection`1", List[Point]([pt])), ("IEnumerable`1", List[Point]([pt]))]
        def by_auto():
            loc = auto_new(ctx, "HoleLocation", HL, pool)
            L = List[HL]()
            L.Add(loc)
            return StandardHoles.Create(L, Selection.Empty(), opts)
        def by_auto2():
            loc = auto_new(ctx, "HoleLocation2", HL, pool)
            L = List[HL]()
            L.Add(loc)
            return StandardHoles.Create(L, opts)
        r = first_ok(ctx, "standard_hole", [by_auto, by_auto2])
        ctx.data["hole_result"] = _safe(lambda: [n for n in dir(r) if not n.startswith("_")])
        return r

    o = StandardHolesOptions()
    ctx.data["hole_opts_default"] = dict((n, _safe(lambda: unicode(getattr(o, n)))) for n in ["SeriesName", "FastenerName", "HoleFit", "HoleRadius", "DrillSize", "HoleDepth", "DepthMeasurement", "Tapped"])

    b = block((0, 0, 0), (40, 30, 20), "Csink_Block")
    setp(ctx, o, [("HoleRadius", MM(3)), ("HoleDepth", MM(12)), ("CountersinkRadius", MM(6)), ("CountersinkAngle", DEG(90))], "hole_opts")
    std_hole(ctx, b, 20, 15, o)
    intent_range("volume_removed_mm3", 24000 - total_volume(), 300, 1500)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\14_holes_threads\14_hole_csink_001_90deg.py")
