# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R2_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '14_hole_cbore_001_M6',
 'category': '14_holes_threads',
 'commands': ['StandardHoles.Create(nomFaceToLocations, StandardHolesOptions)',
              'StandardHoles.Modify*',
              'StandardHoles.Find/Convert',
              '(raw API) Hole.Create'],
 'expect': {'bodies': 1},
 'feature': 'hole_standard',
 'inventory_expect': None,
 'notes': 'fix R2: secondarySelection None instead of Selection.Empty(); explicit HoleRadius 3.2 mm (options '
          'default radius is 0)',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\14_holes_threads',
 'params': {'counterbore': True, 'fastener': 'M6', 'series': 'ISO'},
 'priority': 'P1',
 'title': 'Standard holes (simple, counterbore, countersink, tapped, cosmetic thread): 001_M6'}


def build(ctx):
    def std_hole(ctx, b, x, y, opts):
        top = top_face(b)
        pt = P(x, y, bbox(b)[1][2])
        HL = find_type(ctx, "HoleLocation")
        _safe(lambda: ctor_sigs(ctx, "HoleLocation"))
        mf = master(top)
        uv = _safe(lambda: mf.Shape.ProjectPoint(pt).Param)
        pool = [("IDesignFace", top), ("DesignFace", mf), ("Point", pt), ("PointUV", uv),
                ("IList`1", List[Point]([pt])), ("ICollection`1", List[Point]([pt])), ("IEnumerable`1", List[Point]([pt]))]
        def by_null():
            loc = auto_new(ctx, "HoleLocation", HL, pool)
            L = List[HL]()
            L.Add(loc)
            return StandardHoles.Create(L, None, opts)
        def by_opts():
            loc = auto_new(ctx, "HoleLocation2", HL, pool)
            L = List[HL]()
            L.Add(loc)
            return StandardHoles.Create(L, opts)
        r = first_ok(ctx, "standard_hole", [by_null, by_opts])
        ctx.data["hole_result"] = _safe(lambda: [n for n in dir(r) if not n.startswith("_")])
        return r
    o = StandardHolesOptions()
    ctx.data["hole_opts_default"] = dict((n, _safe(lambda: unicode(getattr(o, n)))) for n in ["SeriesName", "FastenerName", "HoleFit", "HoleRadius", "DrillSize", "HoleDepth", "DepthMeasurement", "Tapped"])

    b = block((0, 0, 0), (40, 30, 20), "Cbore_Block")
    setp(ctx, o, [("SeriesName", "ISO"), ("FastenerName", "M6"), ("HoleFit", _safe(lambda: HoleFit.Medium)), ("HoleRadius", MM(3.2)),
                  ("CounterboreRadius", MM(5.5)), ("CounterboreDepth", MM(6.5)), ("HoleDepth", MM(15))], "hole_opts")
    std_hole(ctx, b, 20, 15, o)
    ctx.data["faces_after"] = face_count(largest())
    intent_range("volume_removed_mm3", 24000 - total_volume(), 100, 2000)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\14_holes_threads\14_hole_cbore_001_M6.py")
