# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B12_surface_holes_mesh.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '15_mesh_convert_001_block',
 'category': '15_mesh_facet',
 'commands': ['FacetConvert.Create',
              'FacetReduce/FacetSmooth/FacetRemesh/FacetMerge/FacetSubtract/FacetThicken',
              'STLFile.Import/Insert'],
 'expect': {'meshes': 1},
 'feature': 'mesh_facet',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\15_mesh_facet',
 'params': {},
 'priority': 'P2',
 'title': 'Facet (mesh) bodies: convert solid->mesh, reduce, smooth, thicken, boolean: 001_block'}


def build(ctx):
    b = block((0, 0, 0), (40, 30, 20), "Mesh_Block")
    o = FacetConvertOptions()
    ctx.data["fc_opts_members"] = [n for n in dir(o) if not n.startswith("_")]
    first_ok(ctx, "facet_convert", [lambda: FacetConvert.Create(sel(b), o), lambda: FacetConvert.Create(sel(b))])
    _safe(lambda: set_name(list(GetRootPart().Meshes)[0], "Block_Mesh"))
    ctx.data["facets"] = _safe(lambda: list(GetRootPart().Meshes)[0].Shape.Facets.Count)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\15_mesh_facet\15_mesh_convert_001_block.py")
