# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R2_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '15_mesh_reduce_001_50pct',
 'category': '15_mesh_facet',
 'commands': ['FacetConvert.Create',
              'FacetReduce/FacetSmooth/FacetRemesh/FacetMerge/FacetSubtract/FacetThicken',
              'STLFile.Import/Insert'],
 'expect': {'meshes': 1},
 'feature': 'mesh_facet',
 'inventory_expect': None,
 'notes': 'fix R2: facet count read via several mesh shape members; coarse sphere r10 to keep FacetReduce '
          'fast',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\15_mesh_facet',
 'params': {},
 'priority': 'P2',
 'title': 'Facet (mesh) bodies: convert solid->mesh, reduce, smooth, thicken, boolean: 001_50pct'}


def build(ctx):
    s = sphere((0, 0, 0), 10, "Reduce_Sphere")
    FacetConvert.Create(sel(s), FacetConvertOptions())
    m = list(GetRootPart().Meshes)[0]
    _safe(lambda: set_name(m, "Sphere_Mesh"))
    def nfac():
        mm = list(GetRootPart().Meshes)[0]
        sh = mm.Shape
        for f in [lambda: sh.Facets.Count, lambda: len(list(sh.Facets)), lambda: sh.FacetCount, lambda: sh.NumberOfFacets,
                  lambda: sh.Triangles.Count, lambda: len(list(sh.Triangles))]:
            v = _safe(f)
            if v:
                return int(v)
        return None
    ctx.data["mesh_shape_members"] = _safe(lambda: [n for n in dir(m.Shape) if not n.startswith("_")][:80])
    n0 = nfac()
    o = FacetReduceOptions()
    ctx.data["fr_defaults"] = [_safe(lambda: unicode(o.DefaultTriangleReduction)), _safe(lambda: unicode(o.DefaultMaxError))]
    setp(ctx, o, [("TriangleReduction", 0.5)], "fr_opts")
    first_ok(ctx, "reduce", [lambda: FacetReduce.Create(sel(m), o), lambda: FacetReduce.Create(sel(list(GetRootPart().Meshes)), o)])
    n1 = nfac()
    ctx.data["facets"] = [n0, n1]
    if n0 and n1:
        intent("reduced", n1 < n0, True)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\15_mesh_facet\15_mesh_reduce_001_50pct.py")
