# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R2_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '15_mesh_stl_import_001',
 'category': '15_mesh_facet',
 'commands': ['FacetConvert.Create',
              'FacetReduce/FacetSmooth/FacetRemesh/FacetMerge/FacetSubtract/FacetThicken',
              'STLFile.Import/Insert'],
 'expect': {'components': 1},
 'feature': 'mesh_facet',
 'inventory_expect': None,
 'notes': 'fix R2: STL exported by this case to 15_mesh_facet\\\\_inputs (scdm_cases only), then inserted; '
          'SpaceClaim puts the mesh into a new component, so the mesh is counted inside components',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\15_mesh_facet',
 'params': {'file': 'exported STL of cylinder'},
 'priority': 'P2',
 'title': 'Facet (mesh) bodies: convert solid->mesh, reduce, smooth, thicken, boolean: import_001'}


def build(ctx):
    import System
    d = System.IO.Path.Combine(CASE["out_dir"], "_inputs")
    if not System.IO.Directory.Exists(d):
        System.IO.Directory.CreateDirectory(d)
    stl = System.IO.Path.Combine(d, "cylinder_r10_h30.stl")
    cylinder((0, 0, 0), (0, 0, 30), 10, "Stl_Source_Cyl")
    first_ok(ctx, "export_stl", [lambda: STLFile.Export(stl), lambda: DocumentSave.Execute(stl)])
    ctx.data["stl_bytes"] = _safe(lambda: System.IO.FileInfo(stl).Length)
    Delete.Execute(sel(bodies_now()))
    io = STLImportOptions()
    setp(ctx, io, [("ImportType", _safe(lambda: enum_pick(type(io.ImportType), "ConnectedMesh")))], "stl_opts")
    first_ok(ctx, "insert_stl", [lambda: STLFile.Insert(stl, io), lambda: DocumentInsert.Execute(stl)])
    ms = []
    for c in GetRootPart().Components:
        ms += list(_safe(lambda: c.Template.Meshes, []) or [])
    ms += list(GetRootPart().Meshes)
    ctx.data["meshes_found"] = len(ms)
    if ms:
        _safe(lambda: set_name(ms[0], "Imported_Cyl_Mesh"))
    intent("meshes_in_doc", len(ms), 1)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\15_mesh_facet\15_mesh_stl_import_001.py")
