# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_spline_003_end_tangents',
 'category': '02_sketch',
 'commands': ['SketchNurbs.CreateFrom2DPoints(periodic, points)'],
 'expect': {'bodies': 0, 'root_curves': 1},
 'feature': 'sk_spline',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'endVector': [1, -1], 'n': 4, 'startVector': [1, 1]},
 'priority': 'P0',
 'title': 'Sketch spline (NURBS through points): 003_end_tangents'}


def build(ctx):
    sketch_mode()
    SketchNurbs.CreateFrom2DPoints(False, P2L([(0, 0), (10, 5), (20, 5), (30, 0)]), VectorUV.Create(MM(10), MM(10)), VectorUV.Create(MM(10), MM(-10)))
    finish_sketch(ctx, "Spline_Tangents")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_spline_003_end_tangents.py")
