# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_spline_002_periodic_6pts',
 'category': '02_sketch',
 'commands': ['SketchNurbs.CreateFrom2DPoints(periodic, points)'],
 'expect': {'bodies': 1, 'faces': 1},
 'feature': 'sk_spline',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'n': 6, 'periodic': True},
 'priority': 'P0',
 'title': 'Sketch spline (NURBS through points): 002_periodic_6pts'}


def build(ctx):
    pts = []
    for i in range(6):
        a = math.radians(60 * i)
        r = 15 if i % 2 == 0 else 10
        pts.append((r * math.cos(a), r * math.sin(a)))
    sketch_mode()
    SketchNurbs.CreateFrom2DPoints(True, P2L(pts))
    finish_sketch(ctx, "Spline_Periodic")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_spline_002_periodic_6pts.py")
