# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_dim_003_angle_30',
 'category': '02_sketch',
 'commands': ['Dimension.CreateLength',
              'Dimension.CreateRadial',
              'Dimension.CreateDiameter',
              'Dimension.CreateAngle',
              'Dimension.CreateDistance',
              'Dimension.Modify'],
 'expect': {},
 'feature': 'sk_dimensions',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'value_deg': 30},
 'priority': 'P1',
 'title': 'Sketch dimensions (length/radial/diameter/angle/distance): 003_angle_30'}


def build(ctx):
    sketch_mode()
    ctx.attempt("StartConstraintSketching", lambda: SketchHelper.StartConstraintSketching())
    l1 = cc(SketchLine.Create(P2(0, 0), P2(30, 0)))[0]
    l2 = cc(SketchLine.Create(P2(0, 0), P2(25, 10)))[0]
    first_ok(ctx, "angle_dim", [
        lambda: Dimension.CreateAngle(sel(l1), sel(l2), False, DEG(30)),
        lambda: Dimension.CreateAngle(sel(l1), sel(l2), True, DEG(30))])
    finish_sketch(ctx, "Dim_Angle30")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_dim_003_angle_30.py")
