# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\R1_fixes.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_round2d_001_rect_corner_r4',
 'category': '02_sketch',
 'commands': ['SketchPoint.Create',
              'SketchOffsetCurve.Create',
              'SketchCorner.Create',
              'Sketch2DRound.Create',
              'TrimSketchCurve.Execute',
              'SplitSketchCurve.Execute'],
 'expect': {},
 'feature': 'sk_point_offset',
 'inventory_expect': None,
 'notes': 'retry R1: recorded-journal form '
          'Sketch2DRound.Create(SelectionPoint.Create(GetRootPart().Curves[i], u), ..., r) with raw curve '
          'parameters near the corner',
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'r_mm': 4, 'rect': [40, 20]},
 'priority': 'P2',
 'title': 'Sketch point / offset curve / corner / 2D round / trim / split: 001_rect_corner_r4'}


def build(ctx):
    def not_feasible_if_all_fail(ctx, key, fns, reason):
        try:
            return first_ok(ctx, key, fns)
        except Exception as e:
            raise NotFeasible(reason + " | last error: " + unicode(e)[-300:])

    sketch_mode()
    for p, q in [((0, 0), (40, 0)), ((40, 0), (40, 20)), ((40, 20), (0, 20)), ((0, 20), (0, 0))]:
        SketchLine.Create(P2(*p), P2(*q))
    cs = curves_now()
    ctx.data["curves_before"] = len(cs)
    cb = root_curve_near((20, 0, 0))
    cl = root_curve_near((0, 10, 0))
    SP = globals().get("SelectionPoint") or find_type(ctx, "SelectionPoint")
    def u_at(c, pt):
        return c.Shape.ProjectPoint(P(*pt)).Param
    ub, ul = u_at(cb, (3, 0, 0)), u_at(cl, (0, 3, 0))
    ctx.data["u"] = [ub, ul]
    def chk():
        n = len(curves_now())
        if n < 5:
            raise Exception("no fillet arc (curves=%d)" % n)
    def f1():
        Sketch2DRound.Create(SP.Create(cl, ul), SP.Create(cb, ub), MM(4))
        chk()
    def f2():
        Sketch2DRound.Create(SP.Create(cl, System.Array[float]([ul])), SP.Create(cb, System.Array[float]([ub])), MM(4))
        chk()
    def f3():
        Sketch2DRound.Create(SP.Create(cb, ub), SP.Create(cl, ul), MM(4))
        chk()
    def f4():
        Sketch2DRound.Create(SP.CreateCurve(cl, ul), SP.CreateCurve(cb, ub), MM(4))
        chk()
    not_feasible_if_all_fail(ctx, "round2d", [f1, f2, f3, f4], "Sketch2DRound with SelectionPoint not usable headless")
    ctx.data["curves_after"] = len(curves_now())
    finish_sketch(ctx, "Rect_Round4")
    b = largest() if bodies_now() else None
    if b is not None:
        intent("area_mm2", round(shape_of(b).Area * 1e6, 2), round(800 - (4 - 3.14159265) * 16, 2), 0.05)

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_round2d_001_rect_corner_r4.py")
