# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_circle_001_r10',
 'category': '02_sketch',
 'commands': ['SketchCircle.Create(Point2D,radius)'],
 'expect': {'area_mm2': 314.159265, 'bodies': 1, 'faces': 1},
 'feature': 'sk_circle',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'c': [0, 0], 'r_mm': 10},
 'priority': 'P0',
 'title': 'Sketch circle: 001_r10'}


def build(ctx):
    sketch_mode()
    SketchCircle.Create(P2(0, 0), MM(10))
    finish_sketch(ctx, "Circle_R10")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_circle_001_r10.py")
