# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_ellipse_001_a20_b10',
 'category': '02_sketch',
 'commands': ['SketchEllipse.Create'],
 'expect': {'area_mm2': 628.318531, 'bodies': 1, 'faces': 1},
 'feature': 'sk_ellipse',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'a_mm': 20, 'b_mm': 10},
 'priority': 'P1',
 'title': 'Sketch ellipse: 001_a20_b10'}


def build(ctx):
    sketch_mode()
    SketchEllipse.Create(P2(0, 0), DirectionUV.Create(1, 0), DirectionUV.Create(0, 1), MM(20), MM(10))
    finish_sketch(ctx, "Ellipse_20x10")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_ellipse_001_a20_b10.py")
