# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_constraint_002_tangent_line_arc',
 'category': '02_sketch',
 'commands': ['Constraint.Create*',
              'SketchHelper.StartConstraintSketching',
              'ConstraintHelper.ModelWellDefined'],
 'expect': {},
 'feature': 'sk_constraints',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'constraints': ['Tangent']},
 'priority': 'P1',
 'title': 'Sketch constraints (horizontal, vertical, coincident, tangent, parallel, perpendicular, '
          'concentric, equal, midpoint, symmetric, fixed): 002_tangent_line_arc'}


def build(ctx):
    sketch_mode()
    ctx.attempt("StartConstraintSketching", lambda: SketchHelper.StartConstraintSketching())
    l = cc(SketchLine.Create(P2(0, 0), P2(20, 0)))[0]
    a = cc(SketchArc.Create(P2(20, 10), P2(20, 1), P2(30, 10)))[0]
    first_ok(ctx, "tangent", [
        lambda: Constraint.CreateTangent(SelectionPoint.CreateCurve(l, None), SelectionPoint.CreateCurve(a, None)),
        lambda: Constraint.CreateTangent(SelectionPoint.CreateCurve(l, MM(20)), SelectionPoint.CreateCurve(a, 0.0)),
        lambda: Constraint.CreateTangent(SelectionPoint.Create(l, System.Array[float]([MM(20)])), SelectionPoint.Create(a, System.Array[float]([0.0])))])
    ctx.data["satisfied"] = _safe(lambda: ConstraintHelper.ModelSatisfied())
    finish_sketch(ctx, "Tangent_LineArc")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_constraint_002_tangent_line_arc.py")
