# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_constraint_003_concentric_equal',
 'category': '02_sketch',
 'commands': ['Constraint.Create*',
              'SketchHelper.StartConstraintSketching',
              'ConstraintHelper.ModelWellDefined'],
 'expect': {},
 'feature': 'sk_constraints',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'constraints': ['Concentric', 'EqualRadius']},
 'priority': 'P1',
 'title': 'Sketch constraints (horizontal, vertical, coincident, tangent, parallel, perpendicular, '
          'concentric, equal, midpoint, symmetric, fixed): 003_concentric_equal'}


def build(ctx):
    sketch_mode()
    ctx.attempt("StartConstraintSketching", lambda: SketchHelper.StartConstraintSketching())
    c1 = cc(SketchCircle.Create(P2(0, 0), MM(10)))[0]
    c2 = cc(SketchCircle.Create(P2(1, 1), MM(7)))[0]
    ctx.attempt("concentric", lambda: Constraint.CreateConcentric(sel(c1), sel(c2)))
    ctx.attempt("equal_radius", lambda: Constraint.CreateEqualRadius(sel(c1), sel(c2)))
    ctx.data["satisfied"] = _safe(lambda: ConstraintHelper.ModelSatisfied())
    if not (ctx.ok("concentric") or ctx.ok("equal_radius")):
        raise Exception("no constraint created")
    finish_sketch(ctx, "Concentric_Equal")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_constraint_003_concentric_equal.py")
