# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_arc_001_center_r20_90deg',
 'category': '02_sketch',
 'commands': ['SketchArc.Create',
              'SketchArc.Create3PointArc',
              'SketchArc.CreateSweepArc',
              'SketchArc.CreateTangentArc'],
 'expect': {'bodies': 0, 'root_curves': 1},
 'feature': 'sk_arc',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'c': [0, 0], 'end': [0, 20], 'start': [20, 0]},
 'priority': 'P0',
 'title': 'Sketch arc (center/3-point/tangent/sweep): 001_center_r20_90deg'}


def build(ctx):
    sketch_mode()
    SketchArc.Create(P2(0, 0), P2(20, 0), P2(0, 20))
    finish_sketch(ctx, "Arc_Center")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_arc_001_center_r20_90deg.py")
