# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_line_003_construction',
 'category': '02_sketch',
 'commands': ['SketchLine.Create', 'SketchLine.CreateChain'],
 'expect': {},
 'feature': 'sk_line',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'isConstruction': True, 'p0': [0, 0], 'p1': [0, 40]},
 'priority': 'P0',
 'title': 'Sketch line / polyline: 003_construction'}


def build(ctx):
    sketch_mode()
    SketchLine.Create(P2(0, 0), P2(0, 40), True)
    SketchLine.Create(P2(-10, 0), P2(10, 0))
    finish_sketch(ctx, "Construction")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_line_003_construction.py")
