# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_designcurve_001_3d_line',
 'category': '02_sketch',
 'commands': ['DesignCurve.Create (API)', 'SketchCurve.Create', 'ProjectToSketch.Create'],
 'expect': {'bodies': 0, 'root_curves': 1},
 'feature': 'sk_datum_curve',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'p0': [0, 0, 0], 'p1': [10, 20, 30]},
 'priority': 'P1',
 'title': '3D design curve (line/arc/spline outside sketch): 001_3d_line'}


def build(ctx):
    dcurve(seg((0, 0, 0), (10, 20, 30)), "Line3D")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_designcurve_001_3d_line.py")
