# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_offset_001_rect_offset3',
 'category': '02_sketch',
 'commands': ['SketchPoint.Create',
              'SketchOffsetCurve.Create',
              'SketchCorner.Create',
              'Sketch2DRound.Create',
              'TrimSketchCurve.Execute',
              'SplitSketchCurve.Execute'],
 'expect': {},
 'feature': 'sk_point_offset',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'offset_mm': 3, 'rect': [40, 20]},
 'priority': 'P2',
 'title': 'Sketch point / offset curve / corner / 2D round / trim / split: 001_rect_offset3'}


def build(ctx):
    sketch_mode()
    r = SketchRectangle.Create(P2(0, 0), P2(40, 0), P2(40, 20))
    cs = cc(r)
    ctx.data["rect_curves"] = len(cs)
    first_ok(ctx, "offset", [
        lambda: SketchOffsetCurve.Create(sel(cs), MM(3)),
        lambda: SketchOffsetCurve.Create(sel(cs), P2(-3, -3))])
    finish_sketch(ctx, "Rect_Offset3")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_offset_001_rect_offset3.py")
