# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_circle_002_two_concentric_r5_r10',
 'category': '02_sketch',
 'commands': ['SketchCircle.Create(Point2D,radius)'],
 'expect': {},
 'feature': 'sk_circle',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'r_mm': [5, 10]},
 'priority': 'P0',
 'title': 'Sketch circle: 002_two_concentric_r5_r10'}


def build(ctx):
    sketch_mode()
    SketchCircle.Create(P2(0, 0), MM(5))
    SketchCircle.Create(P2(0, 0), MM(10))
    finish_sketch(ctx, "Concentric")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_circle_002_two_concentric_r5_r10.py")
