# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_polygon_002_pent_r8',
 'category': '02_sketch',
 'commands': ['SketchPolygon.Create(Point2D,dirX,dirY,internalRadius,n)'],
 'expect': {'bodies': 1, 'faces': 1},
 'feature': 'sk_polygon',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'n': 5, 'r_mm': 8},
 'priority': 'P2',
 'title': 'Sketch polygon: 002_pent_r8'}


def build(ctx):
    sketch_mode()
    SketchPolygon.Create(P2(0, 0), DirectionUV.Create(1, 0), DirectionUV.Create(0, 1), MM(8), 5)
    finish_sketch(ctx, "Pentagon")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_polygon_002_pent_r8.py")
