# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_rect_002_rotated_30deg',
 'category': '02_sketch',
 'commands': ['SketchRectangle.Create(p1,p2,p3)'],
 'expect': {'area_mm2': 800.0, 'bodies': 1, 'faces': 1},
 'feature': 'sk_rect',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'p': '3-point rotated 30deg'},
 'priority': 'P1',
 'title': 'Sketch rectangle: 002_rotated_30deg'}


def build(ctx):
    c, s = math.cos(math.radians(30)), math.sin(math.radians(30))
    p2 = (40 * c, 40 * s)
    p3 = (p2[0] - 20 * s, p2[1] + 20 * c)
    sketch_mode()
    SketchRectangle.Create(P2(0, 0), P2(*p2), P2(*p3))
    finish_sketch(ctx, "Rect_Rot30")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_rect_002_rotated_30deg.py")
