# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_arc_002_3point',
 'category': '02_sketch',
 'commands': ['SketchArc.Create',
              'SketchArc.Create3PointArc',
              'SketchArc.CreateSweepArc',
              'SketchArc.CreateTangentArc'],
 'expect': {'bodies': 0, 'root_curves': 1},
 'feature': 'sk_arc',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'pts': [[0, 0], [10, 5], [20, 0]]},
 'priority': 'P0',
 'title': 'Sketch arc (center/3-point/tangent/sweep): 002_3point'}


def build(ctx):
    sketch_mode()
    SketchArc.Create3PointArc(P2(0, 0), P2(10, 5), P2(20, 0))
    finish_sketch(ctx, "Arc_3Pt")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_arc_002_3point.py")
