# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_designcurve_002_helix_spline',
 'category': '02_sketch',
 'commands': ['DesignCurve.Create (API)', 'SketchCurve.Create', 'ProjectToSketch.Create'],
 'expect': {'bodies': 0, 'root_curves': 1},
 'feature': 'sk_datum_curve',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'type': 'NurbsCurve.CreateThroughPoints helix 3 turns'},
 'priority': 'P1',
 'title': '3D design curve (line/arc/spline outside sketch): 002_helix_spline'}


def build(ctx):
    pts = []
    for i in range(3 * 16 + 1):
        t = 2 * math.pi * i / 16.0
        pts.append((10 * math.cos(t), 10 * math.sin(t), 5 * i / 16.0))
    dcurve(spline_curve(pts), "Helix3Turns")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_designcurve_002_helix_spline.py")
