# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_line_002_chain_closed_tri',
 'category': '02_sketch',
 'commands': ['SketchLine.Create', 'SketchLine.CreateChain'],
 'expect': {'area_mm2': 600.0, 'bodies': 1, 'faces': 1},
 'feature': 'sk_line',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'close': True, 'pts': [[0, 0], [40, 0], [20, 30]]},
 'priority': 'P0',
 'title': 'Sketch line / polyline: 002_chain_closed_tri'}


def build(ctx):
    sketch_mode()
    pts = List[Point]()
    for p in [(0, 0, 0), (40, 0, 0), (20, 30, 0)]:
        pts.Add(P(*p))
    SketchLine.CreateChain(pts, True)
    finish_sketch(ctx, "Triangle")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_line_002_chain_closed_tri.py")
