# -*- coding: utf-8 -*-
# scdm_cases case script (SpaceClaim 2019 R3, RunScript). Generated by _gen\gen_cases.py from _gen\specs\B02_sketch.py.
# Batch: loaded by _framework\scdm_fw.py run_case_files(). Standalone: SpaceClaim.exe /RunScript="<this file>" /ExitAfterScript=True /Headless=True
CASE = {'case_id': '02_sketch_constraint_001_hv_rect',
 'category': '02_sketch',
 'commands': ['Constraint.Create*',
              'SketchHelper.StartConstraintSketching',
              'ConstraintHelper.ModelWellDefined'],
 'expect': {},
 'feature': 'sk_constraints',
 'inventory_expect': None,
 'out_dir': 'D:\\training\\caedecoder\\scdm_cases\\02_sketch',
 'params': {'constraints': ['Horizontal', 'Vertical']},
 'priority': 'P1',
 'title': 'Sketch constraints (horizontal, vertical, coincident, tangent, parallel, perpendicular, '
          'concentric, equal, midpoint, symmetric, fixed): 001_hv_rect'}


def build(ctx):
    sketch_mode()
    ctx.attempt("StartConstraintSketching", lambda: SketchHelper.StartConstraintSketching())
    pts = [(0, 0), (40, 1), (41, 20), (0, 20)]
    cs = [cc(SketchLine.Create(P2(*pts[i]), P2(*pts[(i + 1) % 4])))[0] for i in range(4)]
    ctx.attempt("horizontal_c1", lambda: Constraint.CreateHorizontal(sel(cs[0])))
    ctx.attempt("horizontal_c3", lambda: Constraint.CreateHorizontal(sel(cs[2])))
    ctx.attempt("vertical_c2", lambda: Constraint.CreateVertical(sel(cs[1])))
    ctx.attempt("vertical_c4", lambda: Constraint.CreateVertical(sel(cs[3])))
    ctx.data["satisfied"] = _safe(lambda: ConstraintHelper.ModelSatisfied())
    if not (ctx.ok("horizontal_c1") or ctx.ok("vertical_c2")):
        raise Exception("no constraint created")
    finish_sketch(ctx, "HV_Rect")

if "SCDM_BATCH" not in globals():
    execfile(r"D:\training\caedecoder\scdm_cases\_framework\scdm_fw.py")
    run_standalone(CASE, build, r"D:\training\caedecoder\scdm_cases\02_sketch\02_sketch_constraint_001_hv_rect.py")
